### ISSUE TITLE
Build failing on Windows

### ISSUE THREAD

**Issue by kylegifford** [stealjs/steal-tools#1009]
We have a project that is building fine on Mac, but it errors out on Windows. We get the following error:

`(node:28956) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, lstat 'C:\Users\kyle\Projects\themes\default\assets\fonts\icons.eot'
(node:28956) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:28956) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

The project is running inside of `C:\Users\kyle\Projects\grier\grier-devlan`

**Comment by matthewp** [comment]
`C:\Users\kyle\Projects\themes\default\assets\fonts\icons.eot` assuming this file doesn't exist?

**Comment by matthewp** [comment]
Ok, so the path is wrong. Any idea where this comes from (most likely a css/less file), if so could you post a snippet of that ?

**Comment by matthewp** [comment]
This is a breaking example project. Fails on Windows but works on Mac.

https://github.com/stealjs/less-bug-build-windows

**Comment by matthewp** [comment]
The bug is in steal-less: https://github.com/stealjs/steal-less/blob/fb1ea0e41c9e1f4cb65082aa82eea232a97e9c16/less.js#L62

less expects this to be a filesystem path, but we provide it as a URL (ie, it contains `/`s).

**Comment by matthewp** [comment]
Fixed by steal-less 1.3.1
