### ISSUE TITLE
`Error: define is not a function` when using `deps-bundle`

### ISSUE THREAD

**Issue by eben-roux** [stealjs/steal-tools#1014]
I am using `steal-tools` v1.11.9 and when the application loads `Error: define is not a function` appears in the console.

To be sure I deleted the `node_modules` from the `steal-tools` global folder and re-installed and did the same for my application but to no avail.

**Comment by eben-roux** [comment]
There is a really long bit of red code logged to the console which I'm guessing is the entire bundle so I cannot paste that.

But it start like this:

![image](https://user-images.githubusercontent.com/5379436/41058337-d07f678a-69c9-11e8-9a42-8261f663c3b1.png)

And ends like so:

![image](https://user-images.githubusercontent.com/5379436/41058354-dd9993dc-69c9-11e8-90f7-5707c2bf99ab.png)

Let me know if there is something specific that I can provide.

**Comment by matthewp** [comment]
First I would run the bundle command with `--no-minify` so you can see better what is going on. Then I would click on the first link in the stack trace. It should take you to the code, copy and paste what you see there.

**Comment by eben-roux** [comment]
It appears as though the minifying may be contributing to the original issue.

By using the `--no-minify` I do not get the error.

**Comment by matthewp** [comment]
@eben-roux What version of steal-tools? 

@m-mujica Does this sound at all like the infamous dev bundles regexp issue?

**Comment by eben-roux** [comment]
`steal-tools`: 1.11.9

**Comment by m-mujica** [comment]
@matthewp yeah, seems like it, Eben is using the latest version tho and looking at the screenshots it seems the module preloading the npm stuff is indeed at the bottom of the bundle.

We only prepend the bundles config, I don't think there is anything there that might break the regex.

**Comment by eben-roux** [comment]
It appears as though the minification is ending the functions with a comma whereas the original code had a semi-colon.   Still investigating this...

Original:

![image](https://user-images.githubusercontent.com/5379436/41501469-1bb47258-71a5-11e8-9aa8-6b155cdec0b6.png)

Minified:

![image](https://user-images.githubusercontent.com/5379436/41501472-346788ee-71a5-11e8-99ec-adcf41a31f49.png)

**Comment by eben-roux** [comment]
OK, so the comma doesn't seem to affect anything.  However, when I compared the working minified code from Manuel's branch to the current one the ordering is definitely out of whack.
