### ISSUE TITLE
(node:74175) UnhandledPromiseRejectionWarning: Unhandled promise rejection

### ISSUE THREAD

**Issue by srikkanthsiki** [stealjs/steal-tools#1021]
(node:74175) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 46)
(node:74175) UnhandledPromiseRejectionWarning: file:/Project/Kosmos/trouper/trouper/node_modules/jquery/dist/jquery.min.js:2
!function(a,b){"object"==typeof module&&"object"==typeof module.exports?module.exports=a.document?b(a,!0):function(a){if(!a.document)throw new Error("jQuery requires a window with a document");return b(a)}:b(a)}("undefined"!=typeof window?window:this,function(a,b){var c=[],d=a.document,e=c.slice,f=c.concat,g=c.push,h=c.indexOf,i={},j=i.toString,k=i.hasOwnProperty,l={},m="2.2.4",n=function(a,b){return new n.fn.init(a,b)},o=/^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g,p=/^-ms-/,q=/-([\da-z])/gi,r=function(a,b){return b.toUpperCase()};n.fn=n.prototype={jquery:m,constructor:n,selector:"",length:0,toArray:function(){return e.call(this)},get:function(a){return null!=a?0>a?this[a+this.length]:this[a]:e.call(this)},pushStack:function(a){var b=n.merge(this.constructor(),a);return b.prevObject=this,b.context=this.context,b},each:function(a){return n.each(this,a)},map:function(a){return this.pushStack(n.map(this,function(b,c){return a.call(b,c,b)}))

TypeError: Cannot read property 'createElement' of undefined
    at ia (file:/Project/Kosmos/trouper/trouper/node_modules/jquery/dist/jquery.min.js:2:7340)
    at file:/Project/Kosmos/trouper/trouper/node_modules/jquery/dist/jquery.min.js:2:22092
    at file:/Project/Kosmos/trouper/trouper/node_modules/jquery/dist/jquery.min.js:2:22793
    at file:/Project/Kosmos/trouper/trouper/node_modules/jquery/dist/jquery.min.js:2:207
    at file:/Project/Kosmos/trouper/trouper/node_modules/jquery/dist/jquery.min.js:2:212

**Comment by srikkanthsiki** [comment]
jquery 2.2.4

**Comment by m-mujica** [comment]
@srikkanthsiki can you please provide more details about the error? if you can provide some code to replicate it'd very helpful, too.

**Comment by matthewp** [comment]
Going to close for now, @srikkanthsiki will reopen if you can provide more detail.
