### ISSUE TITLE
Duplicate warnings when bundling invalid HTML

### ISSUE THREAD

**Issue by mjstahl** [stealjs/steal-tools#1030]
Created a not-found component (for 404) and the template was:

```html
<h2>{{message}}</h3>
```

When building there was duplicate errors (below). The first one I think is the most important as it tells me the problem AND how to fix it.

```js
components/pages/not-found/not-found.stache:1: unexpected closing tag </h3> expected </h2>
components/pages/not-found/not-found.stache: expected closing tag </h2>
```

NOTE: I understand why this is occurring and there is a good possibility that it would take too much time to fix to be worth it.

**Comment by matthewp** [comment]
Sorry I missed this one. Going to move this to can-view-parser as its the thing that is producing these errors.

**Comment by matthewp** [comment]
https://github.com/canjs/can-view-parser/issues/94
