### ISSUE TITLE
deps bundle gets tree shaken

### ISSUE THREAD

**Issue by pYr0x** [stealjs/steal-tools#1044]
in development you didn't want hundert of files been loaded by steal. therefore development-bundles came.
but something like this:
```
async function buildDependenciesBundle() {
  return stealTools.bundle({
    main: project+"/web/main",
    config: path.join(__dirname, "package.json!npm")
  }, {
    dest: path.join(__dirname, "/assets/js"),
    filter: "node_modules/**/*",
    treeShaking: false
  });
}
```
didnt work.

in my `main.js` i have one line `import "can";` in development-bundles  tree shaking should be turned off by default and should not remove any "dead" code

**Comment by matthewp** [comment]
That makes sense... I wonder why the dev bundle tests are passing though...

**Comment by matthewp** [comment]
PR: https://github.com/stealjs/steal-tools/pull/1048
