### ISSUE TITLE
import "side-effect" gets tree-shaken if the module is not ES

### ISSUE THREAD

**Issue by pYr0x** [stealjs/steal-tools#1050]
here is a demo app.
https://github.com/pYr0x/css-treeshaken

using steal and steal-tools -> 2

the options `treeShaking: false` addes the css files as dependencies to the "main" module

**Comment by matthewp** [comment]
Looks like it's building out, just removed as a dependency. Looking into it.

**Comment by matthewp** [comment]
Breaking test: https://github.com/stealjs/steal-tools/commit/1c8c19253908660e6e809ce1cd40ecf02e68b6ff

The problem is not related to CSS, just doesn't work if the dependency is not an ES module.
