### ISSUE TITLE
Proposal: Move away from CLI use REPL

### ISSUE THREAD

**Issue by frank-dspeed** [stealjs/steal-tools#1079]
This can be backward Compatible via the CLI interface but we will add 
- https://nodejs.org/api/repl.html
if Node >= 10 so we can Support the overall movement to NodeOS and other Unikernel Projects

The Repl will be also shared via a local unix socket thats best practice on that and then we  do a extra repl client that connects to that socket.

This way we can Programmatic control and use steal-tools directly from the repl we are also able to do remote imports directly from the repl and so are able to bundle projects even without installing them local!

That will allow us to compile only what we need and also use the new module flows desired by Node.

please lets discusse any questions

**Comment by matthewp** [comment]
I don't think it's reason to assume people are going to start a repl to do a build. The CLI is useful for straightforward builds with no special configuration.

**Comment by frank-dspeed** [comment]
@justinbmeyer 
```js
import can from 'https://unpkg.com/can/core.mjs'
import jquery from 'https://unpkg.com/jquery@3.3.1/dist/jquery.slim.min.js'
```

The Main Concept of bypass Npm install is that import is not related to a path its related to a URL so we can also remote import and use that for local development we would have our regular caching proxys for domains like unpkg.

steal-tools would download both files and do its stuff as we would talk about npm packages but every javascript will export at the end as module till wasm takes over.



```js
//import('https://unpkg.com/can/core.mjs').then(pkg=>pkg.Component).then(Compoent=>new Component)
```

**Comment by frank-dspeed** [comment]
@justinbmeyer oh and sorry a more current example for bypass npm i forgotten to show that
```js
// writing to local file in a full example we would simply pipe into the steal-tools bundle stream :)
request('https://unpkg.com/can/core.mjs').pipe(fs.createWriteStream('core.mjs'))
```
