### ISSUE TITLE
Build exports wrong cjs format

### ISSUE THREAD

**Issue by cherifGsoul** [stealjs/steal-tools#1139]
Currently the export for `cjs` is the same as `amd` I noticed this in 2 `canjs` packages, `can-log` and `can-key-tree` .

The used `steal-tools` version `"steal-tools": "^2.2.1"`

<img width="1014" alt="can-log_js_—_can-log" src="https://user-images.githubusercontent.com/109013/59930651-2ec2a400-943b-11e9-9dcd-334a2e9802dc.png">

**Comment by m-mujica** [comment]
My current theory is that there is a shared data structure between each transform and previous code tranforms (AMD -> CJS for example) results are overwritten.

> I verified `transpile` is generating the right output


[can-log](https://github.com/canjs/can-log/blob/784e8d96aacde68bf9c6a5ef705b165328181208/build.js#L8-L12) current build script looks like this:

```js
stealTools.export({
  steal: {
    config: __dirname + "/package.json!npm"
  },
  outputs: {
    "+cjs": {},
    "+amd": {},
    "+global-js": {}
  }
});
```

When you run it, all built bundles are AMDs (which is the last transform in outputs) but it you change the order of the outputs like this:

```js
stealTools.export({
  steal: {
    config: __dirname + "/package.json!npm"
  },
  outputs: {
    "+amd": {},
    "+global-js": {},
    "+cjs": {},
  }
});
```

All bundles will be written out as CJS instead (the last transform in the outputs object).


I think the problem might be around here https://github.com/stealjs/steal-tools/blob/019df7f65970e2e515932909c55ca9926c1107eb/lib/build/transform.js#L100 ... 

Also, [here all transforms share the same graph / data / loader](https://github.com/stealjs/steal-tools/blob/019df7f65970e2e515932909c55ca9926c1107eb/lib/build/export.js#L243)... If I'm not wrong the `activeSource` object stores each transform and I think it is attached to the loader
