### ISSUE TITLE
Grunt task exits as successful when it is unable to find a file

### ISSUE THREAD

**Issue by matthewp** [stealjs/steal-tools#139]
There is a test and we know that the promise rejects in this situation: https://github.com/bitovi/steal-tools/blob/96a152929e985bc3be39d68ffdc952508a30ed8c/test/test.js#L582

So the problem must be the grunt task.

**Comment by justinbmeyer** [comment]
@matthewp Was this issue reported by someone?  

Seems like we need a test for our grunt task.

**Comment by matthewp** [comment]
I noticed it myself.  Yes, we should test these some how.

**Comment by matthewp** [comment]
This is fixed. Here's the test: https://github.com/stealjs/steal-tools/blob/ff9fd2f299343fd3f68c8184fd8df49c5b554fb1/test/grunt_tasks/steal_build.js#L28
