### ISSUE TITLE
bundle: false

### ISSUE THREAD

**Issue by justinbmeyer** [stealjs/steal-tools#14]
We should be able to tell a module that it should not be packaged in production.  We should explore how requirejs does this. If requirejs doesn't have an API for it, I suggest putting it on meta:

System.meta.html5Shiv = {bundle: false};

**Comment by justinbmeyer** [comment]
@matthewp It simply would not put it in a bundle.  Ignore has meant something closer to loading @empty previously.  jquery is something people might not want to bundle, but to load from a cdn.  Our dev utils are something someone would want to ignore.

**Comment by pYr0x** [comment]
closed 
http://stealjs.com/docs/steal-tools.build.html#section_ignore

**Comment by donkeybanana** [comment]
The page does not mention in what format to specify the modules to ignore, nor are there any examples.

Additionally, there is no mention of where to specify this within `package.json`, or even if it is possible.

**Comment by pYr0x** [comment]
there are no examples??
https://stealjs.com/docs/steal-tools.build.html#ignore

**Comment by donkeybanana** [comment]
https://stealjs.com/docs/steal-tools.build.html#ignore is not an example, its a description which does not describe how to format the list of modules.

> https://stealjs.com/docs/StealJS.loading-from-cdn.html

Thanks for this, it is exactly what the first link should provide as far as the `ignore` option goes. Or at least provide a link to this page to make it easier for first-time users.

**Comment by pYr0x** [comment]
> is not an example, its a description which does not describe how to format the list of modules.
i do not understand what is missing. please, if you think the docs should describe something better, make a PR at https://github.com/stealjs/stealjs/blob/gh-pages/docs/steal-tools.build.html

**Comment by donkeybanana** [comment]
@pYr0x what about defining ignores as part of `package.json`?

Is it possible? Any examples?

I know I can use `steal-tools` and have already done so, but I would like to keep all my configuration in one place if possible.

Thanks

**Comment by donkeybanana** [comment]
> i do not understand what is missing

Specifically, https://stealjs.com/docs/steal-tools.build.html#ignore only _describes_ `ignore`, without providing examples. The examples within that heading are for how to subsequently configure the environment, not for using `ignore` itself.

I will try to submit a PR.

For context I am coming at the latest `steal` with fresh eyes, so in a good position to identify things which are not so obvious to new users, while being inherently familiar to the devs/long-time users. I am already making an effort to raise the user-facing issues I find as I go (hence my comments here).

**Comment by pYr0x** [comment]
> For context I am coming at the latest steal with fresh eyes, so in a good position to identify things which are not so obvious to new users, while being inherently familiar to the devs/long-time users. I am already making an effort to raise the user-facing issues I find as I go (hence my comments here).

thats true, and I would be happy about a contribution

**Comment by donkeybanana** [comment]
Found some more specific info at https://stealjs.com/docs/steal-tools.BuildOptions.html

> An array of module names that should be ignored and not included in the bundled file. For more information take a look at the ignore usage http://stealjs.com/docs/steal-tools.build.html#ignore

**Comment by matthewp** [comment]
@donkeybanana You cannot put it into the package.json. The package.json is for configuring *steal.js* which is what loads your code in development (and production). That's different from the build configuration which is just about how to build the application.

I agree though, that it is hard to find this documentation, and that is important! I'm starting to reorganize stealjs.com' docs to be more about *topics* rather than APIs. The API pages will still exist, but the meat of the documentation will be elsewhere. So we should link from the API to the Loading from CDN page (which will be improved in the future). Thanks for your feedback!

**Comment by donkeybanana** [comment]
Thanks @matthewp

Coming from legacy `steal` - `packaged: false, ignore: true` - I had assumed the `steal` config _is_ the build config for all intents and purposes. Obviously `steal-tools` provides its own configuration API but I'd assumed that was sugar.
