### ISSUE TITLE
Streaming API

### ISSUE THREAD

**Issue by matthewp** [stealjs/steal-tools#142]
It would be nice if we had a lower-level API that operated on Streams.  This would be particularly useful for the Watch mode, where a Promise doesn't make sense.  I propose dividing the API into something like this:

```js
stealTools.createBuildStream(system, options) -> Stream<Bundle>
```

```js
stealTools.build(system, options) -> Promise
```

```js
stealTools.continuousBuild(system, options) -> Stream<Bundle>
```

`createBuildStream` would be the low-level API that just returns a Stream containing Bundles.  `build` would work the same way it does today, except it would call `createBuildStream` and when bundles are received, write those to the file-system.  `continuousBuild` would do the same, but would just never resolve.

Same structure for pluginify.

**Comment by whitecolor** [comment]
How is it going? Not ready yet?

**Comment by matthewp** [comment]
Internally it's all streams, this is what `stealTools.build` is: https://github.com/stealjs/steal-tools/blob/master/lib/build/multi.js#L14

I think for your use case is you don't want the bundles to be written, right?  In that case the *easy* thing would be to simply add an option writeBundles: false or something and return the `buildStream`.

**Comment by whitecolor** [comment]
Right, just to have only in memory result.

**Comment by matthewp** [comment]
Yes, this would be very simple with the way the code works now.  I would add these lines: https://github.com/stealjs/steal-tools/blob/master/lib/build/multi.js#L13-L16

to another file, multi_stream.js maybe, and have it return the buildStream. and this could be `stealTools. createBuildStream` as this issue proposes.

**Comment by whitecolor** [comment]
What about buding building fs output?

**Comment by matthewp** [comment]
> What about buding building fs output?

That won't be done in this API, you'll get a stream of bundles and will be responsible for writing them out yourself.  We can expose a `createBundlesWriteStream` or something that takes a bundles stream and writes it out.  So you could create a bundles stream, manipulate it as you wish, and then write out the results.

**Comment by whitecolor** [comment]
steam is ok.

**Comment by matthewp** [comment]
Going to document what we need:

* **createBundleGraphStream** - Given
