### ISSUE TITLE
Conditional Builds

### ISSUE THREAD

**Issue by justinbmeyer** [stealjs/steal-tools#188]
If https://github.com/systemjs/systemjs/issues/285 lands, it would be good to support building apps that do conditionals.

**Comment by matthewp** [comment]
We should just build this as an extension ourselves. There are a lot of cool features in SystemJS that get discussed but never implemented.

**Comment by matthewp** [comment]
He's the gitter discussion behind conditionals for reference: https://gitter.im/stealjs/steal?at=54fe5775846ca2ce6e20b77f

**Comment by matthewp** [comment]
This is now being worked on at https://github.com/stealjs/steal-conditional
