### ISSUE TITLE
bundle-steal command line option isn't working if Steal is already installed on the top level

### ISSUE THREAD

**Issue by daffl** [stealjs/steal-tools#193]
The `--bundle-steal` option looks for `steal.production.js` in the `steal-tools/node_modules/steal` folder. If you already installed Steal at the top level in the same version NPM will not create that folder.

**Comment by matthewp** [comment]
Thanks. I think the [reason is here](https://github.com/stealjs/steal-tools/blob/master/lib/node/make_steal_node.js#L8).  We might be able to use `require.resolve` here instead.

**Comment by matthewp** [comment]
Fixed in https://github.com/stealjs/steal-tools/tree/v0.7.4
