### ISSUE TITLE
Bundling language packs

### ISSUE THREAD

**Issue by whitecolor** [stealjs/steal-tools#199]
There was a smaill discussion about language packs on gitter. I wan't to open an issue here about it, to expose some ideas how this can be done with steal.

Is there a way to bundle such files in separate bundles like css bundling is done?

**Comment by whitecolor** [comment]
Any ideas how this can be implement?

**Comment by justinbmeyer** [comment]
#188

**Comment by whitecolor** [comment]
@justinbmeyer @matthewp 
Not to create a separate issue or something, ask here:

```
components/
 comp1/
   comp1.js
   lang/
    en.js // language file 
    es.js // language file 
 comp2/
   comp2.js
   lang/
    en.js // language file 
    es.js // language file 
```
Is it possible somehow to get 3 bundles with steal:

bundle.js // app JS bundle
bundle.en.js // bundle that contain comp1/lang/en.js & comp2/lang/en.js
bundle.es.js // bundle that contain comp1/lang/es.js & comp2/lang/es.js

Something like that.

**Comment by whitecolor** [comment]
@matthewp is it possible to exclude a particual file from being placed into build?

So that if I have some `module.js`:
```
require('module1`)
require('module2`)
```
builder will use this file while build (and thus include `module1` and `module2`) but will not include code of `module.js` itself?

**Comment by matthewp** [comment]
You can map it to empty during the build:

```js
"envs": {
  "build-development": {
    "module1": "@empty"
  },
  "build": {
    "module1": "@empty"
  }
}
```

I think you need both of those.

**Comment by justinbmeyer** [comment]
I've been thinking lately that modules probably aren't the best way. Especially if you want people to be able to change a dropdown and have them change. 

I'll share my ideas when I have time later today.

**Comment by whitecolor** [comment]
@justinbmeyer interesting to hear.

**Comment by whitecolor** [comment]
@justinbmeyer interesting to hear.

BTW I've build some quite simple plugin for StealJS that allows to imlement what I wanted

If you have a structure
```
components/
 comp1/
   comp1.js
   lp/
    en.js // language file, currnelty cjs modules, json is possible
    es.js
 comp2/
   comp2.js
   lp/
    en.js // language file 
    es.js // language file
```

Then from component code:
```javascript
import getLp from './lp!lp' // `lp` plugin is needed

getLp('en').then(function(dict){
  dict // here will be dict from '.lp/en.js
})
``

And while build it will build `app.en.lp` files (for every language) for each bundle and will load them on demand.

https://gist.github.com/whitecolor/e500e68ec37e052a2dc1

**Comment by whitecolor** [comment]
https://github.com/whitecolor/steal-lp
