### ISSUE TITLE
If transpiler is Babel use Babel to parse ES6 imports

### ISSUE THREAD

**Issue by matthewp** [stealjs/steal-tools#209]
Currently we always use Traceur to parse the `import` statements, but this will cause problems when the code contains features Traceur doesn't support.  We should separate the implementations based on which transpiler the user is using.

**Comment by matthewp** [comment]
Ask me if you want to work on this and i'll explain.

**Comment by Globegitter** [comment]
@matthewp just ran into this, so if you can give me any pointers I would be happy to fix (ideally with using the babelOptions defined in the current project).

**Comment by matthewp** [comment]
Probably if you have this change: https://github.com/stealjs/steal-tools/pull/279  you'll be fine. The problem is that our Traceur is a little outdated, just need to merge that PR and make a release.  I just can't do it this week.

**Comment by matthewp** [comment]
But as far as this bug, https://github.com/stealjs/steal-tools/blob/master/lib/load/get_es_module_imports.js#L48  we need a version of this module that works with babel.

**Comment by matthewp** [comment]
This is in 0.12.0-pre now.
