### ISSUE TITLE
Build fails in 0.8.2

### ISSUE THREAD

**Issue by whitecolor** [stealjs/steal-tools#221]
The same config works ok with 0.7.4

```javascript
    stealTools.build({
        main: 'app',
        bundlesPath: '../public/assets',
        config: __dirname + '/package.json!npm'
    }, {
        bundleSteal: true
    })
```
I'm not sure what error means, so will put config without changes

package.json:
```
"system": {
    "baseURL": "client",
    "map": {
      "models": "composer/models",
      "components": "composer",
      "lesscss": "../node_modules/less/dist/less",
      "common": "../common"
    },
...
```

Though it seems that it doesn't load system config at all.

Build output:

```
[00:13:08] Starting 'build'...
OPENING: app
[00:13:08] Finished 'build' after 7.96 ms
WARN: Could not find models in node_modules. Ignoring.
WARN: Could not find composer/models in node_modules. Ignoring.
WARN: Could not find components in node_modules. Ignoring.
WARN: Could not find composer in node_modules. Ignoring.
WARN: Could not find lesscss in node_modules. Ignoring.
WARN: Could not find common in node_modules. Ignoring.
WARN: Could not find dojo/dojo in node_modules. Ignoring.
WARN: Could not find yui/yui in node_modules. Ignoring.
WARN: Could not find mootools/mootools in node_modules. Ignoring.
WARN: Could not find zepto/zepto in node_modules. Ignoring.
WARN: Could not find steal-qunit/steal-qunit in node_modules. Ignoring.
WARN: Could not find steal-qunit in node_modules. Ignoring.
error { [Error: Error loading "bbooks-composer@0.0.4-6#../node_modules/less/dist/less" at file:d:/Dropbox/Code/node_modules/less/dist/less.js
Error loading "bbooks-composer@0.0.4-6#../node_modules/less/dist/less" from "app" at file:client/app.js
ENOENT, open '...\Code\node_modules\less\dist\less.js']
  errno: 34,
  code: 'ENOENT',
  path: 'd:\\Dropbox\\Code\\node_modules\\less\\dist\\less.js' } Error: Error loading "bbooks-composer@0.0.4-6#../node_modules/less/dist/less" at file:d:/Dropbox/Code/node_modules/less/dist/less.js
Error loading "bbooks-composer@0.0.4-6#../node_modules/less/dist/less" from "app" at file:client/app.js
ENOENT, open '...\Code\node_modules\less\dist\less.js'
ERROR: Error loading "bbooks-composer@0.0.4-6#../node_modules/less/dist/less" at file:d:/Dropbox/Code/node_modules/less/dist/less.js
Error loading "bbooks-composer@0.0.4-6#../node_modules/less/dist/less" from "app" at file:client/app.js
ENOENT, open '...\Code\node_modules\less\dist\less.js' Error: Error loading "bbooks-composer@0.0.4-6#../node_modules/less/dist/less" at file:.../Code/node_modules/less/dist/less.js
Error loading "bbooks-composer@0.0.4-6#../node_modules/less/dist/less" from "app" at file:client/app.js
ENOENT, open '...\Code\node_modules\less\dist\less.js'
Potentially unhandled rejection [6] Error: Error loading "bbooks-composer@0.0.4-6#../node_modules/less/dist/less" at file:.../Code/node_modules/less/dist/less.js
Error loading "bbooks-composer@0.0.4-6#../node_modules/less/dist/less" from "app" at file:client/app.js
ENOENT, open '...\Code\node_modules\less\dist\less.js'
```

**Comment by matthewp** [comment]
Maps shouldn't have relative paths in them. You should be using `paths` in those cases.  Also, does this mean your `node_modules` folder is not in the same directory as your `package.json`?  I didn't think that was even possible.

**Comment by whitecolor** [comment]
But why it works with 0.7.4?

nod_modules in the same folder as package.json

**Comment by matthewp** [comment]
If node_modules is in the same folder why is it `"../node_modules/less/dist/less"`?

**Comment by matthewp** [comment]
Oh because you are changing the base.

**Comment by matthewp** [comment]
You should be able to pull this off with this map:

```js
"lesscss": "less/dist/less"
```

The mapping you have for common should be a paths.  Make those changes and let me know.

**Comment by whitecolor** [comment]
after I added this map client dev app (wich loads `lesscss` module )works ok
but build fails to load $less

```
SOMETHING WENT WRONG [ReferenceError: Error loading "$less" at file:d:\Dropbox\Code\bbooks-composer2\node_modules\steal-tools\node_modules\steal/ext/less.js
Error evaluating file:d:\Dropbox\Code\bbooks-composer2\node_modules\steal-tools\node_modules\steal/ext/less.js
window is not defined]
ERROR: Error loading "composer/composer.less!$less" at <unknown>
Error loading "composer/composer.less!$less" from "app" at file:client/app.js
Error loading "$less" at file:d:\Dropbox\Code\bbooks-composer2\node_modules\steal-tools\node_modules\steal/ext/less.js
Error evaluating file:d:\Dropbox\Code\bbooks-composer2\node_modules\steal-tools\node_modules\steal/ext/less.js
window is not defined ReferenceError: Error loading "composer/composer.less!$less" at <unknown>
Error loading "composer/composer.less!$less" from "app" at file:client/app.js
Error loading "$less" at file:d:\Dropbox\Code\bbooks-composer2\node_modules\steal-tools\node_modules\steal/ext/less.js
Error evaluating file:d:\Dropbox\Code\bbooks-composer2\node_modules\steal-tools\node_modules\steal/ext/less.js
window is not defined
    at Object../add-default-options (evalmachine.<anonymous>:72:15)
    at s (evalmachine.<anonymous>:13:576)
```

**Comment by matthewp** [comment]
Since you're using your own less you'll want to add a `buildConfig` that maps to the node version of less, like shown here: http://stealjs.com/docs/System.buildConfig.html

**Comment by whitecolor** [comment]
@matthewp could you ellaborate what excaclty should I put there, I don't get. Isn't using `buildConfig` the same as  `stealTools.buiid` config?

**Comment by matthewp** [comment]
This will probably work:

```js
"system": {
  "buildConfig": {
    "map": {
      "less": "less/index"
    }
  }
}
```

**Comment by whitecolor** [comment]
This breaks loading of `lesscss`

```
error { [Error: Error loading "lesscss" at file:client/lesscss.js
Error loading "lesscss" from "app" at file:client/app.js
ENOENT, open 'd:\Dropbox\Code\bbooks-composer2\client\lesscss.js']
  errno: 34,
  code: 'ENOENT',
  path: 'd:\\Dropbox\\Code\\bbooks-composer2\\client\\lesscss.js' } Error: Error loading "lesscss" at file:client/lesscss.js
Error loading "lesscss" from "app" at file:client/app.js
ENOENT, open 'd:\Dropbox\Code\bbooks-composer2\client\lesscss.js'
ERROR: Error loading "lesscss" at file:client/lesscss.js
```


Actually I don't understand why mapping  `"lesscss": "less/dist/less"` breaks loading of `less` or `$less`

**Comment by whitecolor** [comment]
No this doesn't help the same result.

Actually I don't understand why mapping  `"lesscss": "less/dist/less"` breaks loading of `less` or `$less`...

**Comment by matthewp** [comment]
Having a `less` dependency is probably what is breaking it, because the less plugin requires `less`.

**Comment by matthewp** [comment]
Will try to create a test for this.

**Comment by whitecolor** [comment]
Well seems to solve. To use this mapping `"lesscss": "less/dist/less"` I had to remove `less` from `npmIgnore` - this broke build (it could not load `less`)

So finaly I mapped `lesscss` using `paths`:
```
"paths": {
      "lesscss": "../node_modules/less/dist/less.js"
    },
```

This works. Thought I'm seeing it as issue of conflicting beetween need use use client (browser) side less from npm package and steal build.

**Comment by matthewp** [comment]
I don't quite understand what you are doing,  your using less in the browser but not the less plugin, but do want to use the less plugin in the build? Is that right?

**Comment by whitecolor** [comment]
Just to make things clear:
1) less plugin is need in client app becase user can edit style of some kind of content (user level content).
2) I don't load less style on the client, I complile in on server, using realtime transpiler (less file is requested - compiled css send to client) so no need in $less plugin in browser. So for dev I remap $less to style hot reload plugin (on change styles are replaced on the client without page reload)
3) As I have only less sources for styles build uses starndard steal $less to build styles.

**Comment by matthewp** [comment]
It just sounds like you have a complicated setup which is why you are having to do some special configuration to pull it off.  Anyways, it should not be a problem to bring your own less, installed with npm, and have that be used by `$less` with some mappings.  If you want to set up an example project I can help you get it configured to work.  It would serve as a good example for people who want this advanced kind of behavior. Closing this as you seem to have worked out your configuration.
