### ISSUE TITLE
base-url tag attribute tries to loads stealconfig

### ISSUE THREAD

**Issue by whitecolor** [stealjs/steal-tools#222]
I want to set baseURL using tag attribute:
`<script src="../node_modules/steal/steal.js" data-base-url="base" data-main="app"></scirpt>`

If I do so it tries to load base\stealconfig.js (I dont' have any) and doesn't try to load package.json.
 
I tried to add data-config="../package.json!npm" in script tag, but it doesn't load system config. 

And with data-base-url it tries to load main="app" from / app.js not /base/app.js

**Comment by justinbmeyer** [comment]
You expect `<script src="../node_modules/steal/steal.js" data-base-url="base" data-main="app"></scirpt>` to load `base\package.json`?  

> I tried to add data-config="../package.json!npm" in script tag, but it doesn't load system config.

You should probably be setting config-main in this case, instead of data-config.  data-config sets configPath, which has a side-effect of setting baseURL and configMain.

**Comment by whitecolor** [comment]
@justinbmeyer with config-main it tries to load `base/package.json`

**Comment by matthewp** [comment]
Well regardless of any workarounds, adding a baseURL shouldn't trigger stealconfig to become the configMain, so I'll take a look at recreating it in a test.

**Comment by matthewp** [comment]
Shouldn't this be in stealjs/steal though? This is a browser bug.

**Comment by whitecolor** [comment]
Yes sorry) hah should I create the issu there?

**Comment by matthewp** [comment]
Yeah please do.
