### ISSUE TITLE
BundleSteal in a web worker fails with `window is not defined`

### ISSUE THREAD

**Issue by BigAB** [stealjs/steal-tools#231]
I want to be able to build/bundle a web worker file with Steal.

When I bundle the web worker with steal (`bundleSteal: true`) and I try and use the web worker it fails with the error:

```javascript
Uncaught ReferenceError: window is not defined
```

The offending code seems to be here:
https://github.com/stealjs/steal-tools/blob/master/lib/bundle/add_steal.js#L8

in the `[add-define]` part.

Simply changing it to `this.define` instead of `window.define` seems to work, but I am not sure of the consequences of such a change.

I could make a PR but I need some help figuring out how to write a test for this.

Here is a gist with some example code if you like:  
https://gist.github.com/BigAB/89c86d54c919d04a23d1

You'll need to `npm install`, `bower install` and `grunt` then serve `index.html` and `build.html` for the build version.

**Comment by matthewp** [comment]
I wouldn't use `this`.  I think there are issues with that.  I would do this ugly sort of thing:

```js
((typeof WorkerGlobalScope !== 'undefined' && self instanceof WorkerGlobalScope) ? self : window).define = System.amdDefine;
```

**Comment by shcarrico** [comment]
:+1: matthewp

**Comment by matthewp** [comment]
Doing a release for this.

**Comment by matthewp** [comment]
This is in 0.9.4, just published.
