### ISSUE TITLE
steal-build watch mode: after the first edit is stops watching the files

### ISSUE THREAD

**Issue by mehiel** [stealjs/steal-tools#242]
This is happening on Debian 8 and probably linux in general as it has to do with inotify watchers.

**Comment by mehiel** [comment]
A proposed workaround (thanks to @matthewp) is to comment out [watch.js:13](https://github.com/stealjs/steal-tools/blob/master/lib/stream/watch.js#L13)

**Comment by matthewp** [comment]
Thanks, I'll take a look and see if the unwatch is needed, it's probably not.

**Comment by matthewp** [comment]
I tested this out and the unwatch is not needed.  Going to remove it.

**Comment by matthewp** [comment]
Once I merge this i'll do a patch release for you.

**Comment by matthewp** [comment]
Ok, released a 0.10.1 with this and your fix. Thanks for figuring this out!

**Comment by mehiel** [comment]
@matthewp Much obliged for the patch release. 

I did a fast pass myself and it seems that you do that because if I change the dependencies of a module then you probably have to watch some new  files (in case of a new dependency added) but you may also have to stop watching files that are not dependencies anymore (in case of a removed dependency). So unwatching some addresses makes sense in that case. But this unwatch/watch everything is kinda brute force eitherway. It's easy to compare old/new addresses there I suppose.

What do you thing?

**Comment by matthewp** [comment]
Ah, yes, I think maybe that was my original intent. It's a bit of a corner-case but you are right.  Could use something like lodash _.difference to compare the old/new like you said, and just unwatch the old.

**Comment by mehiel** [comment]
Sure.

**Comment by mehiel** [comment]
@matthewp FYI I did the change in [this commit](http://goo.gl/9T1BRV) but I'm not sending a PR yet because the problem of not adding a watch on a file that was previously unwatched persists.

So if for example I edit a module and remove a dependency then only the files related to that dependency are unwatched. Which is corrent. But if I add it again that `watch.add()` doesn't work (and doesn't fail either). So let me try to find out what's happening and I'll come back.

**Comment by matthewp** [comment]
Thanks for looking into this. chokidar has more events, maybe there is an error event we need to listen to.

**Comment by mehiel** [comment]
I've reported that to [pollmillr/chokidar#289](https://github.com/paulmillr/chokidar/issues/289) with a patch adding failing test.

**Comment by mehiel** [comment]
@matthewp I had some progress with that. Sent a [PR to chokidar](https://github.com/paulmillr/chokidar/pull/291) with a _probable_ fix. We have some conflicts with the tests but we'll figure it out. 

At least it now works as expected in watch mode.

**Comment by matthewp** [comment]
Awesome! Thanks for following up on this. Once that bug is fixed please do send that newAddresses PR to us. Think that's the correct way to go.

**Comment by mehiel** [comment]
kk
