### ISSUE TITLE
Make live-reload work over ssl

### ISSUE THREAD

**Issue by matthewp** [stealjs/steal-tools#244]
Might need a `--live-reload-ssl` option

**Comment by matthewp** [comment]
Related: https://github.com/stealjs/live-reload/issues/3

**Comment by matthewp** [comment]
Would need to change here: https://github.com/stealjs/steal-tools/blob/master/lib/create_websocket_server.js#L6

Probably need to pass in the cert.

**Comment by mjstahl** [comment]
I propose we add to command line options `--ssl-key` and `--ssl-cert`.

If those two options exist, we can `require("https")`, `server` will be an HTTPS server with appropriate key and cert options passed in.

`server` can then still be passed to the `WebSocketServer` object.

**Comment by matthewp** [comment]
👍 Yep, that's the way to go, look for either key+cert or sfx, if so make it https.

**Comment by matthewp** [comment]
@mjstahl I believe you had a PR for this a while back, right?

**Comment by mjstahl** [comment]
@matthewp Yep, I believe it was already merged -- https://github.com/stealjs/steal-tools/pull/501

And was originally https://github.com/stealjs/steal-tools/pull/494

**Comment by matthewp** [comment]
Great!
