### ISSUE TITLE
add build options to buildResult

### ISSUE THREAD

**Issue by whitecolor** [stealjs/steal-tools#262]
It would be usefull to have options object (using what build was made) available in build result http://stealjs.com/docs/steal-tools.BuildResult.html

**Comment by matthewp** [comment]
Thanks, I agree that this is useful.  It's actually available on `buildResult.configuration.options`.  Although `configuration` is not currently documented; it should be, this is not going to be removed.

**Comment by matthewp** [comment]
This is fixed in `major`.
