### ISSUE TITLE
Grunt task should always fail when there's an error

### ISSUE THREAD

**Issue by daffl** [stealjs/steal-tools#263]
Currently the [build Grunt task](https://github.com/stealjs/steal-tools/blob/master/tasks/build.js) does not error when the build fails.

**Comment by matthewp** [comment]
Yes, this is hopefully easily fixed. Should be able to add an error function to the promise and feed that into Grunt's done (i assume you do `done(err)`).

**Comment by matthewp** [comment]
You can add a test to [this file](https://github.com/stealjs/steal-tools/blob/master/test/test_grunt.js). It uses a simple Grunt mock, I think you'd have to add [error handling here](https://github.com/stealjs/steal-tools/blob/master/test/test_grunt.js#L26) to make the test work. Ping me if you need some help.
