### ISSUE TITLE
StealJS: extract the libries while build to separate bundle

### ISSUE THREAD

**Issue by whitecolor** [stealjs/steal-tools#265]
As I didn't get the anwser on stack oveflow posting the question here.

I want to separate libraries that do not change often (like can, jquery) from app code while build.
Is it possible to configure steal build to extract such modules into separate bundle?

its about production build, currently steal-tools geneartes for me a huge main bundle, though most modules are loaded progressively. main bundle (that contains main libs like can/jquery). I use cache busting with hash fingerprints on files. So I thougth it would be more effective in terms of caching to have separate bundles for can/jquery like libs ("static" code) and main module app code.

**Comment by matthewp** [comment]
In 0.11.p-pre.0 there is a new side bundle feature that sounds like what you want. In meta config set a module as `sideBundle: true`

**Comment by matthewp** [comment]
@whitecolor does this fit your needs?

**Comment by whitecolor** [comment]
I will try and report.

**Comment by whitecolor** [comment]
I just added this option. But nothing happend. What should? How it should define what to split out to side bundle?

**Comment by matthewp** [comment]
This should go in your config (or the system object in steal-tools)

```js
"meta": {
  "other/module": {
    "sideBundle": true
  }
}
```

Let me know if this is what you did and it didn't work. Should have created a bundle just for `other/module`.

**Comment by whitecolor** [comment]
It works fine.
