### ISSUE TITLE
Live reload does not work for app.js in standard DoneJS setup

### ISSUE THREAD

**Issue by daffl** [stealjs/steal-tools#275]
I'm adding `live-reload` to the DoneJS generator. It looks like it works in most cases but not when updating an `app.js` like:

```js
import AppMap from "can-ssr/app-map";

const AppState = AppMap.extend({
  message: 'Hello Worlds hows is you?',
  title: 'place-my-order?'
});

export default AppState;
```

That's loaded into the template like

```html
<html>
  <head>
    <title>{{title}}</title>
    {{asset "css"}}
  </head>
  <body>
    <can-import from="src/styles.less!" />
    <can-import from="src/app" [.]="{value}" />
    <can-import from="src/home.component!" />

    <h1>{{message}} :)</h1>
    <pmo-home></pmo-home>

    {{asset "inline-cache"}}

    {{#isProduction}}
      <script src="/node_modules/steal/steal.production.js"
        main="pmo/index.stache!done-autorender"></script>
    {{else}}
      <script src="/node_modules/steal/steal.js"></script>
    {{/isProduction}}
  </body>
</html>
```

When changing `message` in `app.js` live reload reports `src/app` reloading but does not re-evaluate `index.stache`.

**Comment by matthewp** [comment]
Are you sure that you added "live-reload" to the configDependencies? I tried this earlier today and it worked.

**Comment by whitecolor** [comment]
@matthewp hereis a great talks about hot module reloading, if you haven't seen you should.
http://www.youtube.com/watch?v=j-kj2qwJa_E
https://www.youtube.com/watch?v=xsSnOQynTHs

**Comment by matthewp** [comment]
Thanks!  I've used Figwheel a bit and like it. I like how you get an indicator when a reload happens, we might need something like that, it gives confidence that you're looking at the latest code.

**Comment by matthewp** [comment]
@daffl please reopen in donejs if this is ever still a problem, several bug fixes related to live-reload in a donejs setup have happened.
