### ISSUE TITLE
Error when install steal-tools on Windows

### ISSUE THREAD

**Issue by duongphuhiep** [stealjs/steal-tools#287]
It's quite scary when we do a `npm install steal-tools` on Windows

- `fsevents` is not something for Windows
- `bufferutil`, `utf-8-validate`... don't work with the latest python on my PC
- other modules require the old nodejs 0.8.x

I don't know what is the impact in the future.  For now it is installed and works with the two sample projects: [quick-start](https://github.com/stealjs/quick-start) and [progressive-loading](https://github.com/stealjs/progressive-loading)

```
$ npm install steal-tools
npm WARN package.json stealjs-progressive-loading@1.0.0 No repository field.
npm WARN optional dep failed, continuing fsevents@0.3.8
\


> bufferutil@1.1.0 install d:\dev-js\progressive-loading\node_modules\steal-tools\node_modules\ws\node_modules\bufferutil
> node-gyp rebuild


d:\dev-js\progressive-loading\node_modules\steal-tools\node_modules\ws\node_modules\bufferutil>if not defined npm_config_node_gyp (node "c:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
 yp ERR! /configure error
gyp ERR! stack Error: Python executable "python" is v3.4.3, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (c:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:119:14)
gyp ERR! stack     at c:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:108:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:742:7)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at maybeClose (child_process.js:1015:16)
gyp ERR! stack     at Socket.<anonymous> (child_process.js:1183:11)
gyp ERR! stack     at Socket.emit (events.js:107:17)
gyp ERR! stack     at Pipe.close (net.js:485:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "c:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd d:\dev-js\progressive-loading\node_modules\steal-tools\node_modules\ws\node_modules\bufferutil
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
-


> utf-8-validate@1.1.0 install d:\dev-js\progressive-loading\node_modules\steal-tools\node_modules\ws\node_modules\utf-8-validate
> node-gyp rebuild


d:\dev-js\progressive-loading\node_modules\steal-tools\node_modules\ws\node_modules\utf-8-validate>if not defined npm_config_node_gyp (node "c:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Python executable "python" is v3.4.3, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (c:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:119:14)
gyp ERR! stack     at c:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:108:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:742:7)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at maybeClose (child_process.js:1015:16)
gyp ERR! stack     at Socket.<anonymous> (child_process.js:1183:11)
gyp ERR! stack     at Socket.emit (events.js:107:17)
gyp ERR! stack     at Pipe.close (net.js:485:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "c:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd d:\dev-js\progressive-loading\node_modules\steal-tools\node_modules\ws\node_modules\utf-8-validate
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm WARN optional dep failed, continuing bufferutil@1.1.0
npm WARN optional dep failed, continuing utf-8-validate@1.1.0
npm WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"0.12.7","npm":"2.11.3"})
npm WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"0.12.7","npm":"2.11.3"})
npm WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"0.12.7","npm":"2.11.3"})
npm WARN engine boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"0.12.7","npm":"2.11.3"})
npm WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"0.12.7","npm":"2.11.3"})
steal-tools@0.10.7 node_modules\steal-tools
├── pdenodeify@0.1.0
├── find-line-column@0.5.2
├── urix@0.1.0
├── colors@0.6.2
├── system-parse-amd@0.0.2
├── yargs@1.3.3
├── source-map@0.4.2 (amdefine@1.0.0)
├── through2@0.6.5 (xtend@4.0.0, readable-stream@1.0.33)
├── glob@4.5.3 (inherits@2.0.1, once@1.3.2, inflight@1.0.4, minimatch@2.0.10)
├── fs-extra@0.16.5 (jsonfile@2.2.1, graceful-fs@3.0.8, rimraf@2.4.2)
├── ws@0.7.2 (options@0.0.6, ultron@1.0.2)
├── clean-css@3.1.8 (commander@2.6.0, source-map@0.1.43)
├── lodash@2.4.1
├── chokidar@1.0.5 (arrify@1.0.0, path-is-absolute@1.0.0, is-glob@1.1.3, glob-parent@1.2.0, async-each@0.1.6, is-binary-path@1.0.1, readdirp@1.4.0, anymatch@1.3.0)
├── uglify-js@2.4.24 (uglify-to-browserify@1.0.2, async@0.2.10, source-map@0.1.34, yargs@3.5.4)
├── moment@2.10.6
├── winston@0.7.3 (cycle@1.0.3, stack-trace@0.0.9, eyes@0.1.8, async@0.2.10, pkginfo@0.3.0, request@2.16.6)
├── traceur@0.0.87 (commander@2.6.0, semver@2.3.2, rsvp@3.0.21, glob@4.3.5, source-map-support@0.2.10)
├── transpile@0.7.2 (comparify@0.1.0, js-string-escape@1.0.0, estraverse@1.5.0, js-module-formats@0.1.2, sourcemap-to-ast@0.0.2, escodegen@1.3.2, esprima@1.1.1, babel-core@4.1.1)
└── less@2.5.1 (graceful-fs@3.0.8, mime@1.3.4, image-size@0.3.5, promise@6.1.0, errno@0.1.3, mkdirp@0.5.1, request@2.60.0)
```

**Comment by matthewp** [comment]
Thanks, these are errors for installing `ws` which is used for live-reload. This will require Python 2.7.x.  I can move this into an optionalDependency so the rest of steal-tools will still work if you don't have the right version of Python.

**Comment by W3Max** [comment]
I have python 2.7 installed and here are the errors I get when I try to install steal-tools on windows:

    C:\Users\Maxime>npm install -g steal-tools
    npm WARN engine steal-tools@0.11.2: wanted: {"node":"0.10.x - 0.12.x || ^3.0.0"} (current: {"node":"4.1.0","npm":"3.3.4"})
    npm WARN engine steal-tools@0.11.2: wanted: {"node":"0.10.x - 0.12.x || ^3.0.0"} (current: {"node":"4.1.0","npm":"3.3.4"})
    npm WARN install Couldn't install optional dependency: Unsupported
    npm WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"4.1.0","npm":"3.3.4"})
    npm WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"4.1.0","npm":"3.3.4"})
    npm WARN engine boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"4.1.0","npm":"3.3.4"})
    npm WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"4.1.0","npm":"3.3.4"})
    npm WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"4.1.0","npm":"3.3.4"})
    C:\Users\Maxime\AppData\Roaming\npm\steal-tools -> C:\Users\Maxime\AppData\Roaming\npm\node_modules\steal-tools\bin\steal
    
    > bufferutil@1.1.0 install C:\Users\Maxime\AppData\Roaming\npm\node_modules\steal-tools\node_modules\bufferutil
    > node-gyp rebuild
    
    
    C:\Users\Maxime\AppData\Roaming\npm\node_modules\steal-tools\node_modules\bufferutil>if not defined npm_config_node_gyp (node "C:\Users\Maxime\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-    bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
    Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
      bufferutil.cc
    C:\Users\Maxime\AppData\Roaming\npm\node_modules\steal-tools\node_modules\nan\nan.h(263): error C2995: 'v8::Local<T> _NanEnsureLocal(v8::Local<T>)': function template has already been defined [    C:\Users\Maxime\AppData\Roaming\npm\node_mo
    dules\steal-tools\node_modules\bufferutil\build\bufferutil.vcxproj]
      C:\Users\Maxime\AppData\Roaming\npm\node_modules\steal-tools\node_modules\nan\nan.h(256): note: see declaration of '_NanEnsureLocal'
    C:\Users\Maxime\AppData\Roaming\npm\node_modules\steal-tools\node_modules\nan\nan.h(661): error C3083: 'smalloc': the symbol to the left of a '::' must be a type [    C:\Users\Maxime\AppData\Roaming\npm\node_modules\steal-tools\node_modules
    \bufferutil\build\bufferutil.vcxproj]
    C:\Users\Maxime\AppData\Roaming\npm\node_modules\steal-tools\node_modules\nan\nan.h(661): error C2039: 'FreeCallback': is not a member of 'node' [    C:\Users\Maxime\AppData\Roaming\npm\node_modules\steal-tools\node_modules\bufferutil\build
    \bufferutil.vcxproj]
      C:\Users\Maxime\.node-gyp\4.1.0\include\node\node_object_wrap.h(8): note: see declaration of 'node'
    C:\Users\Maxime\AppData\Roaming\npm\node_modules\steal-tools\node_modules\nan\nan.h(661): error C2061: syntax error: identifier 'FreeCallback' [C:\Users\Maxime\AppData\Roaming\npm\node_modules\steal    -tools\node_modules\bufferutil\build\b
    ufferutil.vcxproj]
    C:\Users\Maxime\AppData\Roaming\npm\node_modules\steal-tools\node_modules\nan\nan.h(665): error C2065: 'callback': undeclared identifier [C:\Users\Maxime\AppData\Roaming\npm\node_modules\steal-    tools\node_modules\bufferutil\build\bufferu
    til.vcxproj]
    C:\Users\Maxime\AppData\Roaming\npm\node_modules\steal-tools\node_modules\nan\nan.h(665): error C2065: 'hint': undeclared identifier [C:\Users\Maxime\AppData\Roaming\npm\node_modules\steal-    tools\node_modules\bufferutil\build\bufferutil.
    vcxproj]
    C:\Users\Maxime\AppData\Roaming\npm\node_modules\steal-tools\node_modules\nan\nan.h(672): error C2665: 'node::Buffer::New': none of the 4 overloads could convert all the argument types [    C:\Users\Maxime\AppData\Roaming\npm\node_modules\s
    teal-tools\node_modules\bufferutil\build\bufferutil.vcxproj]
      C:\Users\Maxime\.node-gyp\4.1.0\include\node\node_buffer.h(43): note: could be 'v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate *,char *,size_t)'
      C:\Users\Maxime\.node-gyp\4.1.0\include\node\node_buffer.h(31): note: or       'v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate *,v8::Local<v8::String>,node::encoding)'
      C:\Users\Maxime\AppData\Roaming\npm\node_modules\steal-tools\node_modules\nan\nan.h(672): note: while trying to match the argument list '(v8::Isolate *, const char *, uint32_t)'
    C:\Users\Maxime\AppData\Roaming\npm\node_modules\steal-tools\node_modules\nan\nan.h(676): error C2440: 'return': cannot convert from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object>' [    C:\Users\Maxime\AppData\Roaming\npm\node_modul
    es\steal-tools\node_modules\bufferutil\build\bufferutil.vcxproj]
      C:\Users\Maxime\AppData\Roaming\npm\node_modules\steal-tools\node_modules\nan\nan.h(676): note: No constructor could take the source type, or constructor overload resolution was ambiguous
    C:\Users\Maxime\AppData\Roaming\npm\node_modules\steal-tools\node_modules\nan\nan.h(683): error C2039: 'Use': is not a member of 'node::Buffer' [    C:\Users\Maxime\AppData\Roaming\npm\node_modules\steal-tools\node_modules\bufferutil\build\
    bufferutil.vcxproj]
      C:\Users\Maxime\.node-gyp\4.1.0\include\node\node_buffer.h(8): note: see declaration of 'node::Buffer'
    C:\Users\Maxime\AppData\Roaming\npm\node_modules\steal-tools\node_modules\nan\nan.h(683): error C3861: 'Use': identifier not found [C:\Users\Maxime\AppData\Roaming\npm\node_modules\steal-    tools\node_modules\bufferutil\build\bufferutil.vc
    xproj]
    gyp ERR! build error
    gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
    gyp ERR! stack     at ChildProcess.onExit (C:\Users\Maxime\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
    gyp ERR! stack     at emitTwo (events.js:87:13)
    gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
    gyp ERR! System Windows_NT 10.0.10240
    gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Maxime\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
    gyp ERR! cwd C:\Users\Maxime\AppData\Roaming\npm\node_modules\steal-tools\node_modules\bufferutil
    gyp ERR! node -v v4.1.0
    gyp ERR! node-gyp -v v3.0.3
    gyp ERR! not ok
    npm ERR! Windows_NT 10.0.10240
    npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Maxime\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "steal-tools"
    npm ERR! node v4.1.0
    npm ERR! npm  v3.3.4
    npm ERR! code ELIFECYCLE
    
    npm ERR! bufferutil@1.1.0 install: `node-gyp rebuild`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the bufferutil@1.1.0 install script 'node-gyp rebuild'.
    npm ERR! This is most likely a problem with the bufferutil package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node-gyp rebuild
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls bufferutil
    npm ERR! There is likely additional logging output above.
    
    npm ERR! Please include the following file with any support request:
    npm ERR!     C:\Users\Maxime\npm-debug.log

Also, I couldn't build (grunt build) the quick start demo (https://github.com/stealjs/quick-start):

    C:\Users\Maxime\Desktop\quick-start>grunt build
    Loading "build.js" tasks...ERROR
    >> SyntaxError: for-in loop variable declaration may not have an initializer.
    Loading "export.js" tasks...ERROR
    >> SyntaxError: for-in loop variable declaration may not have an initializer.
    Warning: Task "steal-build" not found. Use --force to continue.


I would really appreciate some help getting started with stealjs on windows, the product seams really cool!

**Comment by matthewp** [comment]
@W3Max I pushed to stealjs/quick-start upgrading to the latest version of Steal. Try with that and let me know.

**Comment by W3Max** [comment]
@matthewp thanks for your help but now I have the same problem as when I try to install steal-tools:

    npm WARN install Couldn't install optional dependency: Unsupported
    
    > bufferutil@1.1.0 install C:\Users\Maxime\Desktop\quick-start\node_modules\bufferutil
    > node-gyp rebuild
    
    
    C:\Users\Maxime\Desktop\quick-start\node_modules\bufferutil>if not defined npm_config_node_gyp (node "C:\Users\Maxime\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-    gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
    Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
      bufferutil.cc
    C:\Users\Maxime\Desktop\quick-start\node_modules\nan\nan.h(263): error C2995: 'v8::Local<T> _NanEnsureLocal(v8::Local<T>)': function template has already been defined [C:\Users\Maxime\Desktop\quick-    start\node_modules\bufferutil\build\bu
    fferutil.vcxproj]
      C:\Users\Maxime\Desktop\quick-start\node_modules\nan\nan.h(256): note: see declaration of '_NanEnsureLocal'
    C:\Users\Maxime\Desktop\quick-start\node_modules\nan\nan.h(661): error C3083: 'smalloc': the symbol to the left of a '::' must be a type [C:\Users\Maxime\Desktop\quick-    start\node_modules\bufferutil\build\bufferutil.vcxproj]
    C:\Users\Maxime\Desktop\quick-start\node_modules\nan\nan.h(661): error C2039: 'FreeCallback': is not a member of 'node' [C:\Users\Maxime\Desktop\quick-start\node_modules\bufferutil\build\bufferutil.    vcxproj]
      C:\Users\Maxime\.node-gyp\4.1.0\include\node\node_object_wrap.h(8): note: see declaration of 'node'
    C:\Users\Maxime\Desktop\quick-start\node_modules\nan\nan.h(661): error C2061: syntax error: identifier 'FreeCallback' [C:\Users\Maxime\Desktop\quick-start\node_modules\bufferutil\build\bufferutil.    vcxproj]
    C:\Users\Maxime\Desktop\quick-start\node_modules\nan\nan.h(665): error C2065: 'callback': undeclared identifier [C:\Users\Maxime\Desktop\quick-start\node_modules\bufferutil\build\bufferutil.vcxproj]
    C:\Users\Maxime\Desktop\quick-start\node_modules\nan\nan.h(665): error C2065: 'hint': undeclared identifier [C:\Users\Maxime\Desktop\quick-start\node_modules\bufferutil\build\bufferutil.vcxproj]
    C:\Users\Maxime\Desktop\quick-start\node_modules\nan\nan.h(672): error C2665: 'node::Buffer::New': none of the 4 overloads could convert all the argument types [C:\Users\Maxime\Desktop\quick-    start\node_modules\bufferutil\build\bufferuti
    l.vcxproj]
      C:\Users\Maxime\.node-gyp\4.1.0\include\node\node_buffer.h(43): note: could be 'v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate *,char *,size_t)'
      C:\Users\Maxime\.node-gyp\4.1.0\include\node\node_buffer.h(31): note: or       'v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate *,v8::Local<v8::String>,node::encoding)'
      C:\Users\Maxime\Desktop\quick-start\node_modules\nan\nan.h(672): note: while trying to match the argument list '(v8::Isolate *, const char *, uint32_t)'
    C:\Users\Maxime\Desktop\quick-start\node_modules\nan\nan.h(676): error C2440: 'return': cannot convert from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object>' [C:\Users\Maxime\Desktop\quick-    start\node_modules\bufferutil\build\buffe
    rutil.vcxproj]
      C:\Users\Maxime\Desktop\quick-start\node_modules\nan\nan.h(676): note: No constructor could take the source type, or constructor overload resolution was ambiguous
    C:\Users\Maxime\Desktop\quick-start\node_modules\nan\nan.h(683): error C2039: 'Use': is not a member of 'node::Buffer' [C:\Users\Maxime\Desktop\quick-start\node_modules\bufferutil\build\bufferutil.    vcxproj]
      C:\Users\Maxime\.node-gyp\4.1.0\include\node\node_buffer.h(8): note: see declaration of 'node::Buffer'
    C:\Users\Maxime\Desktop\quick-start\node_modules\nan\nan.h(683): error C3861: 'Use': identifier not found [C:\Users\Maxime\Desktop\quick-start\node_modules\bufferutil\build\bufferutil.vcxproj]
    gyp ERR! build error
    gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
    gyp ERR! stack     at ChildProcess.onExit (C:\Users\Maxime\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
    gyp ERR! stack     at emitTwo (events.js:87:13)
    gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
    gyp ERR! System Windows_NT 10.0.10240
    gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Maxime\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
    gyp ERR! cwd C:\Users\Maxime\Desktop\quick-start\node_modules\bufferutil
    gyp ERR! node -v v4.1.0
    gyp ERR! node-gyp -v v3.0.3
    gyp ERR! not ok
    npm WARN install:bufferutil bufferutil@1.1.0 install: `node-gyp rebuild`
    npm WARN install:bufferutil Exit status 1
    
    > utf-8-validate@1.1.0 install C:\Users\Maxime\Desktop\quick-start\node_modules\utf-8-validate
    > node-gyp rebuild
    
    
    C:\Users\Maxime\Desktop\quick-start\node_modules\utf-8-validate>if not defined npm_config_node_gyp (node "C:\Users\Maxime\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-    bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
    Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
      validation.cc
    C:\Users\Maxime\Desktop\quick-start\node_modules\nan\nan.h(263): error C2995: 'v8::Local<T> _NanEnsureLocal(v8::Local<T>)': function template has already been defined [C:\Users\Maxime\Desktop\quick-    start\node_modules\utf-8-validate\buil
    d\validation.vcxproj]
      C:\Users\Maxime\Desktop\quick-start\node_modules\nan\nan.h(256): note: see declaration of '_NanEnsureLocal'
    C:\Users\Maxime\Desktop\quick-start\node_modules\nan\nan.h(661): error C3083: 'smalloc': the symbol to the left of a '::' must be a type [C:\Users\Maxime\Desktop\quick-start\node_modules\utf-8-    validate\build\validation.vcxproj]
    C:\Users\Maxime\Desktop\quick-start\node_modules\nan\nan.h(661): error C2039: 'FreeCallback': is not a member of 'node' [C:\Users\Maxime\Desktop\quick-start\node_modules\utf-8-    validate\build\validation.vcxproj]
      C:\Users\Maxime\.node-gyp\4.1.0\include\node\node_object_wrap.h(8): note: see declaration of 'node'
    C:\Users\Maxime\Desktop\quick-start\node_modules\nan\nan.h(661): error C2061: syntax error: identifier 'FreeCallback' [C:\Users\Maxime\Desktop\quick-start\node_modules\utf-8-    validate\build\validation.vcxproj]
    C:\Users\Maxime\Desktop\quick-start\node_modules\nan\nan.h(665): error C2065: 'callback': undeclared identifier [C:\Users\Maxime\Desktop\quick-start\node_modules\utf-8-validate\build\validation.    vcxproj]
    C:\Users\Maxime\Desktop\quick-start\node_modules\nan\nan.h(665): error C2065: 'hint': undeclared identifier [C:\Users\Maxime\Desktop\quick-start\node_modules\utf-8-validate\build\validation.vcxproj]
    C:\Users\Maxime\Desktop\quick-start\node_modules\nan\nan.h(672): error C2665: 'node::Buffer::New': none of the 4 overloads could convert all the argument types [C:\Users\Maxime\Desktop\quick-    start\node_modules\utf-8-validate\build\valid
    ation.vcxproj]
      C:\Users\Maxime\.node-gyp\4.1.0\include\node\node_buffer.h(43): note: could be 'v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate *,char *,size_t)'
      C:\Users\Maxime\.node-gyp\4.1.0\include\node\node_buffer.h(31): note: or       'v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate *,v8::Local<v8::String>,node::encoding)'
      C:\Users\Maxime\Desktop\quick-start\node_modules\nan\nan.h(672): note: while trying to match the argument list '(v8::Isolate *, const char *, uint32_t)'
    C:\Users\Maxime\Desktop\quick-start\node_modules\nan\nan.h(676): error C2440: 'return': cannot convert from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object>' [C:\Users\Maxime\Desktop\quick-    start\node_modules\utf-8-validate\build\v
    alidation.vcxproj]
      C:\Users\Maxime\Desktop\quick-start\node_modules\nan\nan.h(676): note: No constructor could take the source type, or constructor overload resolution was ambiguous
    C:\Users\Maxime\Desktop\quick-start\node_modules\nan\nan.h(683): error C2039: 'Use': is not a member of 'node::Buffer' [C:\Users\Maxime\Desktop\quick-start\node_modules\utf-8-    validate\build\validation.vcxproj]
      C:\Users\Maxime\.node-gyp\4.1.0\include\node\node_buffer.h(8): note: see declaration of 'node::Buffer'
    C:\Users\Maxime\Desktop\quick-start\node_modules\nan\nan.h(683): error C3861: 'Use': identifier not found [C:\Users\Maxime\Desktop\quick-start\node_modules\utf-8-validate\build\validation.vcxproj]
    gyp ERR! build error
    gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
    gyp ERR! stack     at ChildProcess.onExit (C:\Users\Maxime\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
    gyp ERR! stack     at emitTwo (events.js:87:13)
    gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
    gyp ERR! System Windows_NT 10.0.10240
    gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Maxime\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
    gyp ERR! cwd C:\Users\Maxime\Desktop\quick-start\node_modules\utf-8-validate
    gyp ERR! node -v v4.1.0
    gyp ERR! node-gyp -v v3.0.3
    gyp ERR! not ok
    npm WARN install:utf-8-validate utf-8-validate@1.1.0 install: `node-gyp rebuild`
    npm WARN install:utf-8-validate Exit status 1
    npm WARN prefer global babel@5.8.23 should be installed with -g
    npm WARN EPACKAGEJSON stealjs@1.0.0 No repository field.
    npm WARN EPACKAGEJSON stealjs@1.0.0 No license field.

**Comment by matthewp** [comment]
Install errors doesn't mean it's not working.  So running the build fails?

**Comment by W3Max** [comment]
My bad... all those errors and still it works.
