### ISSUE TITLE
Plugin dependencies of the main are not part of the main bundle

### ISSUE THREAD

**Issue by matthewp** [stealjs/steal-tools#298]
I've noticed that often plugins like `done-css` and `done-component` will be put into a bundle other than the main, even though they are dependencies of the main. This will cause too many bundles to be loaded.

I think the algorithm should favor putting plugins (this is just the empty `System.set("done-css", {})`) in the main bundle to prevent unnecessary extra requests.

**Comment by justinbmeyer** [comment]
Why wouldn't this happen automatically by the algorithm?

**Comment by matthewp** [comment]
There's a bug. Whatever code set's the node's bundles is not appending so these plugins are not treated as dependencies of the main.

**Comment by matthewp** [comment]
I'm going to look into this now.
