### ISSUE TITLE
Option to bundle independent modules into single JS file

### ISSUE THREAD

**Issue by isadovskiy** [stealjs/steal-tools#299]
Right now, if multiple modules are specified in http://stealjs.com/docs/System.main.html, Steal Tools will handle them on wise way and output multiple JS files with shared dependencies.

We need a bit different workflow for our site build. We have a big amount of small individual, independent modules, which are used across the pages. Since content of the page is controlled via CMS Admin UI (author can dynamically add any module on any page) we can not predict which modules will go to each page. Thus we can't create main JS files for every page, listed it's dependencies. Instead, we should have the single main file, has all modules we have on site as their dependencies, to build them all into single production JS file. 

Because of very big amount of modules, we son't want to create and maintain main index JS file manually. Instead, we have a gulp task, which iterates through the folders, searches for JS files, generates and writes temporary main.js file (having all modules as a dependencies). This temp file goes into StealTools to produce all.production.js and then purges.

I think it would be great to suppress this additional temporary file generation and removal steps by providing the opportunity to produce single production JS files from multiple main files directly from Steal Tools. I imagine, there could be some additional configuration option, like "optimizeBundles" ("true" by default). Default behavior will work exactly like it works currently. However turning off "optimizeBundles" should just disable wise bundling logic and just put everything into single JS file. Probably, in this case, an additional "out" options should be specified to define the output file name.

Please let me know if it makes sense and could become a part of Steal Tools.

**Comment by justinbmeyer** [comment]
Can you do this already by specifying all the widget modules that may load and specifying a bundle depth of 2?

**Comment by isadovskiy** [comment]
@justinbmeyer, sorry, but I'm just not clear how specifying bundling depth to 2 will help here.

Lets image I have module1.js, module2.js and module3.js and they are completely independent. 

My understanding is having `main: ['module1', 'module2', 'module3']` will produce 3 separate JS files, while I would like to have the single one, having all 3 listed modules (and all their dependencies) inside.

**Comment by justinbmeyer** [comment]
Can you create another module that imports them and set that in bundles. It will likely group them together.

**Comment by isadovskiy** [comment]
Yes, this is how it works for us now. But, as I explained above, we would like to make it automatic (since maintainig such file, indexed all modules, manually is not a goof idea because of huge amount of modules we have and they are constantly added). Right now we issues it with gulp script and temporary index module js file creation. But I would like to suppress this operation with creating/removing temporary file, listed all dependencies. 

It could be addressed by stealjs, if it would support "bundle all in one" mode. So proposing it. Probbaly could be useful not just for our workflow, described above.

**Comment by isadovskiy** [comment]
If you don't think it makes sense to have such mode as a part of stealjs, you can close this issue. Since temporary file generation in general works for us. Just looking for more elegant way to work this around.

**Comment by justinbmeyer** [comment]
I wonder if canjs's download builder would be a good solution. Build your bundles and cache them on the fly.

**Comment by isadovskiy** [comment]
Again, not sure what do you mean... Modules I'm talking about are our own JS modules, built on top can.Control. Can't understand, how canjs's download builder could help...

**Comment by justinbmeyer** [comment]
Canjs's download builder could dynamically build the modules of your app. It's designed to work with other projects. It's more than just the checkboxes you see. There's an underlying API.

**Comment by isadovskiy** [comment]
Thanks for the tip! I'll take a look.

**Comment by isadovskiy** [comment]
@justinbmeyer, did you mean https://github.com/bitovi/steal-tools-builder ?

**Comment by isadovskiy** [comment]
@justinbmeyer,could you confirm, at this repo I should look for download builder? Also do you have documentation or samples how it should be used?

**Comment by isadovskiy** [comment]
BTW, doesn't http://stealjs.com/docs/steal-tools.export.html can write multiple independent modules into the same file?

**Comment by justinbmeyer** [comment]
Ping me on gitter tomorrow.

**Comment by isadovskiy** [comment]
@justinbmeyer, @matthewp, so, just to clarify, if there a way to pack two completely independent modules into single bundle? Lets say I want to pack several jquery plugins into separate bundle? Or the only way is to create a master file, which will explicitly lists all plugins as the dependencies?

Also, as a side question, do you have any plan to support something similar to bundle arithmetic from SystemJS Builder in order to provide better manual control over the bundling process?

**Comment by justinbmeyer** [comment]
@isadovskiy I think we'll need to talk this out over gitter.  I think there is a way to specify side-bundles.  You probably need another module that explicitly imports all of those plugins as dependencies.  @matthewp would know better.


What do you mean by "bundle arithmetic"? This kinda stuff: https://www.youtube.com/watch?v=C-kM0v9L9UY ?

**Comment by isadovskiy** [comment]
@justinbmeyer, I'll contact you in gitter.

As for bundle arithmetic, I meant this: https://github.com/systemjs/builder#bundle-arithmetic. Basically, build tool from SystemJS provides rather sophisticated manual control over manual bundling configuration. I know, StealJS main feature is automatic bundles optimization. But due to a number of reasons I need to use manual control over the bundling process. And I just can't switch to another build tool since we are using system plugin to build stache templates.
