### ISSUE TITLE
UTF-8 to Unicode problems

### ISSUE THREAD

**Issue by justinbmeyer** [stealjs/steal-tools#310]
Seems like some UTF8 is being written out as unicode:

https://gitter.im/stealjs/steal?at=55fa43f30ed44a00046ea2d8

**Comment by matthewp** [comment]
I don't understand character encoding all that well. We do write out files as utf8, should we not be doing that? If we don't will they be converted to the correct format? I wonder how this can be tested...

**Comment by matthewp** [comment]
@kishoremvrs since you discovered this bug any assistance you can provide would be helpful.  Like perhaps an example input file with chinese characters.

**Comment by matthewp** [comment]
Let's start with a test and take it from there.
