### ISSUE TITLE
Something breaks my build in 0.11 (vs 0.11.0-pre.8 that works)

### ISSUE THREAD

**Issue by whitecolor** [stealjs/steal-tools#317]
My build is broken after 0.11 (and in later version), built app is not loading, the screenshot of :
![image](https://cloud.githubusercontent.com/assets/736697/10261956/8d6b38e8-69cc-11e5-83ab-aae7760c23f6.png)

currently I use 0.11.0-pre.8 - build works there all right.

Not sure how I can be more specific.

**Comment by matthewp** [comment]
Do you have deps config for bootstrap.

**Comment by whitecolor** [comment]
no, should, I? Why did it work in prior version?

**Comment by matthewp** [comment]
Not sure why previously, if you can provide a sample I can take a look.

**Comment by matthewp** [comment]
This should be easy to debug, just do a build with the working version and then compare the output (the bootstrap part) to 0.11'see output.
