### ISSUE TITLE
Built version System.env window-development

### ISSUE THREAD

**Issue by whitecolor** [stealjs/steal-tools#331]
0.12, app built version System.env `window-development`. Why? Before it was `production` in built versions.

**Comment by justinbmeyer** [comment]
what is the question?

**Comment by whitecolor** [comment]
Shouldn't it be `production`?

**Comment by justinbmeyer** [comment]
Env wasn't `production` previously, it was built in `development`, but ran in `production`.

Now, there are multiple environments an app might want to run in ... for example `node` and `window`.  Where `node` means, it's running in NodeJS, and `window` means it is running in browser-like environment.

So `window-development` means load the app as it would load in a browser environment in dev mode.

@matthewp please correct me if i'm wrong on anything.

**Comment by whitecolor** [comment]
Well, in earlier steal versions built package always had `System.env == 'production'`.

**Comment by matthewp** [comment]
This is related to the new `envs` config [shown here](http://stealjs.com/docs/System.envs.html).  This provides a way to have config that is only applied in certain environments. This was needed when building DoneJS and realizing there is different needs on the server, client, and potentially places like Cordova and NW.js.

There are new methods you can use [System.isEnv](http://stealjs.com/docs/System.isEnv.html) differentiates between dev/staging/production and [System.isPlatform](http://stealjs.com/docs/System.isPlatform.html) to see if you are running on client/server/webworker/ where ever.

**Comment by matthewp** [comment]
Going to close, but feel free to ask more questions if it's unclear.
