### ISSUE TITLE
steal bundlesPath do not work as expected

### ISSUE THREAD

**Issue by pYr0x** [stealjs/steal-tools#334]
as the documentation says,

> A convience configuration property for setting the path of where the production bundles folder is located.

my build.js looks like 
```
var stealTools = require("steal-tools");

stealTools.build({
    main: "javascript/web/index/index",
    config: __dirname + "/package.json!npm",
    bundlesPath: __dirname + "/javascript/dist"
}, {
    minify: false,
    bundleSteal: false,
    bundleAssets: false
});
```

in the bundled file the system path was set by steal-tools to:
```
System.paths["bundles/*.css"] = "../../../../javascript/dist/*css";
System.paths["bundles/*"] = "../../../../javascript/dist/*.js";
```
after the build, the css file is not loading -> wrong path

***Note: the app is located at http://localhost/mycanjsapp/***

i tried:

1. ```<script src='node_modules/steal/steal.js' env="production" bundles-path="/mycanjsapp/javascript/dist" main="javascript/web/index/index"></script>```

    **Result:** css file still not loading ```GET http://localhost/javascript/dist/javascript/web/index/index.css```

2. 
  ```
  <script>
  steal = {
   bundlesPath: "/mycanjsapp/javascript/dist",
   env: "production"
  };
  </script>
  <script src='node_modules/steal/steal.js' main="javascript/web/index/index"></script>
   ```

   **Result:** css file still not loading ```GET http://localhost/javascript/dist/javascript/web/index/index.css```

3. 
 ```
<script>
steal = {
    bundlesPath: "/mycanjsapp/javascript/dist",
    env: "production"
};
</script>

<script src='node_modules/steal/steal.js' main="javascript/web/index/index"></script>
<script>
    System.paths["bundles/*.css"] ="/mycanjsapp/javascript/dist/*css";
    System.paths["bundles/*"] = "/mycanjsapp/javascript/dist/*.js";
</script>
 ```
     **Result:** css file still not loading ```GET http://localhost/javascript/dist/javascript/web/index/index.css```

The Problem is, whatever set via ```steal``` or ```System.paths``` it will be overwritten in the bundled file, see above.

The solution would be to conditional setter in the bundled file
```
System.paths["bundles/*.css"] = (!System.paths["bundles/*.css"]) ? "../../../../javascript/dist/*css" : System.paths["bundles/*.css"];
System.paths["bundles/*"] = (!System.paths["bundles/*"]) ? "../../../../javascript/dist/*.js" : System.paths["bundles/*"];
```
in https://github.com/stealjs/steal-tools/blob/v0.13.0-pre.0/lib/bundle/make_bundles_config.js#L46-L48 somethink like that:

    var paths = util.format('System.paths["bundles/*.css"] = (!System.paths["bundles/*.css"]) ? "%s/*css" : System.paths["bundles/*.css"];\n' +
            'System.paths["bundles/*"] = (!System.paths["bundles/*"]) ? "%s/*.js" : System.paths["bundles/*"];\n',
            bundlesPath, bundlesPath);

**Comment by matthewp** [comment]
The bundlesPath should be relative to the page.  So in your script tag use `<script src='node_modules/steal/steal.js' env="production" bundles-path="javascript/dist" main="javascript/web/index/index"></script>`.  Let me know if that works, might need to update the docs to make it clearer.

**Comment by pYr0x** [comment]
is not working...
![](http://i.snag.gy/PeKUO.jpg)
the bundled file still overwrites the paths that are set via attributes

```
/*[system-bundles-config]*/
System.paths["bundles/*.css"] ="../../../../javascript/dist/*css";
System.paths["bundles/*"] = "../../../../javascript/dist/*.js";
```

**Comment by matthewp** [comment]
I'm a little confused, what's different about your app vs. this test? https://github.com/stealjs/steal-tools/blob/master/test/test.js#L584

and https://github.com/stealjs/steal-tools/blob/master/test/other_bundle/bundle.html

**Comment by pYr0x** [comment]
maybe, i installed steal-tools globaly?

**Comment by matthewp** [comment]
No, I wouldn't think that's it... maybe we can pair on Wednesday or Thursday and figure it out together.

**Comment by pYr0x** [comment]
ok...

**Comment by whitecolor** [comment]
How to get rid of such paths in build files?
```
System.paths["bundles/*.css"] ="../../../../../../dist/*css";
System.paths["bundles/*"] = "../../../../../../dist/*.js";
```
Steal conventions still are not intutive and wierd.

**Comment by matthewp** [comment]
I think the mistake we made is making bundlesPath, the client side config (which is the path from the root to where the bundles are located) the same as bundlesPath, the build config (which is the path where to write out the bundles).  

The paths that get written should be the root + path to where the bundles are written.

This is a confusing part of Steal so we should definitely fix it.  How do you think it *should* work?

**Comment by justinbmeyer** [comment]
I think @whitecolor has brought this up before in a previous issue.  

The big thing to remember is that paths need to be transportable between client and server.  So most things need to be relative.  We don't know that a server's files are at: "/user/name/dev/project" and those files get hosted at: "localhost:8080/projects/project" in dev and "domain.com/" in production.

So, `bundlesPath` is a path from `baseUrl` to where your bundles are.  This should not be a name like: `__dirname+"/something"` because that is a full path.

The only alternative solution is to let people supply some type of full path that we "reverse" into these relative paths.

**Comment by matthewp** [comment]
It looks like we are reversing it into a full path, just incorrectly. @pYr0x's example is turning `__dirname + "/javascript/dist"` into `System.paths["bundles/*"] = "../../../../javascript/dist/*.js";` and I'm not sure why.

We should either throw when a full path is provided to steal-tools (with a good warning to make it relative to the baseUrl) or we should properly fix the paths.

**Comment by whitecolor** [comment]
can you explain what this paths meant to mean?
```
System.paths["bundles/*.css"] ="../../../../../../dist/*css";
System.paths["bundles/*"] = "../../../../../../dist/*.js";
```
Are this path to locate other bundle files from parent bundle?

Then this:
```
System.paths["bundles/*.css"] ="*css";
System.paths["bundles/*"] = "*.js";
```
should be enough? No?

**Comment by matthewp** [comment]
Those paths are a bug.  Here's how it should work. If your app is located at:

```
http://example.com/myapp
```

And you set the bundles to `javascript/dist/bundles` with:

```js
<script src="steal.production.js" bundles-path="javascript/dist/bundles"></script>
```

Then it will find the bundles at:

```
http://example.com/myapp/javascript/dist/bundles
```

If you don't set a bundlesPath it would expect to find them at:

```
http://example.com/myapp/dist/bundles
```

**Comment by whitecolor** [comment]
Ok, glad to here this. Btw in may hacky solution to all this still problems and shortages (like hashes on file) I removed this paths:
https://github.com/whitecolor/steal-pack-bundles/blob/master/index.js#L194


Any should test differnt `steal.production.js` locations as well and steal bundled.
```
<script src="javascript/dist/steal.production.js" bundles-path="javascript/dist/bundles"></script>
```

And docs should be very clear about that.

**Comment by justinbmeyer** [comment]
@whitecolor we do test this.  Example: https://github.com/stealjs/steal/blob/master/test/prod-bundlesPath/prod.html

**Comment by matthewp** [comment]
The bundles/* paths overriding what gets set through the script `bundles-path="../path/to/bundles"` config is a bit of a problem.  I think we need to only conditionally add these if not already set.
