### ISSUE TITLE
Mains using directories.lib are not named with the package name

### ISSUE THREAD

**Issue by matthewp** [stealjs/steal-tools#336]
`mycanjsapp@1.0.0#web/index/index` should be named `bundles/mycanjsapp/web/index/index` but is instead named `bundles/web/index/index`. This works if the main is using a plugin but not if it's a normal JavaScript file for some reason.

**Comment by matthewp** [comment]
Going to defer this bug for now as I'm not sure what to do. If the folder includes the package name this means the user has to include the package name in their production.html main.

**Comment by pYr0x** [comment]
@matthewp when do you have time to talk about the mycanjsapp and make a build together? :)

**Comment by pYr0x** [comment]
closed https://github.com/stealjs/steal-tools/pull/404
