### ISSUE TITLE
Recycling modules should detect virtual module children

### ISSUE THREAD

**Issue by matthewp** [stealjs/steal-tools#341]
live-reload and --watch mode both have a module, lib/graph/recycle that reuses (recycles) a dependency graph object when a file changes, so that rebuilds are much faster. 

One of the optimizations this has is to check if the module's dependencies have changed, and if not there is nothing that needs to be done except replace the source and remove the active source keys.

However, some types of modules should not go through this fast-path. An example is https://github.com/donejs/done-component which creates a few virtual modules. These virtual modules have their own dependencies, so merely checking if a component's dependencies have changed will give you a **false-negative**.

I think the fix I'm going to go with is that plugins can add a property to `load.metadata` that signals that the module should not be recycled. `load.metadata.unrecyclable`, most likely.  This way we'll skip the "fast path" and instead fully reload the .component modules.

**Comment by justinbmeyer** [comment]
@matthewp is there a way to follow the virtual modules dependencies?

**Comment by matthewp** [comment]
What the .component does is this (pseudo code):

```js
exports.translate = function(load){
  System.define(load.name + "/template.stache", templateSource);
  System.define(load.name + "/view-model", viewModelSource);
  ...

  return "define(['name/template.stache', 'name/view-model'], function() ..."
};
```

Ideally perhaps it would not call `System.define` but rather keep the sources in a side table and return that source in a fetch hook.  So calling translate would not have loader side-effects.

Then perhaps there could be a mechanism to check the virtual modules dependencies. That would probably be the ideal solution so that you could retain using the fast-path when no dependencies are added/removed.

**Comment by matthewp** [comment]
What do you think? That would be more work to implement but ultimately would mean .components could reload faster. I'm a little torn between doing this or doing it the easier way that will require doing a trace for the module (which always means reloading the config).  Maybe i'll try the easier way and see how slow it is.

**Comment by justinbmeyer** [comment]
I'd prefer not to add some other `unrecyclable` type option to remember if we can avoid it.

**Comment by matthewp** [comment]
The method I'm working on is to trap calls to System.define and check those for new dependencies in the same way we check normal modules.

**Comment by matthewp** [comment]
#344 Fixes this without any `unrecyclable` option or anything like that. We can detect virtual modules by overwriting System.define and then diff them in the same way we diff normal modules.
