### ISSUE TITLE
Config included in production build.

### ISSUE THREAD

**Issue by whitecolor** [stealjs/steal-tools#350]
I see that steal-tools include in main bundle all the package.json with resolved dependendcies and other extended stuff with paths etc. Does it even need this?

**Comment by justinbmeyer** [comment]
It needs it for the included dependencies. You can use npmIgnore to remove the ones you don't need.

**Comment by whitecolor** [comment]
it includes sytem paths, for example:
```
'name': 'jquery',
            'version': '2.1.4',
            'fileUrl': 'file:d:/Dropbox/Code/.../client/node_modules/jquery/package.json',
            'main': 'dist/jquery.js',
            'globalBrowser': {},
            'browser': {}
```
So it makes builds of the same code base different on different machines.
I think such things should be removed.

**Comment by matthewp** [comment]
Yeah, this is weird, should figure out a way to prevent the file system path from being included.

**Comment by matthewp** [comment]
Oh, this is a dupe of #198

**Comment by whitecolor** [comment]
Hm I've already forgot that made those issue!
