### ISSUE TITLE
Combined sideBundle

### ISSUE THREAD

**Issue by whitecolor** [stealjs/steal-tools#351]
`sideBundles` option which is:
```javascript
"system": {
  "meta": {
   "a": {
      "sideBundle": true
    },
    "b": {
      "sideBundle": true
    }
  }
}
```
It will produce `a` and `b` bundles separate from main and other bundles.
It is fine. BTW If I'm correct it is not described in steal docs, so user may not know about it.

But is there a way to combile multiple packages in one side bundle (`a` with `b` in one `c` bundle)?
Another thing that it would be possible to bundle modules using wilcard `a/*`

**Comment by whitecolor** [comment]
Any comment/advice on this?

**Comment by matthewp** [comment]
Why not create a `c` bundle that imports a and b? Mark that as a sideBundle and you've gotten your combined bundle.

**Comment by whitecolor** [comment]
Yes I tried it, but didn't get the result I expected. Probably should work. Steals makes it its own way) well its not so important. Probably may close.

**Comment by matthewp** [comment]
I've added some docs on sideBundle: http://stealjs.com/docs/load.metadata.html
