### ISSUE TITLE
Better minify (uglify) error handling

### ISSUE THREAD

**Issue by whitecolor** [stealjs/steal-tools#357]
Uising new `transpile` option got the minification error due to uglify still doesn't fully support new bable's formats https://github.com/mishoo/UglifyJS2/issues/895

But steal throws something like that:
```
Potentially unhandled rejection [1] Error
    at new JS_Parse_Error (eval at <anonymous> (...\node_modules\uglify-js\tools\node.js:1:0), <anonymous>:1526:18)
    at js_error (eval at <anonymous> (...\node_modules\uglify-js\tools\node.js:1:0), <anonymous>:1534:11)
```

I have to figure at what file cased this, and fix. For this I inserted the output here:
https://github.com/stealjs/steal-tools/blob/master/lib/buildTypes/minifyJS.js#L21

So I think there should be `try catch` and message containing `name of source file` where error occured to know where to address.

**Comment by matthewp** [comment]
Sure, here is the place to put the try/catch: https://github.com/stealjs/steal-tools/blob/master/lib/graph/minify.js#L8

`node.load.name` is the module name, `node.load.address` is the file path.

**Comment by whitecolor** [comment]
Ok perhaps I'll do)
