### ISSUE TITLE
Plugins used by buildConfig included in production build

### ISSUE THREAD

**Issue by matthewp** [stealjs/steal-tools#358]

**Comment by matthewp** [comment]
I went back to StealTools 0.7 to see how it handled it and nothing has changed. Modules that are brought in by buildConfig are treated as any other plugin and are an empty module in production (back then it used System.set, but now we use define() )

I don't think this is a bug. Would be nice to exclude these parts but I can't think of a good way off hand. We could have an excludeFromBuild flag or something.

**Comment by pYr0x** [comment]
now we can use the ignore option to exclude a module. write a new test #392
