### ISSUE TITLE
Transpiled by Babel6 module is not handled while build

### ISSUE THREAD

**Issue by whitecolor** [stealjs/steal-tools#359]
Steal doesn't wrap in `define` transpiled by Babel6 module:

Transpiled source found in built file:
```javascript
/*cycle-driver*/
'use strict';
Object.defineProperty(exports, '__esModule', { value: true });
exports.makeDriver = makeDriver;
exports.runCycle = runCycle;
var _rx = require('rx');
var _rx2 = _interopRequireDefault(_rx);
var _core = require('@cycle/core');
var _core2 = _interopRequireDefault(_core);
var _dom = require('@cycle/dom');
var _dom2 = _interopRequireDefault(_dom);
function _interopRequireDefault(obj) {
    return obj && obj.__esModule ? obj : { default: obj };
}
//...
```

Browser doesn't load it with error on filst line:
```
Uncaught ReferenceError: exports is not defined
```

**Comment by matthewp** [comment]
I assume you mean using the new `transpile` option?

**Comment by whitecolor** [comment]
Yes of cource, how would I get Babel6?
```
    bundleSteal: true,
    minify: true,
    transpile: (source) =>
      babel.transform(source, {
        presets: ['es2015', 'stage-0']
      }) 
```

**Comment by matthewp** [comment]
You have to tell Babel to transpile to AMD. Otherwise it will transpile to CommonJS default. This is the AMD plugin: http://babeljs.io/docs/plugins/transform-es2015-modules-amd/

**Comment by whitecolor** [comment]
Ok, thanks, why this works in browser, systemjs transforms it?

**Comment by matthewp** [comment]
No, in the browser it doesn't tranpsile to AMD at all, it goes to the "system" format. I made it so that's what's always used in the browser.  In the future I'd like to move transpiling to the "translate" step in which case the build and browser would be the same and you could do your own transpiling with a normal translate hook.

**Comment by whitecolor** [comment]
I currenlty deliver to the client already transpiled version by babel (withou amd plugin).
