### ISSUE TITLE
Simultaneous use of import and require (in one module)

### ISSUE THREAD

**Issue by whitecolor** [stealjs/steal-tools#362]
Currenlty, this will work in browser (babel transpiler handles it):
```javascript
var can = require('can')
import `can/map/define`
```
But it breaks build (what anoying you don't know the file which has been broken). 

So there also is need to have more `try catch` and output info about module that caused execption while parsing/transpilation/mification/etc.

**Comment by whitecolor** [comment]
Should this work right?

**Comment by justinbmeyer** [comment]
> Should this work right?

if babel handles it, it might be able to work.  However, our transpiling is handled by https://github.com/stealjs/transpile .  I'm not sure if that is using babel.  

> Should someone do this

no.  It's not a good idea to use different module formats even if you can.

**Comment by matthewp** [comment]
We should move transpiling to the `translate` step in which case this would probably work.

**Comment by justinbmeyer** [comment]
What does it transpile it to? I think es6 behavior is not in transpile to allow cycles.

**Comment by whitecolor** [comment]
So this is related https://github.com/stealjs/steal-tools/issues/363 I belive, because I use custom `transpile` with babel 6 (and it works actually, because with babel5 some modules wouldn't be handeld), but some how steal's babel 5 still gets involved in the process)

**Comment by pYr0x** [comment]
I see no need to write es6 and cjs in one module.
Close this.
