### ISSUE TITLE
TypeError: Cannot read property 'port' of null

### ISSUE THREAD

**Issue by aaronhall** [stealjs/steal-tools#364]
Getting this exception sometimes, but not always, when running can-serve:

```
can-serve starting on http://localhost:8080
./node_modules/steal-tools/lib/stream/live.js:29
        var port = wss.options.server.address().port;
                                               ^

TypeError: Cannot read property 'port' of null
    at module.exports (./node_modules/steal-tools/lib/stream/live.js:29:41)
    at Object.<anonymous> (./node_modules/steal-tools/bin/steal:83:2)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:429:10)
    at startup (node.js:139:18)
    at node.js:999:3
```

This is a race condition at https://github.com/stealjs/steal-tools/blob/master/lib/stream/live.js#L29

See https://nodejs.org/api/net.html#net_server_address: 

> Don't call server.address() until the 'listening' event has been emitted.

`http.Server.listen()` is called [here](https://github.com/stealjs/steal-tools/blob/master/lib/create_websocket_server.js#L6). `net.Server.listen` supports a [signature](https://nodejs.org/api/net.html#net_server_listen_port_hostname_backlog_callback) to pass a callback on `listening`. The port should be read there or in some callback bound to `listening`.

**Comment by matthewp** [comment]
Thanks!

**Comment by matthewp** [comment]
This detects if the port is already in use, we should add this as well.

https://github.com/donejs/done-serve/blob/master/bin/done-serve#L66
