### ISSUE TITLE
Allow custom minify/uglify

### ISSUE THREAD

**Issue by whitecolor** [stealjs/steal-tools#367]
Allong with custom `transpile`, I believe it would be useful to have ability to use custom minifier/uglifier (for example there is experimetal branches of uglify that works better with ES6/babel)

**Comment by matthewp** [comment]
Personally I'd rather finish up https://github.com/stealjs/steal-tools/issues/142. You could turn off minification get back the bundles, do whatever you wish with them, and then write them out yourself.

**Comment by whitecolor** [comment]
but you minify each module not bundle.

**Comment by matthewp** [comment]
Ideally the streams would be fine-grained so you would get back the bundles before being concatenated together. Then you could concat them and do minification OR you could minify before concatenation. You'd be able to do what you wanted.

**Comment by whitecolor** [comment]
Idealy)

**Comment by matthewp** [comment]
With streams you can now do your own minification.
