### ISSUE TITLE
Source Maps Support

### ISSUE THREAD

**Issue by justinbmeyer** [stealjs/steal-tools#37]
Make it possible to include source maps:

https://github.com/bitovi/steal/issues/103

**Comment by matthewp** [comment]
This is the next big feature I'm going to be working on. Will start next week.

**Comment by matthewp** [comment]
Some things I need to know:

* [ ] - Can I generate a source map from transforming an esprima AST?
  - Yes, if you create an ast and transform it, escodegen will generate source maps from that.
* [ ] - Can I concat the sources?
  - Look to see if I can concat esprima ast.
* [ ] - How to handle different types of asts.
  - Traceur creates it's own, can it be converted to esprima while maintaining source maps?  Ditto for Babel.  Can esprima be converted to others like Uglify?

**Comment by justinbmeyer** [comment]
> Yes, if you create an ast and transform it, escodegen will generate source maps from that.

How does that work?  How can you transform it in such a way that escodegen knows what the transformations are?

**Comment by matthewp** [comment]
I'm not sure, I need to research more to find out how that works. I'm guessing there are probably some limitations. Probably you have to perform operations they can track like `pop` and `unshift`.

**Comment by matthewp** [comment]
Wondering what the option should be:

```js
multiBuild(system, {
  sourceMaps: true
});
```

Would create sourcemaps.

```js
multiBuild(system, {
  sourceMaps: 'content'
});
```

Would include the source content with the sourcemaps.

```js
multiBuild(system, {
  sourceMaps: 'inline'
});
```

Would include the sourcemaps inline in the source (via base64 encoding).

**Comment by matthewp** [comment]
@justinbmeyer I'm a little conflicted on how to implement one issue.

Source maps have a `files` array which is the file names. The browser will load these files relative to where the source map is located.  There is also a `sourceRoot` property you can set to make the root of where files are looked for. So you might have something like:

```
foo.js
dist/
  bundles/
    foo.bundled.js
    foo.bundled.js.map
```

Right now I'm leaning towards having:

```json
{
  "files": ["foo.js"],
  "sourceRoot": "../../"
}
```

The other option would be to omit sourceRoot and make all `files` relative.

```json
{
  "files": ["../../foo.js"]
}
```

**Comment by justinbmeyer** [comment]
I'm not sure sourceRoot is the way to go because you will still have to deal with the paths config. Typically only app moduleIds are located directly from baseURL.

**Comment by matthewp** [comment]
There's a bug in source-map (https://github.com/mozilla/source-map/issues/174) that is blocking me on concatenating minified code at the moment.  There's a couple of possible workarounds but would prefer to fix the upstream bug.

While I wait for them to reply I'm going to finish up the remaining issues with sourcemaps and get all tests to pass again.

**Comment by matthewp** [comment]
This change will break transforms API.  Currently it returns source, now it will return an object like: `{ code, map }`

**Comment by matthewp** [comment]
Maybe we should just put this in a pre-release and when #80 is done those are 1.0.0.
