### ISSUE TITLE
Bundle names

### ISSUE THREAD

**Issue by matthewp** [stealjs/steal-tools#378]
We need to nail down how bundles should be named because it causes a lot of issues. All of the following should be covered:

# Without package name

```js
stealTools.build({ main: "app" });
```

```
dist/bundles/app.js
```

```html
<script src="steal.production.js" main="app"></script>
```

# With package name

```js
stealTools.build({ main: "package/app" });
```

```
dist/bundles/app.js
```

```html
<script src="steal.production.js" main="app"></script>
```

# Without package name with plugin

```js
stealTools.build({ main: "app!plug" });
```

```
dist/bundles/app.js
```

```html
<script src="steal.production.js" main="app!plug"></script>
```

# With package name with plugin

```js
stealTools.build({ main: "package/app!plug" });
```

```
dist/bundles/app.js
```

```html
<script src="steal.production.js" main="app!plug"></script>
```

The key is that, **whether or not you use the package name as your main when building, you should never have to use it in the script tag**.

**Comment by pYr0x** [comment]
this can be closed by https://github.com/stealjs/steal-tools/pull/402
