### ISSUE TITLE
using package name when loading multi-main app fails

### ISSUE THREAD

**Issue by matthewp** [stealjs/steal-tools#379]
Partially fixed in 17592fdf3ec79fed1d70de7728da69bc2aa80731

Related to #378

**Comment by matthewp** [comment]
@pYr0x is this one fixed?

**Comment by pYr0x** [comment]
@matthewp no this issue still exists. i have made a PR that we can work on
https://github.com/stealjs/steal-tools/pull/410

**Comment by matthewp** [comment]
Fixed by #417 I presume.
