### ISSUE TITLE
0.13.4 throws errors

### ISSUE THREAD

**Issue by daffl** [stealjs/steal-tools#380]
I am getting this error when doing a CanJS build:

<img width="243" alt="screen shot 2016-02-16 at 3 44 58 pm" src="https://cloud.githubusercontent.com/assets/338316/13095133/4e504df2-d4c4-11e5-95d1-381d435c4a7f.png">

It works with v0.13.3

**Comment by matthewp** [comment]
Thanks, caused by https://github.com/stealjs/steal-tools/pull/373, will fix in the morning.

**Comment by matthewp** [comment]
Fixed in 0.13.5
