### ISSUE TITLE
404 Warning when building with steal-tools

### ISSUE THREAD

**Issue by BigAB** [stealjs/steal-tools#385]
> Some 404s were encountered while loading. Don't panic! These will only happen in dev and are harmless.

This message should probably be suppressed when building with steal-tools.

<img width="554" alt="screen shot 2016-02-23 at 5 10 37 pm" src="https://cloud.githubusercontent.com/assets/76821/13269983/afdbe040-da50-11e5-8e23-102648103135.png">

**Comment by matthewp** [comment]
Ah, yeah you are right.  Here's where it is logged: https://github.com/stealjs/system-npm/blob/master/npm-extension.js#L300

**Comment by matthewp** [comment]
This no longer happens in Node: https://github.com/stealjs/system-npm/blob/4b1c26d5c38adf3629273215602b36748280e376/npm-extension.js#L382
