### ISSUE TITLE
After update to latest 14: build on windows fails

### ISSUE THREAD

**Issue by whitecolor** [stealjs/steal-tools#387]
After update to latest 14: build on windows fails
```
Potentially unhandled rejection [10] Error: Error loading "can/can" at file:d:/Code/app/client/can/can.js
Error loading "can/can" from "app" at file:d:/Code/app/client/app.js
ENOENT: no such file or directory, open 'd:\Code\app\client\can\can\index.js'
    at Error (native)
```

**Comment by whitecolor** [comment]
I've also noticed changed behaviour of map fileds

for example, this mapp:
```
"./shared": "../node_modules/shared_module",
```

allowed to require
```
require('shared/my/module')
```
And it would be loaded from `../node_modules/shared_module/my/module` it doesn't work with latest.

**Comment by pYr0x** [comment]
itsn't 0.15 the latest?

**Comment by whitecolor** [comment]
I will check it.

**Comment by matthewp** [comment]
Need more info than provided here to do anything with.

**Comment by whitecolor** [comment]
Will check it again, just tried to update from 0.13 and it didn't work.
