### ISSUE TITLE
Problem with maping in 0.14

### ISSUE THREAD

**Issue by whitecolor** [stealjs/steal-tools#388]
I've also noticed changed behaviour of map fileds

for example, this map:
```
"./shared": "../node_modules/shared-module",
```

allowed to require
```
require('shared/some/thing')
```
And it would be loaded from `../node_modules/shared_module/some/thing` it doesn't work with latest.

```
Potentially unhandled rejection [7] Error: Error loading "my-app-client@0.1.0#../node_modules/shared-module/some/thing" at file:d:/Code/my-app/client/node_modules/shared-module/some/thing.js
Error loading "my-app-client@0.1.0#../node_modules/shared-module/some/thing" from "app" at file:d:/Code/my-app/client/app.js
ENOENT: no such file or directory, open 'd:\Code\my-app\client\node_modules\shared-module\client\models\auth\index.js'
    at Error (native)
```

**Comment by pYr0x** [comment]
this problem also exists in 0.15?

it would be great if you can provide a test..

**Comment by matthewp** [comment]
I don't know why that was ever working `../node_modules/shared-module` is not a valid map, probably you meant to put this into paths?

**Comment by pYr0x** [comment]
@whitecolor yes, metthewp is right, `path` should be the right place for that.

**Comment by whitecolor** [comment]
I will check, earlier I used paths but then switched to map) and currenlty it works for version <0.14

**Comment by whitecolor** [comment]
close it here and open in steal.
