### ISSUE TITLE
Switch to using polling for live-reload's watch

### ISSUE THREAD

**Issue by matthewp** [stealjs/steal-tools#405]
Works better when doing `npm install`s.

**Comment by pYr0x** [comment]
polling so also needed for using donejs-vagrant via sync folders

**Comment by matthewp** [comment]
Oh really? Cool, I'm going to fix this today or tomorrow, will let you know and you can test with vagrant.

**Comment by pYr0x** [comment]
for now i using https://github.com/whitecolor/watchalive he has also a cool proxying we are using in https://github.com/cherifGsoul/steal-yii/blob/npm/web/package.json#L75
this is for hot module swaping. if there is a request not of (node_modules|css|js) the server sends the request to the PHP server
does steal also provide this?
