### ISSUE TITLE
Consider renaming exports option for pluginify

### ISSUE THREAD

**Issue by matthewp** [stealjs/steal-tools#41]
Pluginify has an option called `exports` that you use like this:

```js
pluginify(system, {
  exports: {
    "jquery": "jQuery"
  }
}).then(function() { ... })
```

jQuery being any object on the window.  Exports is an inappropriate name here. Perhaps `imports`? 

Also we might want to have an actual `exports` option where you export your module's definitions onto the window.

**Comment by justinbmeyer** [comment]
@matthewp Yes, I think imports would probably be nicer.
