### ISSUE TITLE
Remove steal-remove statements earlier, or prevent devDependencies from making it to build

### ISSUE THREAD

**Issue by DesignByOnyx** [stealjs/steal-tools#416]
We have some dev dependencies which are being included in our final build. Most notably our fixtures were being built, despite using the following code:

```js
//!steal-remove-start
import "@src/models/fixtures/";
//!steal-remove-end
```

The import statement was actually being removed, but the fixtures were still built into the final output because the import statement was processed _before_ it was removed. We are also using Moment.js - but not in production code. We are using it for some development-only related purposes. It's listed as a devDependency, and we wrapped the import statement with `steal-remove` - yet it still got built into the final file.

We were able to fix this with configDependencies during build but didn't know we had to do this until we manually inspected our production files:

```js
if ( isBuild ) {
  return {
    map: {
      "moment": "@empty",
      "@src/models/fixtures/fixtures": "@empty"
    }
  }
}
```

**Comment by justinbmeyer** [comment]
The better solution for this is conditional dependencies.

**Comment by justinbmeyer** [comment]
we could make `//!steal-remove-start` part of a translate hook.

**Comment by pYr0x** [comment]
@DesignByOnyx can you use http://stealjs.com/docs/steal-tools.build.html#section_ignore ?

**Comment by matthewp** [comment]
Removing the import from the source really only makes sense if the module your using is purely for side effects. Imagine you had some code like:

```js
import foo from 'foo';

// foo is dev only
if(foo) {
  foo();
}
```

If we removed the import statement here it would throw in production. You could work around this by using `typeof foo` instead but it's non-obvious.

But the use-case aside, removing dev comments earlier might be a good idea.

**Comment by DesignByOnyx** [comment]
We remove the actual code too - so by the time the app is built, we were neither importing or referencing the module - yet it was still getting bundled.

I think it could be a handy warning if we let users know if a dev dependency is being referenced by production code. It shouldn't block the build, but letting users know they have a dev dependency 'foo' being referenced in production code would be useful. Our minified file went from 857Kb to 653Kb, but aside from manually inspecting the file I would have never caught it.

**Comment by matthewp** [comment]
Going to close this as I don't see an actionable item. Let's reopen if anyone disagrees.
