### ISSUE TITLE
Latest release breaks CanJS major build

### ISSUE THREAD

**Issue by daffl** [stealjs/steal-tools#424]
The latest steal-tools release breaks something in the AMD build for CanJS (tested only in the `major` branch at the moment). This is what I and @BigAB are seeing:

![screen shot 2016-03-21 at 3 37 12 pm](https://cloud.githubusercontent.com/assets/338316/13936451/09f391ec-ef7b-11e5-97e6-3acd081a2959.png)

**Comment by daffl** [comment]
Downgrading to 0.15.3 fixes the issue.

**Comment by matthewp** [comment]
This is fixed now.
