### ISSUE TITLE
build production with steal-tools streams throw an error with live-reload

### ISSUE THREAD

**Issue by pYr0x** [stealjs/steal-tools#431]
if you add in your package.json file the live-reload config dependency like
```
"configDependencies": [
      "live-reload"
    ]
```
and you use streams for building
```
var stream = stealStream.graph(system, options)
		.pipe(stealStream.transpile())
		.pipe(stealStream.minify())
		.pipe(stealStream.bundle())
		.pipe(stealStream.concat())
		.pipe(stealStream.write());
```
live-reload throw an error in production file

the problem, @matthewp identify is, that the streams are not setting the config for `localSteal` like `build()` did https://github.com/stealjs/steal-tools/blob/master/lib/build/multi.js#L76

**Comment by pYr0x** [comment]
@matthewp can we remove does lines
* https://github.com/stealjs/steal-tools/blob/master/lib/build/multi.js#L76
* https://github.com/stealjs/steal-tools/blob/master/lib/build/transform.js#L31

and replace this line https://github.com/stealjs/steal-tools/blob/master/lib/graph/make_graph.js#L29 with `localSteal.System.config({ env: "build-development" });` ?
is that better? we dont need to set for localSteal any `env` anymore

**Comment by matthewp** [comment]
Yes, I think that will be fine. I think this was needed for the canjs build, but I can find another way to fix that.

**Comment by pYr0x** [comment]
> but I can find another way to fix that.
what do you mean? should i fix this with my suggestion?

**Comment by matthewp** [comment]
Yes, you can fix this with your suggestion.
