### ISSUE TITLE
Better docs for how to turn on debugging with stealTools.exprot

### ISSUE THREAD

**Issue by justinbmeyer** [stealjs/steal-tools#436]
The example here shows it:

http://stealjs.com/docs/steal-tools.export.html

But the options object isn't actually given a type with possible values (I tried debug: true and it didn't work):

```
options {Object}
Options that configure logging.
```

**Comment by pYr0x** [comment]
Debug: true isn't a valid option ... I think it is verbose: true 
http://stealjs.com/docs/steal-tools.export.object.html

**Comment by justinbmeyer** [comment]
yeah, it's verbose.

**Comment by pYr0x** [comment]
Can we close this?

**Comment by justinbmeyer** [comment]
Nope, I knew prior to posting the issue, that `verbose` worked.  My issue was about properly documenting the available options on the options object.  

They are missing here too: http://stealjs.com/docs/steal-tools.export.object.html

![stealjs_-_exportobject](https://cloud.githubusercontent.com/assets/78602/14439046/bb162a74-ffee-11e5-8e50-7c5946770699.png)

**Comment by justinbmeyer** [comment]
Specifically, I wanted a link where the following arrow is on http://stealjs.com/docs/steal-tools.export.html

![stealjs_-_export](https://cloud.githubusercontent.com/assets/78602/14439082/eff39d8a-ffee-11e5-8e8d-44c4dccb6ae8.png)
