### ISSUE TITLE
Global shim support exporting global.  

### ISSUE THREAD

**Issue by justinbmeyer** [stealjs/steal-tools#443]
Often you want a module to export a global.  Currently, I hack that in like this:

```
if(typeof window !== "undefined" && !require.resolve) {
	window.fixture = fixture;
}
```

We should make `exports` be able to do the reverse.  `{"can-fixture": "fixture"}`

**Comment by justinbmeyer** [comment]
The way to do this is to make `lib/bundle/shim.js`'s `define` after the export is saved here:

```
modules[moduleName] = module && module.exports ? module.exports : result;
```

it should check if `moduleName` is in `exports` and if it is, add the right thing to the global. We probably need a `set` similar to `shim.js`'s `get` that could set a nested property like:

```
exports: {"can-fixture", "can.fixture"}
```

I wonder if we could even supply multiple.  That would be cool for it to try to put it on `window.can`, failing that `window`.

**Comment by matthewp** [comment]
This is available now: https://github.com/stealjs/steal-tools/pull/463
