### ISSUE TITLE
Warnings with Node 6

### ISSUE THREAD

**Issue by daffl** [stealjs/steal-tools#455]
When running a steal-tools build the following warnings (among others) are shown:

```
(node:14137) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node) v8::ObjectTemplate::Set() with non-primitive values is deprecated
(node) and will stop working in the next major release.
```

**Comment by matthewp** [comment]
@mjstahl saw this too today. I think we just need to update our fs-extra version. I'll look into it.

**Comment by mjstahl** [comment]
And if I remember correctly, it was graceful-fs v3 -> v4.

**Comment by matthewp** [comment]
This is in the major branch, and 1.0 prerelease.
