### ISSUE TITLE
steal is broken by `{...options}` spread operator

### ISSUE THREAD

**Issue by whitecolor** [stealjs/steal-tools#459]
`s.graph(config, stealOptions)` - just building graph.

is broken by code `{...options}`

```
Potentially unhandled rejection [5] SyntaxError: file:.../web.js: Unexpected token (8:24)
   6 | 
   7 | var initWebApp = function(opts){
>  8 |   slog('WEB-APP INIT', {...opts})
     |                         ^
   9 |   var auth = new Auth()
  10 | 
  11 |   var appState = new AppState()
    at Parser.pp.raise (file:.../steal/ext/babel.js:32696:13)
```

Just building graph. Why is it using babel at all at this step?

Worked before 0.15.

**Comment by matthewp** [comment]
Thanks, will take a look.

**Comment by whitecolor** [comment]
Ok, would be greatful.

**Comment by matthewp** [comment]
Cannot recreate. This commit adds a test that does what you are doing and it works ok.  https://github.com/stealjs/steal-tools/commit/51afe845513723efaa9b23a2f6e2da65790111a2

Can you reduce down your code? Start by removing every dependency except the main.  Add them back one at a time until you see it break again.

**Comment by matthewp** [comment]
I was able to get it to break, will look into what is going on.

**Comment by matthewp** [comment]
So the issue is that we do use the transpiler (babel or traceur) to get the dependencies of a module. We have to get the deps ourselves (with regexes probably) -- and not use the transpiler -- in order to make this work. I think they should be fairly simple regexes though, so it's probably fine.

**Comment by matthewp** [comment]
This is the root issue: https://github.com/stealjs/system-trace/issues/14

**Comment by whitecolor** [comment]
I tried the code what I see:
1) comments are not handled properly, so imports that are commented
2) `can-import` is handled (again when is not needed in comments) 

for 1 and 2 probably need to use `^/s*import ...` 

3) presence of `import` and `export` is not enough to consider module to be ES6 - I'm not sure what can be done about it. All this methods and regexp s are not very reliable in general.

**Comment by whitecolor** [comment]
A I don't know what it is doing but it doesn't build app correctly it just do not include files from `import` in the build.

**Comment by whitecolor** [comment]
For handling comments I would remove first block comments /* */ and then used expression something like this /(?:^|\n)\s*import .*["'](.+)["']/g;

**Comment by matthewp** [comment]
I have a fix for the comment issue. can-import is not applicable here, this is only for ES6 import/export code, we need it to build the dependency graph.

**Comment by matthewp** [comment]
https://github.com/stealjs/steal/pull/690 will fix the comment issue. Will add a test here to verify.

**Comment by whitecolor** [comment]
this should be check attentively there many cases like
```js
import 'first-line'
import 'line-start'
  import 'space-before'
// import 'comment'
/* import 'block-comment' /*
 /*
 import 'block-comment-multiline'
/*
```

**Comment by matthewp** [comment]
These cases are covered: https://github.com/stealjs/system-trace/blob/master/test/tests/basics/c.js

**Comment by matthewp** [comment]
`export from` is one I hadn't thought of, will add that.

**Comment by matthewp** [comment]
Thanks, all of those cases are covered now and tested.

**Comment by whitecolor** [comment]
Ok, hope you will cover all the cases with specifiers as wll
`import {x} from ` etc

**Comment by whitecolor** [comment]
Was this released?

**Comment by matthewp** [comment]
Yeah, in 0.16.3

**Comment by whitecolor** [comment]
That is the issue I wan't to ask about, and posted in another, sorry)
