### ISSUE TITLE
stealTools.export broken with relative main

### ISSUE THREAD

**Issue by justinbmeyer** [stealjs/steal-tools#462]
If I have a main in `package.json` like:

```
"main": "./can-view-parser",
```

I get the following error:

```
Justins-MacBook-Pro-2:can-view-parser justin$ node build.js 
OPENING: /Users/justin/dev/can-view-parser/package.json!npm
OUTPUT: +amd
/Users/justin/dev/can-view-parser/node_modules/steal-tools/lib/build/transform.js:23
		throw e;
		^

Error: Cannot resolve a relative module identifier with no parent module:
    at Object.utils.moduleName.parseFromPackage (file:/Users/justin/dev/can-view-parser/node_modules/steal/ext/npm-utils.js:217:11)
```

**Comment by matthewp** [comment]
what's the use case? a relative main doesn't make sense, modules are always relative to their parent, if there is no parent this error should occur imo.

**Comment by justinbmeyer** [comment]
I think a relative main makes sense.  It's the path relative to the `package.json` location.  It's supported by CJS/NPM, we should probably support it too.

**Comment by matthewp** [comment]
Ok, this a system-npm issue then.

**Comment by justinbmeyer** [comment]
Strangely, it works fine when loaded from the browser.  It only surfaced when building.

**Comment by matthewp** [comment]
That is strange, i'll try and recreate it.

**Comment by matthewp** [comment]
I was able to reproduce it in the browser, this gist demonstrates: https://gist.github.com/matthewp/6e8c05ab7bd92d75ded0763f10e1ba38

Moving the issue to https://github.com/stealjs/system-npm/issues/137
