### ISSUE TITLE
Why does bundleAssets break things?

### ISSUE THREAD

**Issue by justinbmeyer** [stealjs/steal-tools#477]
In my sample app, if I have:

```js
var stealTools = require("steal-tools");

stealTools.build({
    config: __dirname+"/package.json!npm"
}, {
  bundleAssets: true,
  bundleSteal: true
});
```

The app looks for my `myapp/puppies/puppies` module in: `bundles/myapp/puppies/puppies`.  However, if I change the build to:

```js
var stealTools = require("steal-tools");

stealTools.build({
    config: __dirname+"/package.json!npm"
}, {
  bundleSteal: true
});
```

The app correctly loads the `myapp/puppies/puppies` module in: `dist/bundles/myapp/puppies/puppies`.

**Comment by matthewp** [comment]
Because the bundleAssets option is meant for bundling everything into the `dist/` folder and deploying that folder alone, to something like a CDN.  When we deploy DoneJS apps to Firebase the dist/ folder is the root.

**Comment by matthewp** [comment]
Closing, can discuss further if there are more questions here.
