### ISSUE TITLE
ES modules don't export to globals nicely

### ISSUE THREAD

**Issue by justinbmeyer** [stealjs/steal-tools#480]
A module like:

```
// repos.js
export default function(selector){ ... }
```

That I'd like to be a global `repos` function, so I configure export like:

```
"+global-js": {
        exports: {
            "myhub/repos/repos":"repos",
            "jquery": "jQuery"
        },
        dest: __dirname+"/dist/global/repos.js"
    }
```

doesn't work in a page like:

```
<div id='git-repos'/>
<script src="//code.jquery.com/jquery-3.0.0.js"></script>
<script src="../dist/global/repos.js"></script>
<script>
    repos("#git-repos");
</script>
```

That needs to be:

```js
<div id='git-repos'/>
<script src="//code.jquery.com/jquery-3.0.0.js"></script>
<script src="../dist/global/repos.js"></script>
<script>
    repos["default"]("#git-repos");
</script>
```

**Comment by justinbmeyer** [comment]
I think the fix to this is to have the global-shim-start export the default if `__esModule` is true.  I can't think of any time where someone would want to export a Module as a global.

**Comment by matthewp** [comment]
I can see having a module like:

```js
export function each() {

}

export function map() {

}
```

```js
"+global-js": {
        exports: {
            "lodash": "_"
        },
        dest: __dirname+"/dist/global/repos.js"
    }
```

and expecting that to create `_.each` and `_.map`.  That being said, could check if "default" is the only export, in which case it becomes the value.

**Comment by justinbmeyer** [comment]
Yeah, I could see that actually. But agreed, if default is the only thing, it should be the value.

**Comment by matthewp** [comment]
Closing as this is released, will verify your zip.
