### ISSUE TITLE
inconsistency with build

### ISSUE THREAD

**Issue by justinbmeyer** [stealjs/steal-tools#492]
Someone went through the guide with the initial folder and package called `my-hub`, but left everything else the same (`main: "myhub.js"`), instead of making a `dist/bundles/my-hub/myhub.js`, steal-tools made a ``dist/bundles/myhub.js`.

**Comment by matthewp** [comment]
Could you provide what they ran to do the build (like a build script or whatever) and what their package.json looked like?

**Comment by matthewp** [comment]
In 1.0 the package name is always included in the folder that is written out.
