### ISSUE TITLE
live-reload is broken w/ latest DoneJS

### ISSUE THREAD

**Issue by justinbmeyer** [stealjs/steal-tools#493]
if I go through the start of the DoneJS PMO guide to this point: https://donejs.com/place-my-order.html#section=section_Developmentmode

if I change styles.less, it doesn't always update the styles.

**Comment by matthewp** [comment]
Looks like the less is being cached and not refetched, not sure where the problem is yet, investigating.

**Comment by matthewp** [comment]
Ah, I think this is related to a double-loading bug I fixed last week.

**Comment by matthewp** [comment]
Caused by https://github.com/stealjs/steal-less/pull/21

**Comment by matthewp** [comment]
I sort of want to revert that PR, I'm not sure it's steal-less' responsibility to ensure that a less file is only fetched once. Steal and Less have different fetching mechanisms so if you import a file in less and also import it in JavaScript it would be fetched twice (before my PR).  Going to see if I can make live-reload work again for now.

**Comment by matthewp** [comment]
Bug is in steal-less: https://github.com/stealjs/steal-less/issues/25

**Comment by matthewp** [comment]
Fixed in Steal  0.16.25
