### ISSUE TITLE
watch mode breaks module paths

### ISSUE THREAD

**Issue by shcarrico** [stealjs/steal-tools#495]
I running on 1.0.0-beta.1

using a `paths` configuration such as

```
{
  "jquery": "https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.js",
  "angular": "https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.12/angular.js"
}
```

works great normally and with the initial build including `watch : true` as a build option.

Subsequent builds initiated by the watch process seem to lose the path configuration and start trying to resolve these modules as if there was no path specified..

**Comment by matthewp** [comment]
Does it matter that this are http(s) paths, or does it do this with normal paths as well?

**Comment by shcarrico** [comment]
This may be related to #496 .. perhaps that "build" flag is not being respected in watch mode.

**Comment by matthewp** [comment]
Where is `"build": false` documented? I wasn't able to find that. I know there is a `"bundle": false`, is that what you meant to use?

**Comment by m-mujica** [comment]
@matthewp I set up an example app using jquery from a CND with a path config, and it won't build, there is code in the loader to throw if it's not a file url in Node https://github.com/stealjs/steal/blob/b3a5a75f6154538d19fc9566840d804a12fc8d3b/src/loader/loader.js#L3097

I'm going to try with a local path.

**Comment by m-mujica** [comment]
Could not replicate in this app

https://github.com/m-mujica/steal-tools-watch-paths

![screen shot 2017-04-20 at 15 58 20](https://cloud.githubusercontent.com/assets/724877/25254380/82135dee-25e2-11e7-9a31-d2cf00804dec.png)

**Comment by matthewp** [comment]
Cool, maybe fixed by some other change in the meantime. Will reopen if we find out otherwise.
