### ISSUE TITLE
steal-tools dependency direct to github file

### ISSUE THREAD

**Issue by sergiomcunha** [stealjs/steal-tools#497]
To install steal-tools trough through npm, there's a dependency "source-map" pointing to a file on github. 

    "source-map": "https://github.com/stealjs/source-map/archive/0.4.2-bitovi.1.tar.gz",

At the environment that I work it's not possible to have this dependency, this dependency also shouldn't be moved to devDependencies??

**Comment by matthewp** [comment]
It's not a devDependency, why does your work not allow this? Firewall?  I suppose we could publish this.

**Comment by sergiomcunha** [comment]
It's because of a firewall, if you can publish would be nice. 
But it isn't a production dependency, from my point of view. Anyway this dependency can be avoided or published?
Thanks

**Comment by matthewp** [comment]
Yes, it's production it, it's how we produce source-maps for bundles.

**Comment by matthewp** [comment]
I'm going to publish it, have to fix some unrelated test errors first.

**Comment by matthewp** [comment]
Getting something else in master, then will do a release.

**Comment by pYr0x** [comment]
@matthewp we should also patch the major branch. some user get also an error with steal-tools 1.0 beta
https://github.com/stealjs/steal-tools/issues/502

**Comment by shcarrico** [comment]
👍

**Comment by matthewp** [comment]
will do

**Comment by matthewp** [comment]
I released v0.16.6 and  v1.0.0-beta.2 which has this fixed.
