### ISSUE TITLE
Sadnboxed build is failing due to hard dependency on github.com hosted repo

### ISSUE THREAD

**Issue by Jaygiri** [stealjs/steal-tools#502]
Sandboxed Jenkins build is failing to fetch https://github.com/stealjs/source-map/archive/0.4.2-bitovi.1.tar.gz which is dependency for steal-tools version v1.0.0-pre.1

is it possible to change "source-map": "https://github.com/stealjs/source-map/archive/0.4.2-bitovi.1.tar.gz" back to "bitovi-source-map": "0.4.2-bitovi.2"?

**Comment by matthewp** [comment]
I released v1.0.0-beta.2 which uses bitovi-source-map.
