### ISSUE TITLE
Specifying System.bundle with wildcards does not work with package.json during the build process...

### ISSUE THREAD

**Issue by georgesunil81** [stealjs/steal-tools#507]
I have some pages and modals in my CanJS application that dynamically get loaded using System.import

**I have the System.bundle specified as below in my package.json -**

```
"system": {
"bundle": [
      "my-app/my-pages/**/*",
      "my-app/my-modals/**/*"
]``
```

**I then run the build process (node build.js), it gives me these errors -**

 Error: Error loading `"my-app/my-pages/**/*"`. ENOENT: no such file or directory.

**Below is my build.js -**

```
var stealTools = require("steal-tools");

stealTools.build({
  config: __dirname + "/package.json!npm",
  bundlesPath: "dist/bundles/my-app"
}, {
  bundleAssets: true
});
```

It currently builds fine if I list each bundle individually within System.bundle, but I run the risk of forgetting to add to it if I add some more pages or modals to my application! We'd like the ability to specify asterisks within the System.bundle so that it reads those in dynamically during the build process.

**Comment by frank-dspeed** [comment]
@matthewp  this can be closed
