### ISSUE TITLE
dest option doesn’t seem to work with eachModule

### ISSUE THREAD

**Issue by chasenlehara** [stealjs/steal-tools#513]
Steps to reproduce:
1. `git clone https://github.com/chasenlehara/steal-each-module-dest-function.git`
2. `cd steal-each-module-dest-function`
3. `npm install`
4. `donejs build`

Expected results: build succeeds with no errors and produces two built files, one for each module

Actual results: build fails with error: `Potentially unhandled rejection [1] TypeError: Path must be a string. Received [Function]`

Additional notes: if you comment out the `dest` config in `build.js`, the build succeeds but only produces one file at `dist/global/steal-each-module-dest-function.js` with the second module

**Comment by matthewp** [comment]
Looking at this soon.

**Comment by matthewp** [comment]
Problem is with `dest`, not eachModules.

**Comment by matthewp** [comment]
Fixed in 0.16.7
