### ISSUE TITLE
Live-reload only happening once.

### ISSUE THREAD

**Issue by marshallswain** [stealjs/steal-tools#515]
@matthewp any ideas on what would cause live-reload to only happen once?  It works great the first time, but then on subsequent changes, the server-client socket message goes through, but nothing updates.  I made a test repo to troubleshoot.  

https://github.com/icanjs/steal-can3-feathers

I've disabled the component from loading, so all you should see is the header: "Example steal-can-feathers app"

**Comment by matthewp** [comment]
Not sure but I'll try to take a look on monday.  Thanks for the test repo.

**Comment by matthewp** [comment]
@marshallswain This project doesn't start for me because it is missing a dependency on done-serve. Can you fix that?

**Comment by marshallswain** [comment]
@matthewp, I added done-serve and live reload works, but only when using done-serve.  If I use `steal-tools live-reload` the bug happens where it only runs once (usually, it's sporadic and sometimes will run more than once).  I just tried this same thing with @BigAB's can-react-example and ran into the same bug.  Using done-serve without SSR fixed the problem.

**Comment by marshallswain** [comment]
Anyway, I updated the example repo, so you can try it out.  I also added a Feathers server so you can open the `server` folder first, `npm i` and `npm start` then run the main app.  Try once by running `npm run develop` and it will work.  Try using `http-server` and opening a separate tab and running `steal-tools live-reload` and it be buggy.

**Comment by matthewp** [comment]
Maybe time has fixed this?  I was able to get it to work after upgrading to all of the latest can releases. Let me know if you experience this again though.

![sess](https://cloud.githubusercontent.com/assets/361671/19742186/d274d7b2-9b91-11e6-8ae9-ef7ae88801f8.gif)
