### ISSUE TITLE
cant find any of the files when installing Babylon

### ISSUE THREAD

**Issue by devmondo** [stealjs/steal-tools#518]
`npm install babylon --save`

in code

`import {parse} from 'babylon';`

i get below errors wither with latest RC or current stable branch, also happens with `babel-generator`  and `babel-runtime/regenerator`.

sorry for below error format but i dont know how to format it here :(
thx in advanced.

```
steal.js:2648 GET http://localhost:9090/node_modules/babylon/lib/parser.js 404 (Not Found)fetchTextFromURL @ steal.js:2648(anonymous function) @ steal.js:2823init @ steal.js:377Promise @ steal.js:365value @ steal.js:2822loader.fetch @ steal.js:3637loader.fetch @ steal.js:4705loader.fetch @ steal.js:4805System.fetch @ npm-extension.js:274(anonymous function) @ steal.js:1525tryCatchReject @ steal.js:1183runContinuation1 @ steal.js:1142Fulfilled.when @ steal.js:930Pending.run @ steal.js:821Scheduler._drain @ steal.js:97Scheduler.drain @ steal.js:62run @ steal.js:268
steal.js:2648 GET http://localhost:9090/node_modules/babylon/lib/tokenizer.js 404 (Not Found)fetchTextFromURL @ steal.js:2648(anonymous function) @ steal.js:2823init @ steal.js:377Promise @ steal.js:365value @ steal.js:2822loader.fetch @ steal.js:3637loader.fetch @ steal.js:4705loader.fetch @ steal.js:4805System.fetch @ npm-extension.js:274(anonymous function) @ steal.js:1525tryCatchReject @ steal.js:1183runContinuation1 @ steal.js:1142Fulfilled.when @ steal.js:930Pending.run @ steal.js:821Scheduler._drain @ steal.js:97Scheduler.drain @ steal.js:62run @ steal.js:268
steal.js:2648 GET http://localhost:9090/node_modules/babylon/lib/plugins/jsx.js 404 (Not Found)```

**Comment by matthewp** [comment]
You might get 404s in development mode as it tries to implement the node_modules algorithm. In this case lib/parser.js doesn't exist so it should retry with lib/parser/index.js and find it.  These 404s are unavoidable in the browser unfortunately.

**Comment by devmondo** [comment]
thanks for reply,

this means i cant use those libs in browser ? if this is the case this is show breaker for the project :( 

in JSPM it works, but i moved from JSPM to steal because of performance.

how to enable production mode ? also is there solution like mapping or something

**Comment by matthewp** [comment]
I don't know if it can or not, the existence of 404s doesn't mean it failed to load.  This is a JavaScript parser by the way, you want to load this in the browser? Just making sure.

Yes, you can do mapping. If this project provides a build for the browser then that's a good option to take.  See if there is a global build in the npm package.

**Comment by devmondo** [comment]
thanks again,

here is the project i want to use
https://github.com/babel/babel/tree/master/packages/babel-generator

basically creating runtime modules by parsing user code

unfortunately this lib does not provide global build :(

also if i recall this issue happened with me with other libs
https://github.com/ternjs/acorn
http://ternjs.net/

sorry to sound pushing, but again it works with JSPM, and i dont want to go back to it, steal is awesome and uses NPM directly, and there are many libs like this and i want to make the whole company adapt Steal.

**Comment by matthewp** [comment]
It works for me in 1.0 and 0.16:

![screen shot 2016-08-30 at 4 12 56 pm](https://cloud.githubusercontent.com/assets/361671/18105231/a618dc96-6ecc-11e6-8830-661d9c018530.png)


I'm able to get `babylon`.  You do go 404s, but notice the warning; even though there are a few 404s it still was able to load the module.

**Comment by devmondo** [comment]
```
import generate from 'babel-generator';

const code = 'class Example {}';
const ast = parse(code);
console.log(ast);
```
below is the error, can you try the code above please and see if it works on your end, so i wont be doing something stupid and wasting your time. 

![image](https://cloud.githubusercontent.com/assets/1266367/18105676/5940dd8e-6f11-11e6-999c-0457a231651e.png)

**Comment by pYr0x** [comment]
can you provide a sample app. we will have a look

**Comment by devmondo** [comment]
sure man 
where should i post it please?

**Comment by pYr0x** [comment]
make your own repository

**Comment by devmondo** [comment]
sorry that was stupid question, specially when you slept only 3 hours :)

here is the repo
https://github.com/devmondo/steal-test

i have added bunch of libs that are causing similar issues

 to run it use **npm run dev** 

thanks again for the help

**Comment by matthewp** [comment]
They might have different problems so that doesn't clear so much up.  These are all libraries not intended to be loaded in the browser so there's not much surprise that they don't. JSPM does preprocessor to make NPM modules more browser friendly. Anyways, all issues are welcome, can we move this one to stealjs/steal where it belongs though?

**Comment by devmondo** [comment]
sure, move it man. hope this helps solving.
