### ISSUE TITLE
Bootstrap and building

### ISSUE THREAD

**Issue by MarcGodard** [stealjs/steal-tools#525]
When I build my project, and it contains bootstrap (getbootstrap.com) it removes important lines from bootstrap's less files.

This is the code:

![screen shot 2016-09-12 at 12 14 09 pm](https://cloud.githubusercontent.com/assets/5016637/18443353/8fc0e73e-78e2-11e6-82b8-dd68404fd95f.png)

This is in my browser before the build:

![screen shot 2016-09-12 at 12 17 36 pm](https://cloud.githubusercontent.com/assets/5016637/18443448/f9bf385c-78e2-11e6-9e3e-a00ff2085764.png)

This is in my browser after the build:

![screen shot 2016-09-12 at 12 16 25 pm](https://cloud.githubusercontent.com/assets/5016637/18443410/c3085fd2-78e2-11e6-9c4f-45f13c0dcbe8.png)

Bootstrap duplicates the transition because it knows Chrome doesn't do the 2nd one and will ignore it. As you can see the error. However, the build tools removes the duplication (which generally makes sense), however in this situation and many others it doesn't.

I duplicate many things in my css on purpose to account for older browsers. Keeping the last version would cause problems for older browsers. Is there a way around this problem?

**Comment by matthewp** [comment]
I would guess this happens during minification.  Check out the cleanCSSOptions as documented here: http://stealjs.com/docs/steal-tools.BuildOptions.html and see if that fixes it for you.

**Comment by MarcGodard** [comment]
@matthewp Thanks, I found an option in the clean-css documentation that would do it. Just not sure how to set that option. However, turning off minify worked.

Do you know how to add the clean-css options?

**Comment by pYr0x** [comment]
how about:

```
"cleanCSSOptions": {
    "advanced": false
}
```

**Comment by MarcGodard** [comment]
@pYr0x Thanks, that worked. I only tried "skip-advanced": false

If you found this in the docs, I am sorry, my mind isn't all here lately. My grandmother died a few days ago and my son is teething... so I haven't been sleeping.

Thanks again.
