### ISSUE TITLE
Live reload doesn't seem to be working

### ISSUE THREAD

**Issue by justinbmeyer** [stealjs/steal-tools#526]
Example app: https://github.com/justinbmeyer/live-reload-example

Following the script in the readme.md, the `live-reload` server actually reports changes:

```
Reloading index
Reloading index
Reloading index
Reloading index
```

But nothing happens.

**Comment by justinbmeyer** [comment]
cc @pYr0x

**Comment by justinbmeyer** [comment]
If I change the `<script>` tag to:

```
<script src="./node_modules/steal/steal.js" main="live-reload-example"></script>
```

I see

```
Reloading live-reload-example@1.0.0#index
```

In the terminal but no changes.

**Comment by justinbmeyer** [comment]
If I put a console.log in `index.js`, it reports every time I change the file.  But the same thing is logged. For example, my index.js might change from:

```js
console.log("running index.js")
document.getElementById("app").innerHTML = "Change This Please"
```

to

```js
console.log("running index.js !!!!!")
document.getElementById("app").innerHTML = "Change This Please"
```

When I save the file, another `running index.js` is printed.

**Comment by matthewp** [comment]
Works fine for me.

![testing](https://cloud.githubusercontent.com/assets/361671/18735504/4b9efa70-804c-11e6-97cd-6d13afaaf164.gif)

**Comment by matthewp** [comment]
Node and browser versions?

**Comment by justinbmeyer** [comment]
which version of node? I'm `v5.10.1`

**Comment by justinbmeyer** [comment]
Chrome `53.0.2785.116`

**Comment by matthewp** [comment]
My guess is that's it's the OS version.  Getting file watchers to work on every OS is very tricky, see [here](https://github.com/paulmillr/chokidar#how) for a little bit of background.  I probably need to spend some time trying with different OS versions to figure out how to make it work everywhere.

**Comment by justinbmeyer** [comment]
It's identifying the change, and calling `reload(moduleName);` in StealJS.  I think it's a steal problem (not steal-tools)

**Comment by justinbmeyer** [comment]
seems like chrome is doing very aggressive caching.  @matthewp and @pYr0x are you hosing with `http-server`?

**Comment by matthewp** [comment]
I doubt it, if it were a client-side problem I'd most likely be seeing the problem, browsers are more cross-platform. Check your Network tab and see if you are getting the newest version of the source.

My guess is that the change event is firing too quickly in the watcher and sending you the version of the file before it changed.

**Comment by matthewp** [comment]
I turn off browser caching when developing.

**Comment by justinbmeyer** [comment]
@matthewp I'll change it 20 times and it never picks up the new code.  I have browser caching turned off too.

**Comment by matthewp** [comment]
In the Network tab are you getting the new version?

**Comment by justinbmeyer** [comment]
There's nothing in the network tab.  Running through the debugger, I can see the XHR call be made, and the response is always the same.  Very odd.  I hope this isn't what Julian is facing.

**Comment by justinbmeyer** [comment]
`http-server` doesn't look like it's being hit.

**Comment by justinbmeyer** [comment]
It's fixed if I add some cache busting:

```
fetchTextFromURL = function(url, fulfill, reject) {
	  url = url + "?"+Math.random();
```

Very strange.  @pYr0x if you are seeing what I'm seeing, maybe sneak that in until we can figure out what the heck is wrong w/ Chrome.

**Comment by justinbmeyer** [comment]
```js
fetchTextFromURL = function(url, fulfill, reject) {
      var xhr = new XMLHttpRequest();
      var sameDomain = true;
      var doTimeout = false;
      if (!('withCredentials' in xhr)) {
        // check if same domain
        var domainCheck = /^(\w+:)?\/\/([^\/]+)/.exec(url);
        if (domainCheck) {
          sameDomain = domainCheck[2] === window.location.host;
          if (domainCheck[1])
            sameDomain &= domainCheck[1] === window.location.protocol;
        }
      }
      if (!sameDomain && typeof XDomainRequest != 'undefined') {
        xhr = new XDomainRequest();
        xhr.onload = load;
        xhr.onerror = error;
        xhr.ontimeout = error;
        xhr.onprogress = function() {};
        xhr.timeout = 0;
        doTimeout = true;
      }
      function load() {
        fulfill(xhr.responseText);
      }
      function error() {
        reject(xhr.statusText + ': ' + url || 'XHR error');
      }

      xhr.onreadystatechange = function () {
        if (xhr.readyState === 4) {
          if (xhr.status === 200 || (xhr.status == 0 && xhr.responseText)) {
            load();
          } else {
            error();
          }
        }
      };
      xhr.open("GET", url, true);

      if (doTimeout)
        setTimeout(function() {
          xhr.send();
        }, 0);

      xhr.send(null);
    }
```

If I run that over and over again with:

```
fetchTextFromURL("http://localhost:8080/live-reload-example/index.js", function(text){ console.log(text) })
```

No network traffic is made.  Crazy.

**Comment by justinbmeyer** [comment]
Ok, fixed with starting `http-server` to prevent caching like:

```
http-server -c-1
```

Need to update that StealJS training.

**Comment by marshallswain** [comment]
This is probably the exact same problem I reported a few days ago: https://github.com/stealjs/steal-tools/issues/515
