### ISSUE TITLE
Create a fully-configured steal.production.js in the dest folder

### ISSUE THREAD

**Issue by matthewp** [stealjs/steal-tools#531]
``` js
stealTools.build({}, {
  dest: __dirname + '/build'
})
```

This should right out:

```
build/steal.production.js
build/bundles/app/main.js
build/bundles/app/other.js
```

Where the `steal.production.js` is fully configured with the `main`, and everything else necessary so that you only need to do:

``` html
<script src="/build/steal.production.js"></script>
```

**Comment by matthewp** [comment]
dist/bundles

```js
stealTools.build({
  bundlesPath: __dirname + "/some/other/path"
});
```

```html
<script src="node_modules/steal/steal.production.js" bundles-path="some/other/path"></script>
```

```js
dist/steal.production.js
```

**Comment by justinbmeyer** [comment]
One potential issue ... Multiple builds overwriting steal.production.js. Yes, people should use he multi build ... But what if they don't?

**Comment by matthewp** [comment]
The user can control that with different dests:

```js
stealTools.build({
  main: "app/a"
}, {
  dest: __dirname + '/dist/appA'
});

stealTools.build({
  main: "app/b"
}, {
  dest: __dirname + '/dist/appB'
});
```

A build should "own" a dest folder, I think.

**Comment by frank-dspeed** [comment]
It would be also nice to know what happens and if it could be addressed:

```
All Boundles Include steal it self i mean what happens if steal gets loaded more then once does it attach to the same dom object overwrites it existing when steal gets loaded from many dependencys on same page?
<script src"boundle1.js" />
<script src"boundle2.js" />
<script src"boundle3.js" />
```

**Comment by matthewp** [comment]
Steal doesn't do self contained scripts like that. Maybe a good idea, create a new issue for that?

**Comment by matthewp** [comment]
One problem here is that when adding the main in the configuration we get the fully normalized main. We can do some denormalization to change `foo@1.0.0#main` to `foo/main` have to think about other cases.

* [ ] - mains with plugins.  I believe we transform `foo@1.0.0#main!plugin` to just `foo/main`, need to verify this.

**Comment by frank-dspeed** [comment]
ya i agree it maybe all makes it complex but its worth the effort :) its the hunt !
Some Motivation: https://www.youtube.com/watch?v=uTTO6D7ng3s

**Comment by matthewp** [comment]
Closed by https://github.com/stealjs/steal-tools/pull/549
