### ISSUE TITLE
Shorten the stealTools.build signature

### ISSUE THREAD

**Issue by matthewp** [stealjs/steal-tools#532]
The second argument makes it a bit awkward.  When https://github.com/stealjs/steal/issues/764 is fixed you'll be able to do:

``` js
stealTools.build({}, {
  minify: false
});
```

Which is a little weird, the most important options are in the second argument (since the first is optional).  

I think we can shorten that to just:

``` js
stealTools.build({
  minify: false
});
```

If only 1 argument is provided we'll check for a `steal` property, and if that exists we can safely assume that is the steal (previously system) config.

``` js
stealTools.build({
  steal: {
    config: __dirname + "/path/to/root/package.json!npm"
  },

  minify: false,
  dest: __dirname + "/build"
});
```

The 2 argument signature will remain for legacy reasons, but will be deprecated and docs will be updated to show the single argument form.

**Comment by justinbmeyer** [comment]
I sorta like the 2 argument because it aligns to typed objects used through the codebase. 

I suppose there's still 2 objects, just one can contain the other.

**Comment by matthewp** [comment]
This would bring it in align with `stealTools.export` which already works this way:

```js
stealTools.export({
  system: {
    config: __dirname + "/package.json
  }
})
```

**Comment by matthewp** [comment]
Turns out I can't do this and maintain backwards compatibility. There's no way to distinguish these two forms:

```js
stealTools.build({
  config: __dirname + "/package.json!npm"
});
```

And with config defaults:

```js
stealTools.build({
  minify: false
});
```

Because I can't infer config from buildoptions when there is only a single argument provided, the only way to provide this shorter form would be by making the inner `steal: {}` the *only* way to provide config.

I thought about that, and maybe in the future we'll do it. But I don't think it's an important enough change to warrant a breaking change, at least for 1.0. Perhaps in 2.0, I think we can wait and see if people even need to use the config option any more.
