### ISSUE TITLE
Proposal: steal-export standalone bundle configuration option.

### ISSUE THREAD

**Issue by frank-dspeed** [stealjs/steal-tools#538]
We will add some extra options for the standalone method of steal-tools.export

Current export standalone produces a single.js file with all in it as define.

with the new options we can now tell it

```
{
   canSingle: true,
   componentsSingle: true,
   copyFiles:true
}
```

we can produce a result like:

```
dist/components/comp1.js
dist/components/comp2.js
dist/components/comp3.js
dist/vendor/steal-stache
dist/vendor/can-component
dist/vendor/can-control
```

So this scripts can be added to any html via script tags

the copy files options would copy the stache templates and css files also so its like a build we could mabe later add this to build also and generate a extra html snippet for loading that also but i think all that goes much much to far

**Comment by frank-dspeed** [comment]
#516

**Comment by frank-dspeed** [comment]
https://github.com/stealjs/steal-tools/pull/512

**Comment by frank-dspeed** [comment]
got a depgraph ? https://github.com/stealjs/steal-tools/issues/446

**Comment by matthewp** [comment]
`+standalone` is supposed to be standalone, hence its name :)  You can kind of already do this with `+global-js`, but I think that doesn't create separate exports for your dependencies. If the goal is split all dependencies into their own scripts, I think that can be done with a new helper (I'm not sure what you should call it though).

**Comment by frank-dspeed** [comment]
We can close this this is not do able without Refactoring will refactor steal tools complet and will let steal work as it works.

**Comment by frank-dspeed** [comment]
i will make a new project called: steal-tools-plus that will simply inhire the original steal tools and add some extra stuff like export as production html or wordpress and joomla plugin 

i also created generator-steal wich will configure build.js for steal-tools and steal-tools-plus

**Comment by matthewp** [comment]
I don't think this would require much of a refactor, but if you'd prefer to fork that's cool too.
