### ISSUE TITLE
Proposal: Switch Commander Usage Style to git subcommands

### ISSUE THREAD

**Issue by frank-dspeed** [stealjs/steal-tools#543]
var path = require("path");
var cmdBuild = require("../lib/cli/cmd_build");
var cmdExport = require("../lib/cli/cmd_export");
var cmdTransform = require("../lib/cli/cmd_transform");
var cmdLiveReload = require("../lib/cli/cmd_live_reload");

is what you do at present commander supports this nice feature we could put all into /bin and name them
```
steal
steal-build
steal-export
steal-transform
```

that would allow faster adoption and editing the steal tools it self.
as also it would give steal addons the option to be named steal-addonName

so the whole steal eco system is nice compose able and use able because we can simply look for other existings steal-* bins

**Comment by matthewp** [comment]
How does this work, does commander automatically detect these files or something? I'm fine with it as long as its backwards compatible (meaning `steal-tools` and `steal-tools build` and `steal-tools export`, etc. all still work the same way they currently do).

**Comment by frank-dspeed** [comment]
ya it detects the files automaticly its pointed out in the documentation i prepare a pull request all will still stay same but i am able to hook in more easy and maybe you will love the new structure as much as me because its more how should i say lovely :dagger:

**Comment by matthewp** [comment]
Ok, if you do a pull-request, branch off of `major` and not `master`, that's the 1.0 branch. Make PRs against `major`.

**Comment by matthewp** [comment]
We use yargs and they are done as subcommands now: https://github.com/stealjs/steal-tools/blob/886040c60f6c343c452c3c74446322abf0da4028/bin/steal#L9-L14
