### ISSUE TITLE
Proposal: Make Standalone Self Contained Bundles

### ISSUE THREAD

**Issue by frank-dspeed** [stealjs/steal-tools#545]
It would be also nice to know what happens and if it could be addressed:

All Boundles Include steal it self i mean what happens if steal gets loaded more then once does it attach to the same dom object overwrites it existing when steal gets loaded from many dependencys on same page?

to make more sense i talk about self containing bundled apps that are place able on pages like widgets

and sure i talk about wrapping up some things like bit-tabs and that and components. so that they get build and can be deployed and composed on a html page. with only using html code.

so the distribution of web components.

<html>
<head>
<script src"boundle1.js" />
<script src"boundle2.js" />
<script src"boundle3.js" />
</head>
<body>
<h2>First</h2>
<script src"app1.js" />
<h2>Secund</h2>
<script src"app2.js" />
</body>

**Comment by matthewp** [comment]
Probably loading Steal twice would cause some problems currently as it is a global.  It's also rather large (a known issue I plan on working on soon) so you wouldn't want to do so anyways.  But assuming that could be fixed this would be doable.

**Comment by frank-dspeed** [comment]
ya need to watch into this than it was planned because on my roadmap is to have web components that i can use all over in all my projects thats probally what you whant too

**Comment by matthewp** [comment]
This will happen as part of https://github.com/stealjs/rfcs/pull/5
