### ISSUE TITLE
Proposal: Make Steal Loadable More then Once GlobalSteal Load Only

### ISSUE THREAD

**Issue by frank-dspeed** [stealjs/steal-tools#546]
Lets chat short here or better gitter if you got time about the global that steal is at present i think i can solve it more fast with some answers from you then examing whole code at present
i think we only need to change the first parts of https://github.com/stealjs/steal/blob/master/steal.js so that it checks if there is a stealLoading que and then we set a global steal loading que if not set if is set apply to that
it should be that simple don't you think so?

I think we should be easy able to refactor steal so that it is more splitted up into a processing list and a processor and then we can look if processing list and processor exist and only add the values to them
what do you think=?

**Comment by matthewp** [comment]
Sorry, I don't understand what it is that you would like to see?

**Comment by frank-dspeed** [comment]
@matthewp i think this can be closed as this is not a normal usecase.
