### ISSUE TITLE
Why? is   live-reload  Start a live-reload Web Socket server

### ISSUE THREAD

**Issue by frank-dspeed** [stealjs/steal-tools#547]
why is that in the package here?   live-reload  Start a live-reload Web Socket server
? wouldn't that more belong to donejs and done-serve or anything like that?

if you like i got a nice preloading webserver we could call it steal-server we could integrate all the serving parts into steal-server and offer steal-server also as middelware. then its all in one Project nice and maintainbale.

**Comment by matthewp** [comment]
Yeah, I agree. Not sure what exactly it would be called. Nevertheless, there is already an issue in https://github.com/stealjs/steal-tools/issues/446 for this, so closing.

This might happen sooner-than-later b/c we would like to remove the native dependency in steal-tools (to launch a websocket server native code is needed).

**Comment by frank-dspeed** [comment]
So do you wanna open maybe a new repo here under stealjs and call it steal-server i push code to it :) i have something nice read to be renamed to steal-server

**Comment by matthewp** [comment]
I don't know what the name should be, I would probably include `live-reload` in the name somehow b/c it's specifically for that purpose. We had talked about having a steal dev server so might reserve `steal-server` for that.

If you have something already ready, can you add a link here so I can take a look?

**Comment by frank-dspeed** [comment]
ok i tell you what it will be it will bundle steal-tools done-ssr done-serve + harp + updates

**Comment by frank-dspeed** [comment]
It will be able to prerender donejs, less, scss all this stuff and also be able to cache the results to file so think about it like a ondemand build first load is developer mode secund production 

```

DIREKTSPEED Server is a static web server that also serves doT Jade, Markdown, EJS, Less, Stylus, Sass, and CoffeeScript as HTML, CSS, and JavaScript without any configuration. It supports the beloved layout/partial paradigm and it has flexible metadata and global objects for traversing the file system and injecting custom data into templates. Optionally, DIREKTSPEED Server - Module PreRender can also compile your project down to static assets for hosting behind any valid HTTP server.

Why?
Pre-compilers are becoming extremely powerful and shipping front-ends as static assets has many upsides. It's simple, it's easy to maintain, it's low risk, easy to scale, and requires low cognitive overhead. I wanted a lightweight web server that was powerful enough for me to abandon web frameworks for dead simple front-end publishing.

Features
easy installation, easy to use
fast and lightweight
robust (clean urls, intelligent path redirects)
built in pre-processing
first-class layout and partial support
built in LRU caching in production mode
can export assets to HTML/CSS/JS
does not require a build steps or grunt task
fun to use
```

**Comment by frank-dspeed** [comment]
Think about it as a filesystem traversing autoconfigurating steal ;) so you put your project in and it simply works

**Comment by matthewp** [comment]
I'm not ready to put any bandwidth into such a project, I had a similar idea awhile back, but feel free to experiment if you want.

**Comment by pYr0x** [comment]
@frank-dspeed do you have any example? that we can look into?
