### ISSUE TITLE
possible build bug with steal-stache

### ISSUE THREAD

**Issue by justinbmeyer** [stealjs/steal-tools#556]
To reproduce:

1. Get this pull request: https://github.com/canjs/bit-docs-html-canjs/pull/190
2.  Remove _make-example.js_ `steal-stache` as a dependency from `dependencies` and move it into _package.json_ as a dependency.
3.  Change _static/search.js_'s `var searchResultsRenderer = require("./templates/search-results.stache!");` to `var searchResultsRenderer = require("./templates/search-results.stache!steal-stache");`.
4.  Run `node ./make-example.js -f`.

Notice that _node_modules/bit-docs-generate-html/site/static/build/XXX/build.html_ is able to load without a build-time error.

**Comment by matthewp** [comment]
We now have the `plugins` configuration, so you would add steal-stache to that.
