### ISSUE TITLE
Remove development code of configDependency module

### ISSUE THREAD

**Issue by m-mujica** [stealjs/steal-tools#562]
`//!steal-remove-{start,end}` doesn't seem to work on config dependencies, debugging a little bit it seems the reason is the configDependency is not part of the [dependency graph passed to `stream/transpile`](https://github.com/stealjs/steal-tools/blob/f93a359739a213d51bd3cfdd8d183f8b295dd34a/lib/stream/transpile.js#L38), is this something we can fix/workaround?

**Comment by matthewp** [comment]
Can you file an issue for that? steal-remove-start/stop should work for all modules.

**Comment by m-mujica** [comment]
which repo? I thought creating this issue was enough :D should I rename it then?

**Comment by matthewp** [comment]
Oh, sorry, I thought this wasn't steal-tools :)
