### ISSUE TITLE
steal-less as an external dependency doesn't correctly build

### ISSUE THREAD

**Issue by xedoken** [stealjs/steal-tools#565]
I use donejs latest rc, steal and steal-tools latest 1.0 rc.

build.js is default with bundleAssets and bundleSteal.

```
var stealTools = require("steal-tools");

var buildPromise = stealTools.build({
   config: __dirname + "/package.json!npm"
}, {
   bundleAssets: {
     infer: true,
     glob: [
       "src/libs"
     ]
   },
   bundleSteal: true
});
```

So i run donejs build as bundle, trying to load in a local html project it fails because of steal-less or less engine. If i change my build.js for export to global or standalone result is the same.

Am i need to change my build.js for deps like steal-less or include less engine somehow? Need this ti be fixed or explained how can i build/export my donejs app with steal-less. thank you.

**Comment by pYr0x** [comment]
can you add into your main.js the steal-less as a static import like

```
import "steal-less";
```

before all your other imports

**Comment by xedoken** [comment]
I tried but that not help. still got the error.

**Comment by matthewp** [comment]
I'll create an example project.

**Comment by matthewp** [comment]
I'm seeing a possible build bug, looking into it now.

**Comment by matthewp** [comment]
@xedoken There is a bug related to steal-css' configuration not being applied in production. I'm working on that bug.

In the meantime this project works: https://gist.github.com/matthewp/e36dc5b6d50776270d8c027a4021c6be

Notice in the package.json how there is the config:

```
"steal": {
    "ext": {
      "css": "steal-css"
    }
  }
```

This is a workaround for the bug you've encountered.  Will keep you posted on the bug.

**Comment by xedoken** [comment]
Wow! that's what i'm searching for! Thank you guys! i'll try that steal ext option in package.json in my app. Thank you very much! 👍

**Comment by matthewp** [comment]
This is the underlying bug: https://github.com/stealjs/steal-npm/issues/200 Working on it now.  Going to close this as I don't think anything else is needed here, but can continue to discuss if you want.

**Comment by xedoken** [comment]
Yeah, i add code from your instructions and another failure. right now it b/c of this error

```
OPENING: /Users/<name>/Projects/javascript/<project name>/package.json!npm
Potentially unhandled rejection [11] Error: Error loading "<project name>@0.1.0#index.stache!done-autorender@0.9.0-pre.1#autorender" at file:/Users/<name>/Projects/javascript/<folder  name>/index.stache
Error loading "done-autorender@0.9.0-pre.1#autorender/index" at file:/Users/<name>/Projects/javascript/<folder  name>/node_modules/done-autorender/src/autorender/index.js
ENOENT: no such file or directory, open '/Users/<name>/Projects/javascript/<folder  name>/node_modules/done-autorender/src/autorender/index/index.js'
    at Error (native) 
```

smth is about done-autorender right now, am i right?

btw my main in package.json is
`"main": "<project name>/index.stache!done-autorender"`

**Comment by matthewp** [comment]
It looks like you're using a prerelease version of DoneJS. That code is very dated and hasn't been updated to work with the latest stuff (maybe you are wanting to use CanJS 3.0). I'd post an issue in https://github.com/donejs/donejs/issues, maybe someone can help you there.

**Comment by xedoken** [comment]
yeah, i use donejs latest rc. I want canjs 3.0 packages instead of global can package. Thank you Matthew!
