### ISSUE TITLE
StealJS 1.0 build fails, can't find node_module jquery

### ISSUE THREAD

**Issue by roemhildtg** [stealjs/steal-tools#577]
I have a project that doesn't use jquery directly, jquery is not listed as a dependency in package.json. But a couple dependencies uses jQuery and do have jquery in their package.json dependencies. 

Steal-tools@0.16 seems to build the project without complaining, but the latest release will not. 
```
gre@linux-zxlu:~/public_html/geocola> node build
OPENING: /home/gre/public_html/geocola/package.json!npm
OPENING: config/default
Potentially unhandled rejection [5] Error: Error loading "jquery" at file:/home/gre/public_html/geocola/jquery.js
Error loading "jquery" from "config/default" at file:/home/gre/public_html/geocola/config/default.js
ENOENT: no such file or directory, open '/home/gre/public_html/geocola/jquery.js'
    at Error (native)
```

Here's the projects package.json: 
http://pastebin.com/QfdqxHNw

Here's my build script: 
```javascript
var stealTools = require('steal-tools');
var path = require('path');

try {
    stealTools.build({
        config: path.join(__dirname, 'package.json!npm')
    }, {
        bundleAssets: true,
        sourceMaps: true
    });

} catch (e) {
    console.log(e.getStack());
}
```

**Comment by pYr0x** [comment]
what is in `config/default` does it require jquery?

**Comment by matthewp** [comment]
Need some more info to help. Can you add a minimal reproducing example?

**Comment by roemhildtg** [comment]
@matthewp I don't have a minimal example yet, I've been trying to work on a minimal example, I'll get that to you when I'm able to. 

@pYr0x `config/default` doesn't require jquery directly. It does require a module from another package that requires jquery though.

**Comment by matthewp** [comment]
Ok, going to close for now. You can probably create an example simply by creating a project with only this dependency (and nothing else) and then requiring it like `require('some-dep');`.  I can take a look if you'll provide this.
