### ISSUE TITLE
what to do with multimain and dist/steal.production.js

### ISSUE THREAD

**Issue by pYr0x** [stealjs/steal-tools#581]
if make a multimain build the `dist/steal.production.js` contains the first item of the `main` array
```
var buildPromise = stealTools.build({
	main: ["cms/index", "cms/app"],
	config: __dirname + "/package.json!npm"
}, {
	bundleAssets: true,
	minify: false
});
```
should we remove the pre configured `steal.main` in the steal production file if we have a multimain build?

**Comment by matthewp** [comment]
With multi-main you would override the main in the script tag, no?

**Comment by matthewp** [comment]
Going to close this one, we can reopen if you still want to discuss it though.
