### ISSUE TITLE
Build is missing modules

### ISSUE THREAD

**Issue by roemhildtg** [stealjs/steal-tools#585]
I've been trying to start bundling a project but am running into issues where modules are missing from the bundles that require them. StealJS then tries to import the module as a separate file which fails. 

I've created a simple project to demonstrate the issue, but its not clear to me what is causing the problem. The required modules are listed in their module dependencies, but the `System.bundles` that steal-tools outputs does not have the module listed. 

One example is can-fixture

https://github.com/roemhildtg/steal-build-problem

**Comment by matthewp** [comment]
Thanks, i'll take a look.

**Comment by matthewp** [comment]
What modules are missing? I just cloned and built and it seems to have worked:

<img width="841" alt="screen shot 2017-01-17 at 11 38 52 am" src="https://cloud.githubusercontent.com/assets/361671/22029772/8c69aa64-dca9-11e6-9623-5b4eb4438e22.png">

Are you using it this way in your html:

```html
<script src="./docs/spectre/steal.production.js"></script>
```

This is how I would recommend as it doesn't require any configuration on your part.

**Comment by roemhildtg** [comment]
can-fixture is missing from the bundle. Try this:
```html
<script src="./docs/spectre/steal.production.js">
  steal.import('spectre-canjs/test');
</script>
```

**Comment by matthewp** [comment]
Ok, couple of things here. First, can-fixture is not a dependency in the package.json, so even in dev this fails.

Secondly, it looks like this is a problem with the way that we trace dependencies.  It might be related to this bug: https://github.com/stealjs/system-trace/issues/21

Filed this one just in case it's different: https://github.com/stealjs/system-trace/issues/23

Will try to get to these this week. In the meantime if you remove those comments and add can-fixture as a dependency it should serve as a workaround.

**Comment by matthewp** [comment]
Closing this as https://github.com/stealjs/system-trace/issues/23 is the root problem here.  Thanks for finding this though!

**Comment by roemhildtg** [comment]
Okay, thanks! Yep, the comments were causing the problem, I removed them in my other project and the files are no longer missing.
