### ISSUE TITLE
HTML Build Type

### ISSUE THREAD

**Issue by matthewp** [stealjs/steal-tools#586]
steal-tools supports 2 build types currently, js and css. The css build type is marked by steal-css so that its resources get packed together into css bundles. 

I would like to do the same thing for HTML, so that a plugin for loading HTML could mark its resources as the `html` build type and steal-tools would therefore create separate HTML bundles.

**Comment by justinbmeyer** [comment]
With the intent of making embed-able HTML in the rendered page?

**Comment by matthewp** [comment]
I'd probably create a plugin that did this:

1) If server rendering embed the HTML into the page when needed, like how the CSS plugin does.
2) On the client fetch as text/plain (if not server-rendered) and inject into the page.

**Comment by justinbmeyer** [comment]
Maybe consider this use case along with the use case you've intended this for: an HTML main for static site generation.

**Comment by matthewp** [comment]
Are you suggesting to trace an HTML's dependencies?

**Comment by frank-dspeed** [comment]
I am interrested in Handling HTML via Javascript even for the steal-server project. At Present i Solve that with a lot of overhead but that leads to nice userbility i simply read .html as string and wrapp it into a jQuery Object.

and then i trace the dependencys via link tags and script tags as also custom component HTML tags that have a url in them
