### ISSUE TITLE
react production build using steal-tools

### ISSUE THREAD

**Issue by reinaldoarrosi** [stealjs/steal-tools#630]
I am using the example available in https://github.com/stealjs/react-example to test stealjs.
The example works fine when following the steps on readme, then I tried to create a production build following these steps:

1. set NODE_ENV='production'
2. run steal-tools build
3. replace steal.js in index.html for ./dist/steal.production.js
4. running the app

The build worked but the following warning is shown when the app runs:

```
Warning: It looks like you're using a minified copy of the development build of React. When deploying React apps to production, make sure to use the production build which skips development warnings and is faster. See https://fb.me/react-minification for more details.
```

It seems that "steal-tools build" is minifying react but it is not removing code that is only used in development. According to react docs setting "NODE_ENV=production" should result in a version of react that does not contain development-only code.

Is this a bug or am I missing some configuration?

**Comment by phillipskevin** [comment]
You can use the minified versions of React during the build by adding this to the `steal` section of your package.json:
```
    "envs": {
      "build-development": {
        "paths": {
          "react": "node_modules/react/dist/react.min.js",
          "react-dom": "node_modules/react-dom/dist/react-dom.min.js"
        }
      }
```

Someone else might have a better option, but this way worked when I tried it out.

**Comment by matthewp** [comment]
Sounds like something that should go in the react-example docs. @reinaldoarrosi want to open an issue there? Or even better, a PR that adds this info to the docs.

**Comment by reinaldoarrosi** [comment]
I've ended up customizing the minify function like this:
```javascript
var envify = require('loose-envify/replace'); // from https://www.npmjs.com/package/loose-envify
var uglify = require('uglify-js'); // from https://www.npmjs.com/package/uglify-js

...

stealtools.build(
{ 
    config: 'package.json!npm' 
}, 
{ 
    minify: function(source, options) {
        var envified = envify(source.code, [process.env]);
        var minified = uglify.minify(envified, { fromString: true });

        source.code = minified.code;
        return source;
    }
}
);
```

I've noticed steal-tools default minify function already uses uglify-js. Shouldn't it also use envify (like I did in my code)?
I think it would benefit not only react, but also any other packages that check for "process.env" since dead-code removal would be able to remove even more code.

**Comment by matthewp** [comment]
@reinaldoarrosi I'm not familiar with envify, maybe it's something we should do. Want to open another issue to discuss what it is?
