### ISSUE TITLE
Make the slim loader basic shim

### ISSUE THREAD

**Issue by matthewp** [stealjs/steal-tools#663]
The basic shim should be able to execute modules that conform to the AMD commonJS format like:

```js
define('bar', function(module, require){
  module.exports = require('bar');
})
```

But note that we are using numbers instead of names and we don't want to use `define` or `require` to prevent any format detection if loaded through another loader (like Steal or webpack).

Also we need to make this work with `script=async` (worry about this in another issue) so we have to account for the loader being executed **after** bundles.

So let's go with this for now (might change it before release):

```js
(_steal=_steal||[]).push([
  [1, function(stealModule, stealRequire){
    stealModule.exports = stealRequire(2);
  }],
  [2, function(stealModule, stealRequire){
    stealModule.exports = "bar";
  }]
]);
```

The basic shim will be attached to the top of this bundle by default. It will also be possible to put the shim into a separate bundle (so you can load multiple bundle in async scripts as the same time without them all having the shim).  but don't worry about that for now.

So the shim needs to be able to execute the above bundle, and it needs to be about the same size as webpack's basic shim (hopefully smaller!).  

See https://github.com/matthewp/webpack-research under the "single" folder which contains their code for loading a single bundle like this.

**Comment by m-mujica** [comment]
The app's code:

```js
// foo.js
module.exports = "foo";
```

```js
// bar.js
module.exports = "bar";
```

```js
// index.js
var foo = require("foo");
var bar = require("bar");

window.foo = foo;
window.bar = bar;
```

The bundle code: 

```js
(function(modules) {
  var cache = {};

  function stealRequire(moduleId) {
    if (cache[moduleId]) {
      return cache[moduleId];
    }

    var mod = cache[moduleId] = {
      exports: {}
    };

    modules[moduleId].call(mod.exports, stealRequire, mod.exports, mod);
    return mod.exports;
  }

  // import the main module
  stealRequire(2);
})([

  /*foo[0]*/
  function(stealRequire, stealExports, module) {
    module.exports = "foo";
  },

  /*bar[1]*/
  function(stealRequire, stealExports, module) {
    module.exports = "bar";
  },

  /*index[2]*/
  function(stealRequire, stealExports, module) {
    var foo = stealRequire(0);
    var bar = stealRequire(1);
    window.foo = foo;
    window.bar = bar;
  }
]);
```

**Comment by matthewp** [comment]
@m-mujica Submit PRs to minor branch I guess (if it doesn't exist create one off of minor).

**Comment by m-mujica** [comment]
```
```

**Comment by m-mujica** [comment]
I think we can close this one based on https://github.com/stealjs/steal-tools/pull/715#issuecomment-304405389 and https://github.com/stealjs/transpile/commit/257d91f942301992d86eb6f36e7eddd8b53693b6
