### ISSUE TITLE
Create basic slim bundler api

### ISSUE THREAD

**Issue by matthewp** [stealjs/steal-tools#666]
This is an internal api that will be used by `stealTools.build`. The name doesn't matter for now, maybe "optimize"? Since this is like an optimization.

# optimize(options)

```js
optimize({
  // An array of steal-tools bundle objects
  bundles: [
    {nodes: [], buildType: 'js'}
  ],

  // Don't worry about the other options for now but this is the idea
  plugins: true,
  otherOptions: true
});
```

With the return value I'm guessing being the bundles array with any shim stuff added to the beginning and/or ends.

**Comment by m-mujica** [comment]
@matthewp in this example https://github.com/stealjs/steal-tools/issues/663#issuecomment-300544185

The generated things looks like this:

```js
(function(modules) {
  ....
})
```

The IIFE with the "loader" logic and then the actual function call with the nodes as an array.

```js
([
     function() {},
     function() {},
     function() {},
])
```

How should we arrange the nodes in the bundle to generate this output? I mean, the node can't contain partial code, so I could unshift the IIFE with the loader code but what about the actual function call?

```js
{ bundle: [
     { /* IIFE loader code */ },
     { /* bundle node */   },
     { /* bundle node */   },
     { /* bundle node */   },
     { /* bundle node */   }
  ]
}
```

Should transpile be responsible of taking the first node and then create the arguments list based on the following nodes in the bundle?

**Comment by m-mujica** [comment]
actually transpile can't do that since transpile gets acts on every node. It's a steal-tools thing... At the concatenate bundle level maybe.

**Comment by matthewp** [comment]
I would think that in "slim mode" it would have a different concat bundle module since, as you said, it does something different from what the regular concatenate would do.  Otherwise, I think you are right, it would just unshift the loader into the bundle array.
