### ISSUE TITLE
Enable progressive loading in slim

### ISSUE THREAD

**Issue by matthewp** [stealjs/steal-tools#667]
I would do this _after_ https://github.com/stealjs/steal-tools/issues/663

Progressive loading is enabled if more than 1 JavaScript bundle exists.

Whatever code needs to be added to the shim to enable progressive loading should **only** exist if progressive loading is needed.

In order to conditional add features like this (and runtime plugin capabilities) we might using a templating approach like we do in DoneJS generators. Just an idea.

----

During the transpile process `System.import` will be converted to something else, let's say `_stealImport` for now, and will look like:

```js
_stealImport(1, 2).then(function(mod){

})
```

Where the first parameter is the module id and the second is the bundle id. This happens during transpile. For the sake of this issue you shouldn't be worried about how this code is transformed.

The bundle id should be used to load `dist/bundles/${id}.js` or whatever.  id might not be a number, could be a string name.

The implementation of `_stealImport` should load the bundle in a script tag, after it has loaded get the module id from the module cache and resolve the promise.

**Comment by m-mujica** [comment]
@matthewp I pushed an example of how the shim would look like based for progressive loading. Still early days, but the example works.

https://github.com/m-mujica/slim-progressive/tree/master/dist/bundles 

Next I want to play with this version and https://github.com/stealjs/steal-tools/issues/668

**Comment by matthewp** [comment]
Cool.  So I think we won't be able to write the bundles like [this](https://github.com/m-mujica/slim-progressive/blob/master/dist/bundles/baz.js#L2) because `__stealBundle` might not exist when this bundle is loaded once you implement `async`.  That's why I suggested the method of:

```js
(_steal=_steal||[]).push([
```

**Comment by m-mujica** [comment]
@matthewp  I got something working with the async script tags

https://github.com/m-mujica/slim-progressive/tree/async/dist/bundles 

![star-wars-terminator-2-mash-up-its-working-anakin-skywalker-14098428930](https://cloud.githubusercontent.com/assets/724877/26132479/dded59d2-3a5d-11e7-8b98-d1f81328b0e2.gif)

thoughts?

**Comment by matthewp** [comment]
Cool, looks pretty good to me. Next I think we should get the basic shim into minor and then this as well. Then you might want to try out the transpiling part.

**Comment by m-mujica** [comment]
@matthewp  just pushed a revised version of the async example based on the changes we discussed yesterday... I'm working on getting steal-tools to output the config node + the revised loader; transpile already outputs the format in that example 

https://github.com/m-mujica/slim-progressive/commit/bb0f1a1393652acb34750ef2c2599d50b24b10b0

**Comment by m-mujica** [comment]
Closed by https://github.com/stealjs/steal-tools/pull/715
