### ISSUE TITLE
Enable slim bundles to be loaded with async scripts

### ISSUE THREAD

**Issue by matthewp** [stealjs/steal-tools#668]
This should come after https://github.com/stealjs/steal-tools/issues/667

A big win for this feature is that bundles can be loaded asynchronously.

```html
<script src="main-bundle.js" async></script>
<script src="bundle-a" async></script>
<script src="bundle-b" async></script>
```

Where **main-bundle.js** contains the loader. It doesn't matter if **bundle-a** or **bundle-b** execute first, because all they do is push a value into an array like:

```js
(_steal=_steal||[]).push([
  [1, function(stealModule, stealRequire){
    stealModule.exports = stealRequire(2);
  }],
  [2, function(stealModule, stealRequire){
    stealModule.exports = "bar";
  }]
]);
```

The loader will know when all necessary bundles have loaded and will execute the modules only when all are complete.

**Comment by m-mujica** [comment]
@matthewp does `main-bundle` imports any of the stuff inside either `bundle-a` or `bundle-b` ? 

Because in that case, the bundles will be part of the `main-bundle` dependency graph and will be bundled into `main-bundle`, right?

I'm trying to set up a simple app with this use case in mind.

**Comment by m-mujica** [comment]
and if `main-bundle` does not need any of the stuff in `bundle-a` or `bundle-b`, why to load them? To preload the "next" page code or something?

**Comment by matthewp** [comment]
No, I don't think `main-bundle` will ever import stuff in `bundle-a` or `bundle-b`.

Yes, the idea is that if you have a `main-bundle` and a `home-bundle` and you are visiting the homepage you can add both script tags have them download in parallel. This prevents the waterfall effect that steal apps have today.

**Comment by m-mujica** [comment]
Closed by https://github.com/stealjs/steal-tools/pull/715
