### ISSUE TITLE
Option `dest` does not support function for cjs output

### ISSUE THREAD

**Issue by ilyavf** [stealjs/steal-tools#683]
As described in [steal-tools/ExportOutput](http://stealjs.com/docs/steal-tools.export.output.html)
dest can be a function. But in the following example its getting ignored (if its a string then its OK):

```js
stealTools.export({
  steal: {
    config: 'package.json!npm',
    main: 'myprop/index'
  },
  outputs: {
    '+cjs': {
      dest: function(moduleName){
            // --- ---- is not getting called.
            return __dirname+"/"+moduleName+".js";
      }
    }
  }
});
```

**Comment by matthewp** [comment]
The code for this stuff is in this folder: https://github.com/stealjs/steal-tools/tree/master/lib/build/helpers
