### ISSUE TITLE
Missing extension when using steal-tools export

### ISSUE THREAD

**Issue by m-mujica** [stealjs/steal-tools#699]
With a configuration, like the one below:

```js
stealTools.export({
  steal: {
    main: "index",
    config: path.join(__dirname, "package.json!npm")
  },
  options: {},
  outputs: {
    "+global-js": {
      format: "global",
      graphs: ["index"],
      dest: path.join(__dirname, "dist", "global")
    }
  }
});
```

steal-tools will write a file with no extension; we could check if the extension was provided and add it when needed maybe?

**Comment by matthewp** [comment]
I'm not a huge fan of "fixing" user mistakes like this. What is the user wanted no extension?

**Comment by m-mujica** [comment]
![preview](https://cloud.githubusercontent.com/assets/724877/25903090/b1a881da-3558-11e7-921b-0edaa8390373.jpeg)

j/k, that makes sense.
