### ISSUE TITLE
steal-conditional boolean throw an error

### ISSUE THREAD

**Issue by pYr0x** [stealjs/steal-tools#711]
i used the steal-conditional boolean syntax to load a module.
`require("~/modules/notice-box#?triwala-vk/modules/notice-box-exists");`

reduce the `notice-box-exists` to the basic the module looks like this:
```
import $ from 'jquery';
const foo = false;
export default foo;
```
when i create a production version i get this error
![image](https://cloud.githubusercontent.com/assets/1126711/26125198/9516571c-3a81-11e7-8cdf-6af728d9055f.png)
the problem is "jquery" but i dont know why.
@m-mujica any idea why jquery cause an error in steal-conditional
if i import a module that does not use jquery i works.
`import '~/util/url';`
**url.js**
```
exports.setLocation = function (url) {
	var htmlDoc = document.getElementsByTagName('html')[0];
	htmlDoc.classList.add('wait');
	window.location.href = url;
	return false;
};
```

**Comment by pYr0x** [comment]
i found out that `module.exports = !!window.document.querySelector('.notice-box');` is not working too.

`window` is not defined. is the problem that while build, the loader is using node and there is not window object present?

**Comment by m-mujica** [comment]
@pYr0x are you using the latest version of steal-conditional?

steal-conditional should not eval your condition module (`notice-box-exists`) during the build

See https://github.com/stealjs/steal-conditional/blob/68283fd641bf97aa969946576fd6c4a05ae0d1cc/conditional.js#L323-L327

I'll try to replicate the `jquery` issue.

**Comment by m-mujica** [comment]
@pYr0x in this case, since you're using the boolean syntax, steal-conditional should make a bundle of `~/modules/notice-box`. https://github.com/stealjs/steal-conditional/blob/68283fd641bf97aa969946576fd6c4a05ae0d1cc/conditional.js#L259

**Comment by pYr0x** [comment]
@m-mujica i used "steal-conditional": "^0.3.2"
`notice-box` is bundled into a file called `index-form-index-bd4d57f2.js`
and 
`notice-box-exists` is also bundled into a file 
```
/*triwala-vk@1.0.0#modules/notice-box-exists*/
define('triwala-vk@1.0.0#modules/notice-box-exists', function (require, exports, module) {
    const loader = require('@loader');
    let ex = false;
    if (loader.isPlatform('window')) {
        ex = !!document.querySelector('.notice-box');
    }
    module.exports = ex;
});
```
and if i use a console.log in the module `notice-box-exists` the output is shown during the build. so the module will be eval during build

**Comment by matthewp** [comment]
Issue moved to [stealjs/steal-conditional #42](https://github.com/stealjs/steal-conditional/issues/42) via [**ZenHub**](https://www.zenhub.com/)
