### ISSUE TITLE
Create a guide for the slim loader

### ISSUE THREAD

**Issue by matthewp** [stealjs/steal-tools#718]
We should create a guide on converting a project to use the slim loader. I think something like donejs-chat would be a good example as it *should* be usable with slim.

**Comment by m-mujica** [comment]
We are going to use the `myhub` application (progressive loading guide) as the example app for the guide. First, I'm working on getting it to work with the slim bundle:

- [x] Get jquery to work when transpiled to slim format
- [ ] Get `justifiedGallery` to transpile correctly (we'd probably need to close https://github.com/stealjs/transpile/issues/81)
- [ ] The weather modlet is not building correctly, seems to be an issue in the ES6 -> AMD -> SLIM transpilation
- [ ] Get less files to build correctly. Need to check why the plugin is being added to the build output

**Comment by matthewp** [comment]
Yeah, need to fix transpile#81.

With regards to less, I believe in normal builds the nodes are included in the build output but they are noops like:

```js
define("less@1.0.0#less", [], function(){});
```

So it's totally acceptable that in slim they are noops like that too.

**Comment by m-mujica** [comment]
the thing I'm trying to fix now with the ES6 -> SLIM transpile is that babel's amd is 

```javascript
define(
  ["exports", "jquery", "bootstrap/dist/css/bootstrap.css", "./weather.css"],
  function(exports, _jquery) {
    "use strict";

    Object.defineProperty(exports, "__esModule", {
      value: true
    });
  }
);
```

is that way of "requiring" `exports` a babel thing I guess? I can't find any reference in the AMD spec about it, except for the CJS wrapper but this is not that.

The transpiled slim version generates a 

```
var exports = stealRequire("exports");
```

which breaks runtime :(

**Comment by matthewp** [comment]
I think this is valid AMD (cjs wrapper is part of AMD).  Probably what I would do is remove the "exports" during transpilation and turn it into:

```js
[
  'some-dep',
  function (stealRequire, stealExports, stealModule) {
    var exports = stealExports;

    var _jquery = stealRequire("jquery");

    "use strict";

    Object.defineProperty(exports, "__esModule", {
      value: true
    });
  }
]; 
```
