### ISSUE TITLE
Provide a way to target Node for slim bundles

### ISSUE THREAD

**Issue by matthewp** [stealjs/steal-tools#719]
The slim shim currently uses `<script>` to load bundles. This obviously won't work in Node, but that's ok.  I'm thinking the approach we take here is to have different targets. `browser` would be the default, we could create a `node` target (and possible a `worker` target in the future).

The Node target would substitute out the script loading code for something that uses Node APIs instead.

**Comment by matthewp** [comment]
Webpack uses a [target config](https://webpack.js.org/concepts/targets/), I think it's a good way to go. I'm thinking:

```js
stealTools.optimize({}, {
  target: 'node'
});
```

Will create a target for Node.js usage. I guess the bundles could go in `dist/bundles/node/` ? Sounds right to me I think...

Then you should also be able to have multiple targets like:

```js
stealTools.optimize({}, {
  target: ['web', 'node']
});
```

Which will create `dist/bundles/web/` and `dist/bundles/node/`.  Typedef would be `[String|Array<String>]` with the default being `web`.  Possible values:

| Value  | Environment                     |
|--------|---------------------------------|
| web    | Browser window                  |
| node   | Node.js (using require() calls) |
| worker | Web worker                      |

I think those are a good start. Create a new issue for the web worker one if you want.

**Comment by m-mujica** [comment]
@matthewp should we change the default output to `dist/bundles/web/`? 

My reasoning is, currently our supported target is browser, which should make these two commands have the same result

```js
steal.Tools.optimize({}, {})
```

and 

```js
steal.Tools.optimize({}, { target: ['web' ]})
```

right? Also, instead of changing the default output to `dis/bundles/web/` we could make it so it only outputs the folder name when there are multiple targets, but that means

```js
steal.Tools.optimize({}, { target: ['node' ]})
```

will write out to `dist/bundles/` by default

**Comment by matthewp** [comment]
Yeah, I suppose adding web/ to the default makes sense even though arg to more nesting!  In the future I'd like to rethink how we handle where bundles are output so there isn't so much nesting, but I guess this can wait until then.

**Comment by matthewp** [comment]
Actually, adding web/ to the default is arguably a breaking change :/ . Anyone who has their prod script tags already set up will see breakage.

**Comment by matthewp** [comment]
Can we go with not adding the target to the path if there is no `target` provided and then adding it if there is, no matter whether there is 1 or more targets?

**Comment by m-mujica** [comment]
sure, we can do that. It's just more code to maintain but changing the default is indeed a breaking change. Will go with that one.
