### ISSUE TITLE
Travis build broken in Node 8

### ISSUE THREAD

**Issue by m-mujica** [stealjs/steal-tools#723]
https://travis-ci.org/stealjs/steal-tools/jobs/238843622#L663

**Comment by m-mujica** [comment]
There a are two failing tests in Node V8, both recycle tests.

I've been debugging this one https://github.com/stealjs/steal-tools/blob/2858ceced90efe47fe6026d6560f7c05585ca8c5/test/recycle_test.js#L170-L238 and for some reason when steal loads `config.js` from the filesystem (which should be mocked at that point) it gets a truncated string 

```js
System.config({ map: { 'bi
```

instead of:

```js
System.config({ map: { 'bit-tabs': 'tabs' } });
```

The filesystem object looks fine (it's not mutated) when steal loads the file, I tried to replicate the issue in a script but with no success so far... :/

**Comment by matthewp** [comment]
probably mock-fs hasn't been updated to work with Node 8.

**Comment by m-mujica** [comment]
yup, https://github.com/tschaub/mock-fs/issues/208 their tests are not passing in Node 8. We could:

1) Skip recycle tests in Node 8
2) Change travis to skip Node 8 while that gets solved
3 Look for a mock-fs alternative? 

What do you think?

**Comment by matthewp** [comment]
Let's skip the recycle tests for now.
