### ISSUE TITLE
See if we can switch to uglify-es

### ISSUE THREAD

**Issue by matthewp** [stealjs/steal-tools#740]
https://www.npmjs.com/package/uglify-es

This supports ES201x code. Assuming it's not breaking in some weird way with the current version of uglify I don't see why we couldn't switch to this in steal-tools 1.x.

**Comment by jonlinnell** [comment]
Yes please – got some issues with uglify breaking when trying to process some ES6 code in a dependency, weirdly. Dev runs fine, but production build fails.

**Comment by m-mujica** [comment]
@jonlinnell in case you missed it, we released steal-tools@1.6.0 with uglify-es, hopefully that fixes your production builds 💥
