### ISSUE TITLE
build errors with steal-vue

### ISSUE THREAD

**Issue by gKreator** [stealjs/steal-tools#746]
Having issues using steal-tools to build this Vue.js project.

console output:
![image](https://user-images.githubusercontent.com/1431487/27254863-393aea22-5357-11e7-9241-4e3c25a08543.png)

package.json
```
{
  "name": "awesome-guy-client",
  "version": "1.0.0",
  "description": "",
  "main": "main.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "MIT",
  "steal": {
    "homeAlias": "@",
    "directories": {
      "lib": "src"
    },
    "configDependencies": [
      "live-reload"
    ],
    "map": {
      "vue": "vue/dist/vue.common"
    },
    "plugins": [
      "steal-vue",
      "steal-css",
      "steal-less"
    ]
  },
  "dependencies": {
    "steal": "^1.0.10",
    "steal-css": "^1.2.4",
    "steal-less": "^1.2.0",
    "steal-socket.io": "^4.0.9",
    "steal-tools": "^1.0.3",
    "steal-vue": "0.0.6",
    "vue": "^2.1.4",
    "vue-router": "^2.5.3",
    "vuex": "^2.3.1",
    "vuex-router-sync": "^4.2.0"
  }
}
```

build.js
```
const stealTools = require("steal-tools");

var buildPromise = stealTools.build({
  config: __dirname + "/package.json!npm"
}, {
  sourceMaps: true,
  sourceMapsContent: true,
  bundleAssets: true,
  minify: true,
  watch: false
});

buildPromise.then(function(buildResult){

})
.then(function(){
  console.log("Build successful");
})
.catch(function(err){
  console.error(err);
});
```

**Comment by matthewp** [comment]
Looks like steal-vue probably has some ES201x code that is not supported by uglify2. Have you tried providing your own minify function: https://stealjs.com/docs/steal-tools.BuildOptions.html That way you can use babili or uglify-es or something else that supports ES201x code.

We are looking into possibly making uglify-es the default in the near-future: https://github.com/stealjs/steal-tools/issues/740

**Comment by gKreator** [comment]
Yeah I had a feeling it was something to do with ES201x, I have not tried that. I was not aware of that ability.

Anyway, If I build with minify:false I get these issues.
![image](https://user-images.githubusercontent.com/1431487/27346364-9481d1e0-55b2-11e7-9c32-83c65ccab68d.png)

**Comment by matthewp** [comment]
How are you loading it? What does your steal script tag look like?

**Comment by gKreator** [comment]
I knew I should of added that sorry.

![image](https://user-images.githubusercontent.com/1431487/27360058-beb6adc8-55e4-11e7-8539-9bc78d4b888f.png)

**Comment by justinbmeyer** [comment]
Is awesome-guy-client the name of your npm package?

What if you provide the name of the main too: "awesome-guy-client/main"?

**Comment by gKreator** [comment]
That worked thanks!

**Comment by justinbmeyer** [comment]
yeah, steal-view needs to export them to the CSS build.  Can you create an issue there?
