### ISSUE TITLE
Expose the slim API

### ISSUE THREAD

**Issue by matthewp** [stealjs/steal-tools#747]
The slim bundler should be exposed through the main `stealTools` namespace. If anyone wants to bikeshed on the name, now is the chance.

So far my best attempt is `stealTools.optimize`.  The pros and cons:

**Pros**

* Conceptually the slim bundler is about optimizing your code to having the smallest possible footprint, by removing all runtime checks in favor of build-time optimizations.

**Cons**

* It's kinda long?
* stealTools.build does code splitting which is a form of optimization. So does calling the api `optimize` make build() sound bad?

**Comment by matthewp** [comment]
cc @justinbmeyer @m-mujica @phillipskevin if anyone has opinions here.

**Comment by pYr0x** [comment]
how about `slimBuild`

**Comment by andrejewski** [comment]
`aot` (Ahead of time)? `stealTools.aotOptimization`

**Comment by matthewp** [comment]
Closed by #765, going with optimize for now!
