### ISSUE TITLE
Provide alternative bundleManifest formats

### ISSUE THREAD

**Issue by matthewp** [stealjs/steal-tools#769]
Currently it is boolean, we could make it take a string for format types.

```js
{
  bundleManifest: "json"
}
```

Would output the current format, and is the same as `true`.  I want to bring up an idea of @justinbmeyer, we could have:

```js
{
  "bundleManifest": "html-snippet"
}
```

Or something like that (bikeshed on the name) that outputs individual snippets corresponding to each page. This way someone using a server templating language could more easily inject the snippets into their pages.

This issue is to figure out what this format should look like, how weights are used, etc.

**Comment by matthewp** [comment]
Primarily part of slim page 2, but not ready to be worked on yet.

**Comment by m-mujica** [comment]
Any concrete idea about this issue? I might be able to take it the current sprint.

**Comment by matthewp** [comment]
Are you saying the above isn't concrete enough 😎

**Comment by matthewp** [comment]
Rather than building these out as HTML snippets I think it makes more sense to do it on the fly. I would propose a new package for dealing with bundle manifests. Something like:

```js
var Handlebars = require("handlebars");
var manifestTools = require("bundle-manifest-tools");

var cartTemplate = Handlebars.compile(`
   {{#links}}
     <link rel="stylesheet" href="{{.}}">
   {{/links}}

   <h1>Cart Page</h1>

    {{#scripts}}
      <script src="{{.}}" async></script>
    {{/scripts}}
`);

var cartAssets = manifestTools.for("app/cart/cart");

require("http").createServer(function(req, res){
  if(isCart(req.url)) {
    var html = someTemplate({
      links: cartAssets.styles
      scripts: cartAssets.scripts
    });

    res.end(html);
  }
}).listen(8080);
```

Or, if you really want strings:

```js
var Handlebars = require("handlebars");
var manifestTools = require("bundle-manifest-tools");

var cartAssets = manifestTools.for("app/cart/cart");

require("http").createServer(function(req, res){
   if(isCart(req.url)) {
    var scripts = manifestTools.stringify(cartAssets.scripts);

    res.end(`
      <h1>Cart Page</h1>
       
      ${scripts}   
    `);
  }
}).listen(8080);
```

**Comment by matthewp** [comment]
Want to show this use-case in some documentation some where.

**Comment by matthewp** [comment]
Probably will do this in steal-bundle-manifest's readme.

**Comment by matthewp** [comment]
This was done and is now on stealjs.com.
