### ISSUE TITLE
Support running multiple builds at the same time.

### ISSUE THREAD

**Issue by justinbmeyer** [stealjs/steal-tools#77]
You can't currently call two builds one after another.  I'm pretty sure this has to do with what System / steal is global.  Hopefully this is something wrong in our code and not SystemJS.  

I'll submit a test shortly.

**Comment by matthewp** [comment]
We have a test of multiple builds running at once: https://github.com/stealjs/steal-tools/blob/eadbbe9014f83ba95bd10910c0049a404c68cee1/test/test.js#L2043
