### ISSUE TITLE
[SLIM] esm named imports not working

### ISSUE THREAD

**Issue by m-mujica** [stealjs/steal-tools#776]
Currently the loader _always_ tries to return `.default` when it sees the `__esModule` flag, this does not work for named imports.

**We need the ES6 -> SLIM transpiler to wrap the `stealRequire` call with the `stealRequire.esm` function only for default imports.**

Babel transpiles the following named import

```js
import { foo } from "./foo";
foo()
```

to 

```js
var _bar = require("./bar");

(0, _bar.foo)();
```

The slim version of this module should look like:

```js
[ 
  "foo", 
  function(stealRequire, stealExports, stealModule) {
    var _bar = stealRequire.esm(stealRequire("bar"));
    (0, _bar.foo)();    
  }
]
```

where `stealRequire.esm` looks at the `__esModule` flag and returns `stealExports.default` instead `stealExports`.

This can be a little bit challenging since we rely on babel to do the transpilation and when we get the AMD output, we no longer know whether a default import was used.

**Comment by m-mujica** [comment]
any thoughts @matthewp? I wonder if there is a way to always return `stealExports` and somehow detect when `stealExports.default` is needed (without having to mess with the ES6 AST).

**Comment by matthewp** [comment]
I think using __esModule is what steal does, so I'd go with that.

**Comment by matthewp** [comment]
We just need to match steal.production.js. If it doesn't have good interop here then we don't need to fix that, yet. But maybe file a separate bug as it's something we *should* fix for sure.
