### ISSUE TITLE
Allow main to be defined in config

### ISSUE THREAD

**Issue by stevenvachon** [stealjs/steal-tools#78]
In dev mode, I have:
```js
steal.config({ main:"main" });
```
and
```html
<script src="path/to/steal.js" data-config="stealconfig.js" data-env="development"></script>
```
and it works.

But when I try to build with:
```js
stealTools.build({ config:"stealconfig.js", bundlesPath:"build/" });
```
I get this error:
```
OPENING: undefined
error [ReferenceError: jQuery is not defined] ReferenceError: jQuery is not defined
```
I don't know exactly why jQuery was involved in this, but I do know that it should read "OPENING: main". Somewhere in the code, `config.main` (pseudo) is not checked for.

**Comment by matthewp** [comment]
This should work now, npm sets the `main` in config.
