### ISSUE TITLE
Lodash Version mismatch

### ISSUE THREAD

**Issue by christopherjbaker** [stealjs/steal-tools#782]
steal-tools depends on lodash@^4.3.0, but [production_env_config](https://github.com/stealjs/steal-tools/blob/master/lib/slim/checks/production_env_config.js) uses defaultTo, which [was introduced in 4.14.0](https://lodash.com/docs/4.17.4#defaultTo).

**Comment by matthewp** [comment]
Thanks, just waiting on https://github.com/stealjs/steal-tools/pull/781

**Comment by matthewp** [comment]
Fixed by #781
