### ISSUE TITLE
Remove: "Can't find dependency ${depName} in graph" warnings 

### ISSUE THREAD

**Issue by m-mujica** [stealjs/steal-tools#815]
Is there any use to these warnings? 
What can the user do anyway?

Since there is nothing actionable about these, I think we should remove them. 

```
WARNING: Can't find dependency npm-extension in graph.
WARNING: Can't find dependency node_modules/steal-conditional/conditional in graph.
WARNING: Can't find dependency npm in graph.
```

**Comment by matthewp** [comment]
I believe this is in the npm extension. I agree about removing them, I thought I already had, actually.

**Comment by m-mujica** [comment]
There are some in steal-tools itself.... I've added some while working on dev bundles and slim loader 😂

**Comment by m-mujica** [comment]
lib/build/transform.js 
lib/graph/pluck.js
lib/stream/filter_bundle_graph.js
