### ISSUE TITLE
The Loader is deeply cloned during transpilation

### ISSUE THREAD

**Issue by matthewp** [stealjs/steal-tools#820]
[This line](https://github.com/stealjs/steal-tools/blob/366d3f9e9c5c4d330899bd49388863a6bd97438c/lib/graph/transpile.js#L44) causes the Loader to be cloned, which means any module that exports a getter causes that getter to be called. I can create a breaking test that has a getter that throws, to demonstrate the problem.

@m-mujica is it possible for us to use `Object.assign()` rather than cloneDeep here? If so I'll create a test and fix this.

**Comment by m-mujica** [comment]
@matthewp yes, I think so.

I saw some code using `_.clone(..., true);` and that's why I started using `deepClone`, sorry about that.
