### ISSUE TITLE
bundleAsset test removed?

### ISSUE THREAD

**Issue by pYr0x** [stealjs/steal-tools#825]
is there a reason why the bundleAsset test was removed?
in 1.x the test was removed, in 0.16 the test exists
https://github.com/stealjs/steal-tools/tree/2371ad6db30e78eac34f61275de112f28f1894a8/test/bundle_assets

**Comment by matthewp** [comment]
I'm not sure, I guess we can add it back. The option is tested more thoroughly in the steal-bundle repo.

**Comment by pYr0x** [comment]
i add it back and add some one more for serviceworker.
