### ISSUE TITLE
Steal build: absolute path does not start at the server root but at the module root

### ISSUE THREAD

**Issue by PieterSwitten** [stealjs/steal-tools#827]
I'm having trouble with building my module because of some absolute paths inside stylesheets to other stylesheets.

The structure of my project looks like this:
```
|– httpdocs
    |– modules
        |– module1
        |– module2
            |– src
                |– app.js
                |– app.stache
                |– app.less
            |– main.js
            |– build.js
            |– package.json
    |– stylesheets
        |– image.less
        |– base.less
        |– colors.less
```

Inside my app.less I import image.less like this:
```
@import "/stylesheets/image.less";
```

In development everything was fine, it could find the `image.less` file. Problem is when I wanted to build the project it failed because steal couldn't find the `image.less`.

Problem is (I think) that the `"@import '/stylesheets/image.less"` does not start at the server root but at the module root so steal searches to `httpdocs/modules/module2/stylesheets/image.less` which obviously does not exists. It should be looking to `httpdocs/stylesheets/image.less`.

I tried to at a path in the package.json to the stylesheets folder like this:
```
"paths": {
    "/stylesheets/*": "../../stylesheets/*.less"
},
```
But it doesn't work..

Anyone a suggestion how I can fix this?

**Comment by matthewp** [comment]
There are two options here:

1) Make the import relative like `@import '../../stylesheets/image.less';`
2) Use the [locate:// scheme](https://stealjs.com/docs/locate.html) to lookup less imports like: `@import 'locate://stylesheets/image.less';`

Steal can't handle absolute paths, as you said it isn't aware of your server setup.

**Comment by matthewp** [comment]
Glad to have you as a new steal user @PieterSwitten! 🤠 Are you using steal for a company project or is this personal stuff?

**Comment by PieterSwitten** [comment]
Thanks @matthewp ! I have solved the issue with a symlink in combination with the `locate://`, I couldn't use the relative path in my case.

I'm using steal for a company project.
