### ISSUE TITLE
optimize build maybe not working with done-autorender?

### ISSUE THREAD

**Issue by matthewp** [stealjs/steal-tools#845]
@pYr0x commented on [Thu Sep 21 2017](https://github.com/stealjs/steal/issues/1275)

__How often can you reproduce it?__ 

- [x] Always
- [ ] Sometimes
- [ ] Rarely
- [ ] Unable
- [ ] I didn’t try

__Description:__
try to build a optimized bundle with done-autorender `"main": "steal-pwa-example/index.stache!done-autorender/no-zone"`
with steal-tools `build` all worked fine.

__Steps to reproduce:__

1. https://github.com/pYr0x/steal-pwa-example/tree/manifest
2. clone and follow the instructions on the readme for nodejs (production)
3. build with `npm run optimize`
4. open the webpage and see the error
```
Uncaught TypeError: Cannot read property 'call' of undefined
    at stealRequire (index.js:187)
    at Object.<anonymous> (index.js:15521)
    at stealRequire (index.js:187)
    at index.js:328
    at index.js:329
```

__Expected results:__
working

__Actual results:__
some module can not loaded.

__Environment:__

| Software                     | Version
| --------------------- | -------
| Steal version              | 1.5.13
| Steal-tools version    | 1.8.4
| node -v                       | 8
| npm -v                        | 5
| Browser                      | chrome
| Operating system      | mac

---

@matthewp commented on [Thu Sep 21 2017](https://github.com/stealjs/steal/issues/1275#issuecomment-331276079)

Thanks! Will take a look.

---

@matthewp commented on [Thu Sep 21 2017](https://github.com/stealjs/steal/issues/1275#issuecomment-331276146)

Going to move this over to steal-tools.

**Comment by pYr0x** [comment]
the problem is that doneautorender use the `module`-module https://github.com/donejs/autorender/blob/master/src/init.js#L3
this is not available on the slim build.

**Comment by matthewp** [comment]
Hm, I don't think that should matter, that module is not used in production. It should be a noop, I think. @m-mujica will look into the problem.

**Comment by pYr0x** [comment]
but it is imported by the template
https://github.com/donejs/autorender/blob/master/src/init.js#L61
https://github.com/donejs/autorender/blob/master/src/template.txt#L1

**Comment by matthewp** [comment]
Thanks, that might be it. I would say we substitute in an empty object.

**Comment by pYr0x** [comment]
i prefer the way to `noop` `module` because then we can catch all other places where `module` is used....
an other solution could be change `init.js` translate method
```js
function translate(load){
			var result = parse(load.source, this, useZones);

			return Promise.all([
				addBundles(result.dynamicImports, load.name),
				Promise.all(result.imports)
			]).then(function(pResults){
				var imports = [pResults[1], result.args].map(function (item) {
					return item.filter((val) => { return val !== 'module' });
				});
				var output = template({
					imports: JSON.stringify(imports[0]),
					args: imports[1].join(", "),
					useZones: useZones,
					intermediate: JSON.stringify(result.intermediate),
					ases: map(result.ases, function(from, name){
						return "\t" + name + ": " + name +"['default'] || " + name;
					}).join(",\n")
				});

				return output;
			});
		}
```

**Comment by matthewp** [comment]
An empty object would be a noop, that's what the `@empty` module is in steal.js

**Comment by m-mujica** [comment]
@matthewp steal deals with AMD's "module" in runtime https://github.com/stealjs/steal/blob/master/src/base/lib/extension-amd.js#L210-L211.

I can't tell by walking the graph that "module" was required. I mean, it's not registered as dependency of any of the nodes. 

Should slim loader `stealRequire` have a conditional for this special case? I don't know how to get this under a flag though, so it will most likely affect the loader size for all apps.

**Comment by m-mujica** [comment]
The other thing about handling it on the loader side, is that we don't know if the "module" import came from AMD. It seems CJS also has special semantics for it https://nodejs.org/api/modules.html#modules_module

**Comment by matthewp** [comment]
I think this can be done in transpile. You know the load's id then (`load.name`). This would be part of amd_slim I imagine.

**Comment by matthewp** [comment]
to be more clear, you can remove "module" from the dependencies during transpile and replace it with a top-level variable. Does that sound right?

**Comment by m-mujica** [comment]
I like it better than modifying the loader.

**Comment by pYr0x** [comment]
I don't think the issue is fully solved.
Pls have a look at this repo https://github.com/pYr0x/steal-pwa-example
Run the optimize build and try to load the app

**Comment by m-mujica** [comment]
I should have created a new issue only for the "module" thing =P 
..... I'll take a look.

**Comment by m-mujica** [comment]
I created a smaller example to replicate the issue here https://github.com/m-mujica/done-autorender-slim

@matthewp the current issue I have is that the done-autorender output relies on `steal` being available as a global, see:

https://github.com/donejs/autorender/blob/ca2943c4d93a4e3e3985dc8596f4eec5424fa925/src/init.js#L16

https://github.com/donejs/autorender/blob/ca2943c4d93a4e3e3985dc8596f4eec5424fa925/src/template.txt#L298 ( this is the one causing the current issue )

The slim loader stores its config in a global called `steal` :|

1) I guess we should make `@steal` a explicit dependency in done-autorender, not sure how to push it to the "import" variable that the template uses.

2) Should we rename the slim loader global? what should happen in the slim builds when someone relies on the `steal` global.

**Comment by matthewp** [comment]
1. Yeah, we should make it explicit. To add it to the template one, do that [here](https://github.com/donejs/autorender/blob/ca2943c4d93a4e3e3985dc8596f4eec5424fa925/src/parse.js#L38) I think . (then run the `build.js` to build the template.

2. Nah, steal is fine.

**Comment by pYr0x** [comment]
i think (as i described here: https://github.com/stealjs/steal-tools/issues/857#issuecomment-332925145) we should rename the global slim loader to something different
