### ISSUE TITLE
bundleAssets is not working with optimize build

### ISSUE THREAD

**Issue by matthewp** [stealjs/steal-tools#846]
@pYr0x commented on [Thu Sep 21 2017](https://github.com/stealjs/steal/issues/1274)

__How often can you reproduce it?__ 

- [x] Always
- [ ] Sometimes
- [ ] Rarely
- [ ] Unable
- [ ] I didn’t try

__Description:__
bundleAssets is not working with optimize build
```
let buildResult = await stealTools.optimize({
        config: path.join(__dirname, "package.json!npm")
    }, {
        bundleAssets: {
            glob: [
                path.join(__dirname, "src", "assets", "**", "*"),
                path.join(__dirname, "src", "styles.css"),
                path.join(__dirname, "src", "manifest.json")
            ]
        },
        minify: true,
        bundlePromisePolyfill: false,
        splitLoader: true
    });
```

__Expected results:__
assets are copied

__Actual results:__
assets are not copied into the dist folder

__Environment:__

| Software                     | Version
| --------------------- | -------
| Steal version              | latest
| Steal-tools version    | latest
| node -v                       | 8
| npm -v                        | 5
| Browser                      | chrome
| Operating system      | mac

**Comment by matthewp** [comment]
Thanks, we probably just need to add it at the end like we did with the multibuild.

**Comment by pYr0x** [comment]
maybe tomorrow i can create a PR. i will see if it is that easy i think

**Comment by matthewp** [comment]
👍
