### ISSUE TITLE
@loader not defined in slim build

### ISSUE THREAD

**Issue by pYr0x** [stealjs/steal-tools#856]
this PR and this line cause an error after build
https://github.com/stealjs/steal-tools/pull/850/files#diff-970f87aa3e6b874cd244518372a6e3f5R90
`moduleId` is `@loader` which is not defined.
the transpiled code looks like this:
```[
		151,
		function(stealRequire, stealExports, stealModule) {
			var atLoader = stealRequire("@loader");
			var steal = {};
			steal.loader = atLoader;
			steal.done = function() {
				return Promise.resolve();
			};
			stealModule.exports = steal;
		}
	],
```

**Comment by m-mujica** [comment]
@pYr0x were you able to replicate this in a small app? A breaking example would be awesome.

The slim build should add an "@loader" shim right after "@steal" is added around here https://github.com/stealjs/steal-tools/blob/master/lib/build/slim.js#L64 

https://github.com/stealjs/steal-tools/blob/34fe1cfab3630de95a62eb0e596e3393aada8e33/lib/build/slim.js#L64

**Comment by m-mujica** [comment]
I just hit this issue 🎉  :|

**Comment by pYr0x** [comment]
was what it?

**Comment by m-mujica** [comment]
There is a stream called `addModuleIds` and it adds the numeric ids to the load object of each node in the graph.

That stream also sets a normalize hook so the module identifiers are replaced by transpile

https://github.com/stealjs/steal-tools/blob/34fe1cfab3630de95a62eb0e596e3393aada8e33/lib/stream/add_module_ids.js#L31-L36

So, we pretty much push the `@loader` shim node to the graph, and it happens that the `load` object normalize expects there is `undefined`.

I had to change the function to check if `graph[name]` is available and get the numeric id from there.

makes sense?
