### ISSUE TITLE
[SLIM] Missing System object from @steal shim

### ISSUE THREAD

**Issue by m-mujica** [stealjs/steal-tools#860]
This code breaks in done-autorender

```js
if (steal.System.autorenderAutostart !== false) {
  if (useZones) {
    reattachWithZone();
  } else {
    connectViewModelAndAttach();
  }
}
```

@matthewp should we make it an empty object?

**Comment by matthewp** [comment]
Update done-autorender to use `steal.loader` instead. steal.System is for backwards compat only, I don't want new APIs to support that.
