### ISSUE TITLE
Bundle assets test is failing on Node 4

### ISSUE THREAD

**Issue by m-mujica** [stealjs/steal-tools#871]
https://travis-ci.org/stealjs/steal-tools/jobs/283397367#L1398-L1408

**Comment by pYr0x** [comment]
i removed `this.end()` on multibuild
https://github.com/stealjs/steal-tools/pull/848#discussion_r140461132
but i dont know if this cause the error

**Comment by m-mujica** [comment]
forgot how annoying is to debug stuff on Node before `--inspect` 😢

**Comment by m-mujica** [comment]
https://github.com/stealjs/steal-bundler/pull/33
