### ISSUE TITLE
Flaky live-reload test in Node 6

### ISSUE THREAD

**Issue by m-mujica** [stealjs/steal-tools#873]
I've seen [this test](https://github.com/stealjs/steal-tools/blob/369d9f8d82222f9642e6ff6be6169ea5b5f9eb2b/test/test_live.js#L62) fail a couple of times and then pass on a rebuild. 

Need to figure out what's causing it to throw sometimes.

**Comment by matthewp** [comment]
Node 6 is no longer supported.
