### ISSUE TITLE
Disabling minify breaks envify option

### ISSUE THREAD

**Issue by imaustink** [stealjs/steal-tools#925]
Using `minify: false` with `envify: true` breaks the `envify` option.

```
var stealTools = require("steal-tools");

var buildPromise = stealTools.build({
  config: __dirname + "/package.json!npm"
}, {
  envify: true,
  minify: false
});
```

**Comment by m-mujica** [comment]
> breaks the envify option.
steal-tools would not inline the string value when minify is false.

**Comment by imaustink** [comment]
So this is expected behavior?

**Comment by m-mujica** [comment]
Nope, I was just translating for myself what "breaks the envify option" meant, for a moment there I thought it could break the build or something. 

It is indeed a bug, PR here https://github.com/stealjs/steal-tools/pull/965

**Comment by imaustink** [comment]
👏
