### ISSUE TITLE
Unable to load CSS

### ISSUE THREAD

**Issue by Kleppo** [stealjs/steal-tools#926]
We see a lot of these errors in our errorlog:

```
Error loading "login@1.0.0#styles.less!steal-less@1.2.2#less" at ***/production/login/src/styles.less 
Error loading "login@1.0.0#styles.less!steal-less@1.2.2#less" from "main" at ***/production/login/main.js 
Error loading "bundles/main.css!steal-css@1.3.1#css" at ***/production/login/bundles/main.css Unable to load CSS
```

We use the steal-less plugin to import our less files, with 'steal-tools build' we make a production bundle. The error doesn't show up every time. (We haven't seen it ourselves, but we monitor it with trackjs)

**Comment by pYr0x** [comment]
1. css files exists after build?
2. you load the plugins as described in https://stealjs.com/docs/StealJS.configuration.html#plugins or  https://stealjs.com/docs/steal-less.html

**Comment by Kleppo** [comment]
1. The css file 'production/login/bundles/main.css' DOES exist
2. we use it as described in the seconde link (https://stealjs.com/docs/steal-less.html)
3. There indeed is no *.less file in the production-folder. That's one of the things I don't understand, why does it look for one?!

**Comment by jeroencornelissen** [comment]
+1

**Comment by pYr0x** [comment]
can you provide a sample code? or the steal-part of your package.json file?

**Comment by jeroencornelissen** [comment]
@pYr0x this is the steal-part of our `package.json`

```
"steal": {
    "main": "main.js",
    "directories": {
      "lib": "src"
    },
    "plugins": [
      "steal-less",
      "steal-stache"
    ],
    "lessOptions": {
      "relativeUrls": false
    },
    "paths": {
      "smsc": "../../../../smsc/resources/stealjs-smsc/stealjs-smsc.js",
      "utils/*": "../../../../smsc/desktop/utils/*.js",
      "components/*": "../../../../smsc/desktop/components/*.js",
      "includes/*": "../../../../includes/*.js",
      "modernizr/*": "../../../../smsc/resources/modernizr/*.js"
    },
    "bundle": [
      "wicg-focus-ring/dist/focus-ring"
    ],
    "transpiler": "babel",
    "npmAlgorithm": "flat"
  },
```

This is how we load the JS (`Steal` is bundled in the `main.js`):
```
<script src="/production/Authentication/login/bundles/main.js" base-url="/production/Authentication/login" bundles-path="./bundles" cache-key="rev" cache-version="0e80f4bb-c7c5-4fbc-9b5f-26a57b9d9890"></script>
```

Hope that helps.

**Comment by pYr0x** [comment]
pls add "steal-css" as a plugin as well

**Comment by pYr0x** [comment]
gone close this.
since there is no response from the OP

**Comment by Kleppo** [comment]
I added the 'steall-css' plugin in all the packages, but the error still shows up in trackjs..
