### ISSUE TITLE
incorrect bundle path with steal-tools@1.11.1 

### ISSUE THREAD

**Issue by phillipskevin** [stealjs/steal-tools#939]
I ran into a bug running the canjs test suite with steal-tools@1.11.1. For some reason the path to `can.js` does not contain `/global` with the most recent patch. You can reproduce this by checkout out [canjs#master](https://github.com/canjs/canjs/), running `npm run build && npm run build-tests`, and then loading the `test/production.html` file in the browser.

With steal-tools@1.11.0:
![image](https://user-images.githubusercontent.com/5851984/35595919-df44e6e6-05dd-11e8-8931-35b10db969fa.png)

With steal-tools@1.11.1:
![image](https://user-images.githubusercontent.com/5851984/35595904-d6342b84-05dd-11e8-88b8-c563e43b2062.png)

**Comment by m-mujica** [comment]
This branch indeed makes the test pass again but I noticed with `1.11.0` (and with this branch) that one of the test throws the following error to the console 

<img width="1440" alt="screen shot 2018-01-30 at 4 57 41 pm" src="https://user-images.githubusercontent.com/724877/35598626-cb9e1a32-05e1-11e8-977c-a3c6f7359a77.png">

which is the same error preventing the tests to run at all in `1.11.1`, looking into that.

**Comment by m-mujica** [comment]
This is the test causing that error https://github.com/canjs/can-view-import/blob/f356e123ddaf8746cdbbdc102a5691c81a3563ea/can-view-import_test.js#L55-L65

**Comment by phillipskevin** [comment]
@m-mujica do you think that error is related? I assume it has always been that way. Thanks for pointing it out, either way.
