### ISSUE TITLE
Code stripping leaves code in bundle

### ISSUE THREAD

**Issue by DaveO-Home** [stealjs/steal-tools#978]
Code not removed, application can be found  @ github.com/DaveO-Home/embedded-acceptance-tests
Upgrade steal-tools from directory public  and run `gulp` from stealjs/build.  index.js will be located @
dist/bundles/stealjs/appl/js/
You will find that `testit` is not stripped.  The app fails because "testit" is undefined.

    //!steal-remove-start
            if (testit) {
                describe("Popper Defined - required for Bootstrap", function () {

                    it("is JQuery defined", function () {
                        expect(typeof $ === "function").toBe(true);
                    });

                    it("is Popper defined", function () {
                        expect(typeof Popper === "function").toBe(true);
                    });

                });
            }
    //!steal-remove-end

**Comment by matthewp** [comment]
Are you in Windows by any chance? There's a bug fix not released yet.

**Comment by matthewp** [comment]
Yes, steal-tools doesn't use NODE_ENV unless you are using envify.

**Comment by DaveO-Home** [comment]
Verified that 1.12.0-pre.0 fixes the problem.

**Comment by matthewp** [comment]
Ok, I think I can do a patch release with that bug fix.

**Comment by matthewp** [comment]
This was released in 1.11.8.

**Comment by DaveO-Home** [comment]
1.11.8 verified - thanks
