### ISSUE TITLE
steal 2.0 breaks slim builder

### ISSUE THREAD

**Issue by pYr0x** [stealjs/steal-tools#996]
i tried to create an example

**Comment by matthewp** [comment]
Could be related to https://github.com/stealjs/steal/pull/1399. Going to try and fix that one today, then let's see how things look.

**Comment by pYr0x** [comment]
here is an example
https://github.com/pYr0x/steal-slim

if you looking into the build file you see:
```
function(stealRequire) {
			stealRequire("../steal-slim@1.0.0#components/foo/foo");
			stealRequire(
				"../steal-slim@1.0.0#components/foo/foo.stache!steal-stache@4.1.0#steal-stache"
			);
			stealRequire("../can-component@4.0.7#can-component");
			("use strict");
		}
````
the names of the modules are not translated to the numbers.

**Comment by matthewp** [comment]
Thanks for the demo! I'll look into this as soon as #1399 is merged in. Some steal-tools tests are currently breaking so hopefully it's the same thing.

**Comment by matthewp** [comment]
Ok, I can recreate. it's definitely related to the tree-shaking changes.

**Comment by matthewp** [comment]
This works as of 2.0.0-pre.10
