### ISSUE TITLE
development bundle fails with steal-stache

### ISSUE THREAD

**Issue by pYr0x** [stealjs/steal-tools#997]
if you running `steal-tools bundle --dev` and have `steal-stache` as a dependency, you will get this error:

![image](https://user-images.githubusercontent.com/1126711/40307160-a75be240-5d01-11e8-90f1-7c3a9a10306f.png)

you can use this repo for testing: https://github.com/pYr0x/steal-slim

**Comment by matthewp** [comment]
Is this steal@pre?

**Comment by pYr0x** [comment]
yes, but it fails on current stable release too

**Comment by pYr0x** [comment]
this works for now. maybe i had an old version of steal-tools installed globally...
